// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { WorkspaceErrors } from '../errors/workspace.errors';

/**
 * Id Value Object
 * Represents a validated id with business rules
 */
export const WorkspaceId = createStringVO({
  name: 'Id',
  trim: true,
  caseTransform: 'none',
  allowEmpty: false,
  minLength: 10,
  maxLength: 32,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(WorkspaceErrors.INVALID_ID, 'Id'),
});

/**
 * Public instance type for Id
 */
export type WorkspaceId = StringVOInstance;

// Convenience creators
export const createWorkspaceId = (s: string) => WorkspaceId.create(s);
export const workspaceIdFrom = (v: unknown) => WorkspaceId.from(v);
