// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { QueryHandler, IQueryHandler } from '@nestjs/cqrs';
import { Injectable } from '@nestjs/common';
import { DomainError, Result } from 'src/shared/errors';
import { ListTemplateQuery } from '../queries';
import { ListTemplateUseCase } from '../use-cases';
import { TemplatePageResponse } from '../dtos';

/**
 * ✅ Enhanced CQRS Query Handler with use case delegation
 * Follows the pattern: Handler → Use Case → Repository
 */
@Injectable()
@QueryHandler(ListTemplateQuery)
export class ListTemplateHandler implements IQueryHandler<ListTemplateQuery> {
  constructor(private readonly listTemplateUseCase: ListTemplateUseCase) {}

  /**
   * Handle the list template query by delegating to the use case
   */
  async execute(
    query: ListTemplateQuery,
  ): Promise<Result<TemplatePageResponse, DomainError>> {
    // ✅ Delegate to use case for business logic
    return await this.listTemplateUseCase.execute({
      user: query.user,
      filter: query.filter,
      correlationId: query.correlationId || 'unknown',
    });
  }
}
