// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

/**
 * TestSecurity Application Service
 *
 * Application-layer service that coordinates authorization with business operations.
 */

// Framework imports
import { Inject, Injectable } from '@nestjs/common';

// Shared utilities and infrastructure
import { APP_LOGGER, Log, componentLogger, Logger } from 'src/shared/logging';
import { Result, DomainError, err, ok, withContext } from 'src/shared/errors';
import type { IUserToken } from 'src/shared/security';
import { CorrelationUtil } from 'src/shared/utilities/correlation.util';
import { Clock, CLOCK } from 'src/shared/infrastructure/time';

// Service configuration
import { WebhookConfigServiceConstants } from '../../../service-constants';

// Domain types and errors
import { TestSecurityErrors } from '../../domain/errors/test-security.errors';
import type {
  CreateTestSecurityProps,
  UpdateTestSecurityProps,
} from '../../domain/props';
import {
  DetailTestSecurityResponse,
  ListTestSecurityFilterRequest,
  TestSecurityPageResponse,
} from '../dtos';

// Application layer
import { TestSecurityAuthorizationService } from './test-security-authorization.service';
import { TestSecurityAuthContext } from '../types/test-security-auth-context';

// Use case contracts
import {
  ICreateTestSecurityUseCase,
  IUpdateTestSecurityUseCase,
  IDeleteTestSecurityUseCase,
  IGetTestSecurityUseCase,
  IListTestSecurityUseCase,
} from '../use-cases/contracts';

/**
 * Application Service for TestSecurity operations with integrated authorization
 */
@Injectable()
export class TestSecurityApplicationService {
  private readonly logger: Logger;

  constructor(
    private readonly testSecurityAuthorizationService: TestSecurityAuthorizationService,
    private readonly createTestSecurityUseCase: ICreateTestSecurityUseCase,
    private readonly updateTestSecurityUseCase: IUpdateTestSecurityUseCase,
    private readonly deleteTestSecurityUseCase: IDeleteTestSecurityUseCase,
    private readonly getTestSecurityUseCase: IGetTestSecurityUseCase,
    private readonly listTestSecurityUseCase: IListTestSecurityUseCase,
    @Inject(CLOCK) private readonly clock: Clock,
    @Inject(APP_LOGGER) moduleLogger: Logger,
  ) {
    this.logger = componentLogger(
      moduleLogger,
      'TestSecurityApplicationService',
    );
  }

  /**
   * Helper to create TestSecurityAuthContext from user token
   */
  private createAuthContext(
    user: IUserToken,
    operation: string,
  ): TestSecurityAuthContext {
    return {
      tenant: user.tenant,
      tenant_userId: user.tenant_id || '',
      roles: user.roles || [],
      operationType: operation,
      metadata: {
        userId: user.sub,
        timestamp: this.clock.nowIso(),
      },
    };
  }

  /**
   * Helper to create consistent logging context
   */
  private createLogContext(
    operation: string,
    correlationId: string,
    userId: string,
    additionalContext?: Record<string, unknown>,
  ): Record<string, unknown> {
    return {
      serviceName: WebhookConfigServiceConstants.SERVICE_NAME,
      component: 'TestSecurityApplicationService',
      operation,
      correlationId,
      userId,
      ...additionalContext,
    };
  }

  /**
   * Helper to validate required id input
   */
  private validateId(
    id: string,
    operation: string,
    correlationId?: string,
  ): Result<string, DomainError> {
    if (!id?.trim()) {
      return err(
        withContext(TestSecurityErrors.INVALID_TEST_SECURITY_DATA, {
          operation,
          correlationId:
            correlationId ||
            CorrelationUtil.generateForOperation(`test-security-${operation}`),
        }),
      );
    }
    return ok(id.trim());
  }

  /**
   * Centralized auth → log → execute → catch pattern
   */
  private async authorizeThenExecute<T>(args: {
    operation: 'create' | 'update' | 'delete' | 'read';
    user: IUserToken;
    id?: string;
    correlationIdPrefix: string;
    doAuthorize: () => Promise<Result<boolean, DomainError>>;
    doExecute: () => Promise<Result<T, DomainError>>;
    logContext?: Record<string, unknown>;
  }): Promise<Result<T, DomainError>> {
    const corrId = CorrelationUtil.generateForOperation(
      args.correlationIdPrefix,
    );
    const ctx = {
      ...this.createLogContext(
        `${args.operation}_test_security`,
        corrId,
        args.user.sub,
        args.logContext,
      ),
    };

    const auth = await args.doAuthorize();
    if (!auth.ok) {
      Log.warn(this.logger, `${args.operation} authorization failed`, {
        ...ctx,
        authDecision: 'deny',
      });
      return err(auth.error);
    }
    if (!auth.value) {
      Log.warn(this.logger, `${args.operation} permission denied`, {
        ...ctx,
        authDecision: 'deny',
      });
      return err(
        withContext(TestSecurityErrors.PERMISSION_DENIED, {
          correlationId: corrId,
          userId: args.user.sub,
          operation: args.operation,
          id: args.id,
          category: 'security',
        }),
      );
    }

    Log.info(this.logger, `TestSecurity ${args.operation} authorized`, {
      ...ctx,
      authDecision: 'allow',
    });

    try {
      return await args.doExecute();
    } catch (error) {
      Log.error(this.logger, `TestSecurity ${args.operation} use case failed`, {
        ...ctx,
        error: error instanceof Error ? error.message : String(error),
      });
      return err({
        code: `DOMAIN.TEST_SECURITY.${args.operation.toUpperCase()}_FAILED`,
        title: `TestSecurity ${args.operation} failed`,
        detail: error instanceof Error ? error.message : 'Unknown error',
        category: 'application',
        context: {
          correlationId: corrId,
          id: args.id,
          operation: `${args.operation}_test_security`,
        },
      });
    }
  }

  /**
   * Create a new testSecurity with authorization
   */
  async createTestSecurity(
    user: IUserToken,
    props: CreateTestSecurityProps,
    options?: { idempotencyKey?: string; correlationId?: string },
  ): Promise<Result<DetailTestSecurityResponse, DomainError>> {
    const authContext = this.createAuthContext(user, 'create');
    const correlationId =
      options?.correlationId ||
      CorrelationUtil.generateForOperation('test-security-create');

    return this.authorizeThenExecute<DetailTestSecurityResponse>({
      operation: 'create',
      user,
      correlationIdPrefix: 'test-security-create',
      doAuthorize: () =>
        this.testSecurityAuthorizationService.canCreateTestSecurity(
          user.sub,
          correlationId,
          authContext,
        ),
      doExecute: () =>
        this.createTestSecurityUseCase.execute({
          user,
          props,
          correlationId,
          authorizationReason: 'create_test_security',
          ...(options?.idempotencyKey && {
            idempotencyKey: options.idempotencyKey,
          }),
        }),
    });
  }

  /**
   * Update an existing testSecurity with authorization
   */
  async updateTestSecurity(
    user: IUserToken,
    id: string,
    props: UpdateTestSecurityProps,
    options?: { idempotencyKey?: string; correlationId?: string },
  ): Promise<Result<DetailTestSecurityResponse, DomainError>> {
    // Early input validation
    const idValidation = this.validateId(id, 'update');
    if (!idValidation.ok) {
      return err(idValidation.error);
    }

    const validatedid = idValidation.value;
    const authContext = this.createAuthContext(user, 'update');
    const correlationId =
      options?.correlationId ||
      CorrelationUtil.generateForOperation('test-security-update');

    // Optional: Field-level authorization
    // Uncomment when TestSecurityAuthorizationService supports authorizeTestSecurityOperation
    /*
    const fields = extractDefinedFields(props); // Use shared utility
    const opAuth = await this.testSecurityAuthorizationService.authorizeTestSecurityOperation(
      user.sub, 
      'update', 
      CorrelationUtil.generateForOperation('test-security-update'), 
      validatedid, 
      fields, 
      authContext
    );
    if (!opAuth.ok) return err(opAuth.error);
    if (!opAuth.value.authorized) {
      return err(withContext(TestSecurityErrors.PERMISSION_DENIED, { 
        operation: 'update', 
        id: validatedid, 
        userId: user.sub,
        category: 'security'
      }));
    }
    */

    return this.authorizeThenExecute<DetailTestSecurityResponse>({
      operation: 'update',
      user,
      id: validatedid,
      correlationIdPrefix: 'test-security-update',
      doAuthorize: () =>
        this.testSecurityAuthorizationService.canUpdateTestSecurity(
          user.sub,
          validatedid,
          correlationId,
          authContext,
        ),
      doExecute: () =>
        this.updateTestSecurityUseCase.execute({
          user,
          id: validatedid,
          props,
          correlationId,
          authorizationReason: 'update_test_security',
          ...(options?.idempotencyKey && {
            idempotencyKey: options.idempotencyKey,
          }),
        }),
      logContext: { id: validatedid },
    });
  }

  /**
   * Delete a testSecurity with authorization
   */
  async deleteTestSecurity(
    user: IUserToken,
    id: string,
  ): Promise<Result<void, DomainError>> {
    // Early input validation
    const idValidation = this.validateId(id, 'delete');
    if (!idValidation.ok) {
      return err(idValidation.error);
    }

    const validatedid = idValidation.value;
    const authContext = this.createAuthContext(user, 'delete');

    return this.authorizeThenExecute<void>({
      operation: 'delete',
      user,
      id: validatedid,
      correlationIdPrefix: 'test-security-delete',
      doAuthorize: () =>
        this.testSecurityAuthorizationService.canDeleteTestSecurity(
          user.sub,
          validatedid,
          CorrelationUtil.generateForOperation('test-security-delete'),
          authContext,
        ),
      doExecute: () => {
        // Log high-risk operation before execution
        Log.warn(
          this.logger,
          'TestSecurity deletion authorized - HIGH RISK OPERATION',
          {
            id: validatedid,
            userId: user.sub,
            riskLevel: 'HIGH',
            operation: 'delete_test_security',
          },
        );
        return this.deleteTestSecurityUseCase.execute({
          user,
          id: validatedid,
          correlationId: CorrelationUtil.generateForOperation(
            'test-security-delete',
          ),
          authorizationReason: 'delete_test_security',
        });
      },
      logContext: { id: validatedid, riskLevel: 'HIGH' },
    });
  }

  /**
   * Get a testSecurity by ID with authorization
   */
  async getTestSecurityById(
    user: IUserToken,
    id: string,
  ): Promise<Result<DetailTestSecurityResponse, DomainError>> {
    // Early input validation
    const idValidation = this.validateId(id, 'read');
    if (!idValidation.ok) {
      return err(idValidation.error);
    }

    const validatedid = idValidation.value;
    const authContext = this.createAuthContext(user, 'read');

    return this.authorizeThenExecute<DetailTestSecurityResponse>({
      operation: 'read',
      user,
      id: validatedid,
      correlationIdPrefix: 'test-security-read',
      doAuthorize: () =>
        this.testSecurityAuthorizationService.canReadTestSecurity(
          user.sub,
          validatedid,
          CorrelationUtil.generateForOperation('test-security-read'),
          authContext,
        ),
      doExecute: () =>
        this.getTestSecurityUseCase.execute({
          user,
          id: validatedid,
          correlationId:
            CorrelationUtil.generateForOperation('test-security-read'),
        }),
      logContext: { id: validatedid },
    });
  }

  /**
   * List testSecurities with authorization and pagination
   */
  async listTestSecurities(
    user: IUserToken,
    filter?: ListTestSecurityFilterRequest,
  ): Promise<Result<TestSecurityPageResponse, DomainError>> {
    const authContext = this.createAuthContext(user, 'list');
    const correlationId =
      CorrelationUtil.generateForOperation('test-security-list');

    // Ensure we always have a proper filter object
    const safeFilter = filter || new ListTestSecurityFilterRequest();

    return this.authorizeThenExecute<TestSecurityPageResponse>({
      operation: 'read', // List is a form of read operation
      user,
      correlationIdPrefix: 'test-security-list',
      doAuthorize: () =>
        this.testSecurityAuthorizationService.canReadTestSecurity(
          user.sub,
          'list', // Use 'list' as a special id for list operations
          correlationId,
          authContext,
        ),
      doExecute: () =>
        this.listTestSecurityUseCase.execute({
          user,
          filter: safeFilter,
          correlationId,
        }),
      logContext: {
        operation: 'list_test_securities',
        pageSize: safeFilter.size,
        page: safeFilter.page,
      },
    });
  }
}
