// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { DomainError, Result, ok, err } from 'src/shared/errors';
import {
  createIntegerVO,
  createIntegerVOErrors,
  IntegerVOInstance,
  createDateTimeVO,
  createDateTimeVOErrors,
  DateTimeVOInstance,
} from 'src/shared/domain/value-objects';
import { Clock } from 'src/shared/domain/clock';
import { LookupTypeErrors } from '../errors/lookup-type.errors';

/**
 * LookupType Instance Value Objects
 *
 * Instance VOs for LookupType aggregate lifecycle management.
 * Includes creation timestamps, update timestamps, and version tracking.
 * Follows the Clock injection pattern for deterministic testing.
 */

// ===========================================
// LookupType Created At Instance VO
// ===========================================

const LookupTypeCreatedAtErrors = createDateTimeVOErrors(
  LookupTypeErrors.CREATED_AT_REQUIRED,
  'LookupType Created At',
);

export const LookupTypeCreatedAt = createDateTimeVO({
  name: 'LookupTypeCreatedAt',
  allowFuture: false, // Cannot create lookup_type in the future
  allowPast: true, // Can create with past timestamps (data migration)
  customValidation: (date: Date): Result<void, DomainError> => {
    // Optional: Add domain-specific creation time validation
    // For example, cannot be more than 1 year in the past
    const oneYearAgo = new Date();
    oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);

    if (date < oneYearAgo) {
      return err({
        ...LookupTypeErrors.CREATED_AT_REQUIRED,
        detail:
          'LookupType creation date cannot be more than 1 year in the past',
        context: { value: date, maxPastDate: oneYearAgo },
      } as DomainError);
    }

    return ok(undefined);
  },
  errors: LookupTypeCreatedAtErrors,
});

export type LookupTypeCreatedAt = DateTimeVOInstance;

// ===========================================
// LookupType Updated At Instance VO
// ===========================================

const LookupTypeUpdatedAtErrors = createDateTimeVOErrors(
  LookupTypeErrors.UPDATED_AT_REQUIRED,
  'LookupType Updated At',
);

export const LookupTypeUpdatedAt = createDateTimeVO({
  name: 'LookupTypeUpdatedAt',
  allowFuture: false, // Cannot update lookup_type in the future
  allowPast: true, // Can update with past timestamps (data correction)
  errors: LookupTypeUpdatedAtErrors,
});

export type LookupTypeUpdatedAt = DateTimeVOInstance;

// ===========================================
// LookupType Version Instance VO
// ===========================================

const LookupTypeVersionErrors = createIntegerVOErrors(
  LookupTypeErrors.INVALID_CODE_DATA, // Reusing existing error until specific version error is added
  'LookupType Version',
);

export const LookupTypeVersion = createIntegerVO({
  name: 'LookupTypeVersion',
  min: 0, // Version starts at 0
  allowNegative: false,
  errors: LookupTypeVersionErrors,
});

export type LookupTypeVersion = IntegerVOInstance;

// ===========================================
// Clock-Based Helper Functions (Explicit Dependencies)
// ===========================================

/**
 * Create LookupTypeCreatedAt from Clock (explicit dependency)
 * Deterministic and testable - pass a fake clock in tests
 */
export const createdAtNow = (
  clock: Clock,
): Result<LookupTypeCreatedAt, DomainError> =>
  LookupTypeCreatedAt.create(clock.now());

/**
 * Create LookupTypeUpdatedAt from Clock (explicit dependency)
 * Deterministic and testable - pass a fake clock in tests
 */
export const updatedAtNow = (
  clock: Clock,
): Result<LookupTypeUpdatedAt, DomainError> =>
  LookupTypeUpdatedAt.create(clock.now());

/**
 * Bump version by 1 (domain business rule)
 */
export const bumpVersion = (
  currentVersion: LookupTypeVersion,
): Result<LookupTypeVersion, DomainError> =>
  LookupTypeVersion.create(currentVersion.value + 1);

/**
 * Create initial version (starts at 1 for new aggregates)
 */
export const initialVersion = (): Result<LookupTypeVersion, DomainError> =>
  LookupTypeVersion.create(1);

// ===========================================
// Direct Creation Functions (Non-Clock Based)
// ===========================================

/**
 * Create LookupTypeCreatedAt from Date
 */
export const createLookupTypeCreatedAt = (
  date: Date,
): Result<LookupTypeCreatedAt, DomainError> => LookupTypeCreatedAt.create(date);

/**
 * Create LookupTypeUpdatedAt from Date
 */
export const createLookupTypeUpdatedAt = (
  date: Date,
): Result<LookupTypeUpdatedAt, DomainError> => LookupTypeUpdatedAt.create(date);

/**
 * Create LookupTypeVersion from number
 */
export const createLookupTypeVersion = (
  version: number,
): Result<LookupTypeVersion, DomainError> => LookupTypeVersion.create(version);

// ===========================================
// Domain Invariants & Validation
// ===========================================

/**
 * Validate that updatedAt is not before createdAt (monotonic time)
 */
export const validateMonotonicTime = (
  createdAt: LookupTypeCreatedAt,
  updatedAt: LookupTypeUpdatedAt,
): Result<void, DomainError> => {
  if (updatedAt.value < createdAt.value) {
    return err({
      ...LookupTypeErrors.UPDATED_AT_REQUIRED,
      detail: 'Updated at cannot be before created at',
      context: {
        createdAt: createdAt.value.toISOString(),
        updatedAt: updatedAt.value.toISOString(),
      },
    } as DomainError);
  }
  return ok(undefined);
};

// ===========================================
// Legacy Compatibility (DEPRECATED)
// ===========================================

/**
 * @deprecated Use createdAtNow(clock) instead for better testability
 * This function hides the Date dependency and makes testing harder
 */
export function createLookupTypeCreatedAtNow(): Result<
  LookupTypeCreatedAt,
  DomainError
> {
  return LookupTypeCreatedAt.create(new Date());
}

/**
 * @deprecated Use updatedAtNow(clock) instead for better testability
 * This function hides the Date dependency and makes testing harder
 */
export function createLookupTypeUpdatedAtNow(): Result<
  LookupTypeUpdatedAt,
  DomainError
> {
  return LookupTypeUpdatedAt.create(new Date());
}
