// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { EventDataProcessingUtils } from 'src/shared/infrastructure/events/utilities/event-data-processing.utils';

/**
 * LookupXxx Field Validator Utility
 *
 * Centralized utility for parsing and validating LookupXxx aggregate data from EventStore events.
 * Provides consistent field validation patterns that can be reused across repositories
 * and projectors for LookupXxx domain operations.
 *
 * @domain Notification Context - LookupXxx Field Validation Utility
 * @layer Infrastructure
 * @pattern Utility Pattern + Field Validation
 */
export class LookupXxxFieldValidatorUtil {
  /**
   * Create projector data with SecretRef objects for Redis storage
   *
   * This method extracts SecretRef objects from event data and serializes them
   * as JSON strings for storage in Redis. The reader repository will deserialize
   * and resolve these SecretRef objects back to actual secret values.
   *
   * @param aggregateData - Raw event data from EventStore containing SecretRef objects
   * @returns Projector data object with SecretRef fields as JSON strings
   */
  static createLookupXxxProjectorDataFromEventData(
    aggregateData: Record<string, any>,
  ): {
    lookupType: string;
    code: string;
    name: string;
    description?: string;
    enabled?: boolean;
    attributes?: string;
    version: number;
    createdAt: Date;
    updatedAt: Date;
  } {
    const lookupType = aggregateData.lookupType as string;
    const code = aggregateData.code as string;
    const name = aggregateData.name as string;
    const description = aggregateData.description as string;
    const enabled =
      aggregateData.enabled === 'true' || aggregateData.enabled === true;
    const attributes = aggregateData.attributes
      ? JSON.stringify(aggregateData.attributes)
      : undefined;

    // Extract version and timestamps with proper type conversion
    const version = EventDataProcessingUtils.extractVersion(aggregateData);
    const { createdAt, updatedAt } =
      EventDataProcessingUtils.extractTimestamps(aggregateData);

    return {
      lookupType,
      code,
      name,
      description,
      enabled,
      attributes,
      version,
      createdAt,
      updatedAt,
    };
  }
}
