// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsNotEmpty, IsString, MaxLength } from 'class-validator';

/**
 * Options for property decorators
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for AttributeRuleSet Code
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiAttributeRuleSetCode(options: PropOptions = {}) {
  const { required = true } = options;

  return applyDecorators(
    ApiProperty({
      description: `Primary key and unique identifier for the lookup type. Defines the category or classification that groups related lookup entries together.`,
      example: `COUNTRY`,
      type: String,
      required,
    }),
    IsString(),
    MaxLength(64),
    required ? IsNotEmpty() : IsOptional(),
  );
}
