// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { LookupTypeSnapshotProps } from '../../domain/props';
import { DetailLookupTypeResponse } from '../dtos';

/**
 * LookupType Snapshot to DTO Mappers
 * Reusable mapping functions for converting domain snapshots to DTOs
 */

/**
 * Map lookupType snapshot to DTO response
 */
export const mapLookupTypeSnapshotToDto = (
  snapshot: LookupTypeSnapshotProps,
): DetailLookupTypeResponse => {
  return {
    lookupType: snapshot.lookupType,
    code: snapshot.code,
    name: snapshot.name,
    description: snapshot.description,
    enabled: snapshot.enabled,
    attributes: snapshot.attributes,
  };
};
