// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Result, DomainError } from 'src/shared/errors';
import { ActorContext } from 'src/shared/application/context';
import { RepositoryOptions } from 'src/shared/infrastructure/repositories';
import { Option } from 'src/shared/domain/types';
import { LookupTypeReference } from './references';

export const LOOKUP_TYPE_REFERENCE_READER_TOKEN = 'ILookupTypeReader' as const;

/**
 * LookupType Reader Port (Bounded Context: Core)
 *
 * Handles lookup-type reference data lookups for FK validation.
 * Clean ownership of lookup-type-related operations with swappable implementations.
 */
export interface ILookupTypeReader {
  /**
   * Find valid LookupType Codes for LookupType configuration
   * @param actor - The authenticated user context
   * @param options - Optional repository options
   * @returns Result containing available LookupType Codes
   */
  findValidLookupTypeCodes(
    actor: ActorContext,
    options?: RepositoryOptions,
  ): Promise<Result<string[], DomainError>>;

  /**
   * Find LookupType configuration by LookupType code
   * @param actor - The authenticated user context
   * @param  - The   to lookup
   * @param options - Optional repository options
   * @returns Result containing LookupType configuration or null if not found
   */
  findLookupTypeByCode(
    actor: ActorContext,
    code: string,
    options?: RepositoryOptions,
  ): Promise<Result<Option<LookupTypeReference>, DomainError>>;
}
