// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  TestSecurityCreatedAt,
  TestSecurityUpdatedAt,
  TestSecurityVersion,
  TestSecurityDescription,
  TestSecurityId,
  TestSecurityName,
} from '../value-objects';

/**
 * TestSecurity Domain State
 *
 * Domain state interface that uses value objects to model business concepts
 * while maintaining compatibility with entity operations. Business fields are
 * modeled as value objects with proper validation and domain rules.
 *
 * Domain-First State Interface
 *
 * This interface represents the domain model where business concepts
 * are properly encapsulated as value objects when appropriate.
 */

export interface TestSecurityDomainState {
  id: TestSecurityId;
  name: TestSecurityName;
  description?: TestSecurityDescription;
  version: TestSecurityVersion;
  createdAt: TestSecurityCreatedAt;
  updatedAt: TestSecurityUpdatedAt;
}

export type TestSecurityDomainStateOptional = Partial<TestSecurityDomainState>;
