// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { AuthtypeSnapshotProps } from '../../domain/props';
import { DetailAuthtypeResponse } from '../dtos';

/**
 * Authtype Snapshot to DTO Mappers
 * Reusable mapping functions for converting domain snapshots to DTOs
 */

/**
 * Map authtype snapshot to DTO response
 */
export const mapAuthtypeSnapshotToDto = (
  snapshot: AuthtypeSnapshotProps,
): DetailAuthtypeResponse => {
  return {
    id: snapshot.id,
    webhookId: snapshot.webhookId,
    type: snapshot.type,
    signingSecretRef: snapshot.signingSecretRef,
    signatureAlgorithm: snapshot.signatureAlgorithm,
    usernameRef: snapshot.usernameRef,
    passwordRef: snapshot.passwordRef,
    apiKeyRef: snapshot.apiKeyRef,
    apiKeyHeader: snapshot.apiKeyHeader,
    apiKeyQueryParam: snapshot.apiKeyQueryParam,
    tokenUrl: snapshot.tokenUrl,
    clientIdRef: snapshot.clientIdRef,
    clientSecretRef: snapshot.clientSecretRef,
    scope: snapshot.scope,
    certRef: snapshot.certRef,
    keyRef: snapshot.keyRef,
    caRef: snapshot.caRef,
  };
};
