// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  BooleanVOInstance,
  createBooleanVO,
  createBooleanVOErrors,
} from 'src/shared/domain/value-objects';
import { ChannelErrors } from '..//errors/channel.errors';

/**
 * Enabled Boolean Value Object
 * Represents a validated enabled with business rules
 */
export const ChannelEnabled = createBooleanVO({
  name: 'Enabled',
  treatNullAsFalse: false,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createBooleanVOErrors(ChannelErrors.INVALID_ENABLED, 'Enabled'),
});

/** Public instance type for Enabled */
export type ChannelEnabled = BooleanVOInstance;

// Convenience creators
export const createChannelEnabled = (v: boolean) => ChannelEnabled.create(v);
export const channelEnabledFrom = (v: unknown) => ChannelEnabled.from(v);
