// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Module } from '@nestjs/common';
import { RouterModule, Routes } from '@nestjs/core';
import { ConfigModule } from '../../config.module';
/**
 * Config Router Configuration
 *
 * Configures nested routing for config endpoints to follow
 * the module monolith structure: /notification/slack-request/api/v1/configs
 *
 * This replaces flat routing (/api/v1/configs) with contextual routing
 * that reflects the bounded context hierarchy.
 */

// Define the routing structure for the config bounded context
const configRoutes: Routes = [
  {
    path: 'notification',
    children: [
      {
        path: 'slack-request',
        children: [
          {
            path: 'configs',
            module: ConfigModule,
          },
        ],
      },
    ],
  },
];

/**
 * Config Router Module
 *
 * Provides nested routing configuration for config endpoints.
 * This module should be imported in the main app module to enable
 * the nested route structure.
 *
 * Routes configured:
 * - /notification/slack-request/api/v1/configs/:workspaceCode (GET)
 * - /notification/slack-request/health/projectors/config (GET)
 * - /notification/slack-request/health/projectors/config/metrics (GET)
 */
@Module({
  imports: [ConfigModule, RouterModule.register(configRoutes)],
  exports: [ConfigModule],
})
export class ConfigRouterModule {}
