// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { EventMetadata } from 'src/shared/domain/events';

/**
 * Webhook Deleted Event Payload
 * Contains identifying information about the deleted webhook
 */
export interface WebhookDeletedEventPayload {
  id: string;
  deletedAt: Date;
  version: number;
  metadata: EventMetadata;
}

/**
 * Webhook Deleted Domain Event
 *
 * Emitted when a webhook is successfully deleted.
 * Contains identifying information and deletion metadata.
 */
export class WebhookDeletedEvent {
  public readonly eventType = 'NotificationWebhookConfigWebhookDeleted.v1';
  public readonly eventVersion = 'v1';

  constructor(public readonly payload: WebhookDeletedEventPayload) {}

  // Factory method with security context
  static create(
    data: Omit<WebhookDeletedEventPayload, 'metadata'>,
    baseMetadata: EventMetadata,
  ): WebhookDeletedEvent {
    const metadata: EventMetadata = {
      ...baseMetadata,
      eventVersion: '1.0',
      source: 'notification.domain.webhook',
    };

    return new WebhookDeletedEvent({
      ...data,
      metadata,
    });
  }

  get id(): string {
    return this.payload.id;
  }

  get deletedAt(): Date {
    return this.payload.deletedAt;
  }

  get version(): number {
    return this.payload.version;
  }

  get metadata(): EventMetadata {
    return this.payload.metadata;
  }
}
