// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsNotEmpty, IsString, MaxLength } from 'class-validator';

/**
 * Options for property decorators
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Attributerule Code
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiAttributeruleCode(options: PropOptions = {}) {
  const { required = true } = options;

  return applyDecorators(
    ApiProperty({
      description: `An identifier for the attribute rule. It is typically represented as an integer, but the specific format may vary.`,
      type: String,
      required,
    }),
    IsString(),
    MaxLength(64),
    required ? IsNotEmpty() : IsOptional(),
  );
}
