// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsNotEmpty, IsString, MaxLength } from 'class-validator';

/**
 * Options for property decorators
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Attributerule Name
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiAttributeruleName(options: PropOptions = {}) {
  const { required = true } = options;

  return applyDecorators(
    ApiProperty({
      description: `A string representing the name or label of the attribute rule.`,
      type: String,
      required,
    }),
    IsString(),
    MaxLength(60),
    required ? IsNotEmpty() : IsOptional(),
  );
}
