// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsNotEmpty, IsString, MaxLength } from 'class-validator';

/**
 * Options for property decorators
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Attributerule Regex
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiAttributeruleRegex(options: PropOptions = {}) {
  const { required = false } = options;

  return applyDecorators(
    ApiProperty({
      description: `This is a regular expression pattern field. If set, the system will validate the value against the specified regular expression pattern and return an error if there is no match.`,
      type: String,
      required,
    }),
    IsString(),
    MaxLength(120),
    required ? IsNotEmpty() : IsOptional(),
  );
}
