// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsNotEmpty, IsString, MaxLength } from 'class-validator';

/**
 * Options for property decorators
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Attributerule RegexError
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiAttributeruleRegexError(options: PropOptions = {}) {
  const { required = false } = options;

  return applyDecorators(
    ApiProperty({
      description: `Custom error message displayed when regex pattern validation fails. Should explain the expected format and provide examples.`,
      example: `Please enter a valid email address (e.g., user@domain.com)`,
      type: String,
      required,
    }),
    IsString(),
    MaxLength(255),
    required ? IsNotEmpty() : IsOptional(),
  );
}
