// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Injectable, Inject } from '@nestjs/common';
import { APP_LOGGER, Log, componentLogger, Logger } from 'src/shared/logging';
import { CorrelationUtil } from 'src/shared/utilities/correlation.util';
import { Clock, CLOCK } from 'src/shared/infrastructure/time';
import {
  RepositoryLoggingUtil,
  RepositoryLoggingConfig,
  handleRepositoryError,
  RepositoryOptions,
} from 'src/shared/infrastructure/repositories';
import { Result, DomainError, ok } from 'src/shared/errors';
import { ActorContext } from 'src/shared/application/context';
import { Option } from 'src/shared/domain/types';
import { CacheMetricsCollector } from 'src/shared/infrastructure/projections/cache-optimization';
import { DetailWorkspaceResponse } from '../../application/dtos';
import { workspaceStore, WorkspaceProjection } from '../stores/workspace.store';
import { IWorkspaceQuery } from '../../application/ports';

/**
 * Workspace Read Model - In-Memory Projection
 * Used internally by the query repository to work with read-optimized data
 * Uses DTOs consistently throughout (proper CQRS pattern - no domain props in read model)
 */
interface WorkspaceReadModel {
  id: string;
  name: string;
  botToken?: string;
  signingSecret?: string;
  appId?: string;
  botUserId?: string;
  defaultChannelId?: string;
  enabled: boolean;
  createdAt: Date;
  updatedAt: Date;
  version: number;
}

/**
 * Domain Props to DTO Conversion Utilities
 * Used when converting from the in-memory store (domain props) to the read model (DTOs)


/**
 * Workspace Query Repository - CQRS Read Model Implementation (In-Memory)
 *
 * Bounded Context: Notification/Workspace
 * Handles complex query operations including pagination, filtering, and search using in-memory projector
 * as the data source. Returns DTOs/ViewModels optimized for read operations, NOT domain props.
 *
 * CQRS Benefits:
 * - Returns read-optimized DTOs (DetailWorkspaceResponse, ListWorkspaceResponse)
 * - No dependency on domain props (proper read/write model separation)
 * - Zero external database dependencies
 * - Ultra-fast query operations (LRU cache)
 * - Perfect for testing, prototyping, and shadow validation
 * - Comprehensive logging and error handling
 *
 * ISP Benefits:
 * - Clients that need simple reads don't depend on complex query methods
 * - Can be optimized independently using in-memory indexing strategies
 * - Easier to implement caching strategies for query operations
 * - Supports analytical and reporting use cases with in-memory operations
 *
 * @domain Notification Context - Workspace Query Repository (Read Side)
 * @layer Infrastructure
 * @pattern CQRS + Repository Pattern + Interface Segregation Principle + In-Memory Projector
 */
@Injectable()
export class WorkspaceQueryRepository implements IWorkspaceQuery {
  private readonly logger: Logger;
  private readonly loggingConfig: RepositoryLoggingConfig;
  private readonly metricsCollector = new CacheMetricsCollector();

  constructor(
    @Inject(APP_LOGGER) baseLogger: Logger,
    @Inject(CLOCK) private readonly clock: Clock,
  ) {
    this.loggingConfig = {
      serviceName: 'WorkspaceConfigService',
      component: 'WorkspaceQueryRepository',
    };
    this.logger = componentLogger(baseLogger, this.loggingConfig.component);

    Log.info(
      this.logger,
      'WorkspaceQueryRepository initialized with in-memory backend',
      {
        component: this.loggingConfig.component,
        architecture: 'in-memory-shared-store',
        dataSource: 'in-memory-projector',
        cacheOptimized: true,
      },
    );
  }

  /**
   * Convert WorkspaceProjection to WorkspaceReadModel (reusable conversion logic)
   */
  private projectionToReadModel(
    projection: WorkspaceProjection,
  ): WorkspaceReadModel {
    return {
      id: projection.id,
      name: projection.name,
      botToken: projection.botToken,
      signingSecret: projection.signingSecret,
      appId: projection.appId,
      botUserId: projection.botUserId,
      defaultChannelId: projection.defaultChannelId,
      enabled: projection.enabled,
      createdAt: projection.createdAt || this.clock.now(),
      updatedAt: projection.updatedAt || this.clock.now(),
      version: projection.version || 1,
    };
  }

  /**
   * Get all workspaces for a tenant from the in-memory store
   * Filters out soft-deleted workspaces and converts to read model
   */
  private getWorkspacesForTenant(tenantId: string): WorkspaceReadModel[] {
    const allProjections = workspaceStore.getAll();
    const workspaces: WorkspaceReadModel[] = [];

    for (const [key, projection] of allProjections) {
      // Parse key to extract tenant and id
      const [projectionTenantId] = key.split(':');

      // Only include workspaces for the requested tenant
      if (projectionTenantId === tenantId && !projection.deletedAt) {
        // Convert projection to read model using shared conversion logic
        const readModel = this.projectionToReadModel(projection);
        workspaces.push(readModel);
      }
    }

    return workspaces;
  }

  /**
   * Transform WorkspaceReadModel to DetailWorkspaceResponse DTO
   */
  private toDetailResponse(
    workspace: WorkspaceReadModel,
  ): DetailWorkspaceResponse {
    return {
      id: workspace.id,
      name: workspace.name,
      botToken: workspace.botToken,
      signingSecret: workspace.signingSecret,
      appId: workspace.appId,
      botUserId: workspace.botUserId,
      defaultChannelId: workspace.defaultChannelId,
      enabled: workspace.enabled,
    } as DetailWorkspaceResponse;
  }
  /**
   * Helper to create consistent logging context using shared utilities
   */
  private createLogContext(
    operation: string,
    correlationId: string,
    actor: ActorContext,
    additionalContext?: Record<string, unknown>,
  ): Record<string, unknown> {
    return RepositoryLoggingUtil.createLogContext(
      this.loggingConfig,
      this.clock,
      operation,
      correlationId,
      actor,
      additionalContext,
    );
  }

  /**
   * Find a single Workspace by its unique identifier (for CQRS query operations)
   * @param actor - The actor context containing authentication and request metadata
   * @param id - The unique identifier of the Workspace
   * @param options - Optional repository options
   * @returns A promise resolving to a Result containing the Workspace or null if not found
   */
  findById(
    actor: ActorContext,
    id: string,
    options?: RepositoryOptions,
  ): Promise<Result<Option<DetailWorkspaceResponse>, DomainError>> {
    const operation = 'findById';
    const correlationId =
      options?.correlationId ??
      CorrelationUtil.generateForOperation('workspace-query-findById');

    const logContext = this.createLogContext(operation, correlationId, actor, {
      workspaceId: id,
    });

    try {
      Log.debug(this.logger, 'Finding workspace by ID', {
        ...logContext,
        queryDetails: {
          scope: 'shared_workspace_store',
          method: 'workspaceStore.get',
          tenantId: actor.tenantId,
        },
      });

      // Find the workspace in the store
      const projection = workspaceStore.get(
        actor.tenantId || 'default-tenant',
        id,
      );

      if (!projection) {
        Log.debug(this.logger, 'Workspace not found', logContext);
        return Promise.resolve(ok(Option.none()));
      }

      // Convert projection to read model, then transform to DetailWorkspaceResponse DTO
      const readModel = this.projectionToReadModel(projection);
      const detailResponse = this.toDetailResponse(readModel);

      Log.debug(this.logger, 'Workspace found successfully', {
        ...logContext,
        resultData: {
          workspaceId: detailResponse.id,
          workspaceName: detailResponse.name,
        },
      });

      return Promise.resolve(ok(Option.some(detailResponse)));
    } catch (error) {
      RepositoryLoggingUtil.logOperationError(
        this.logger,
        operation,
        logContext,
        error as Error,
        'MEDIUM',
      );
      return Promise.resolve(handleRepositoryError(error));
    }
  }
}
