// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Module } from '@nestjs/common';
import { RouterModule, Routes } from '@nestjs/core';
import { LookupTypeModule } from '../../lookup-type.module';
import { LookupTypeProjectorModule } from '../../lookup-type-projector.module';
/**
 * Lookup type Router Configuration
 *
 * Configures nested routing for lookup-type endpoints to follow
 * the module monolith structure: /core/lookup/api/v1/lookup-types
 *
 * This replaces flat routing (/api/v1/lookup-types) with contextual routing
 * that reflects the bounded context hierarchy.
 */

// Define the routing structure for the lookup-type bounded context
const lookupTypeRoutes: Routes = [
  {
    path: 'core',
    children: [
      {
        path: 'lookup',
        children: [
          {
            path: 'lookup-types',
            module: LookupTypeModule,
          },
          {
            path: 'health',
            module: LookupTypeProjectorModule,
          },
        ],
      },
    ],
  },
];

/**
 * Lookup type Router Module
 *
 * Provides nested routing configuration for lookup-type endpoints.
 * This module should be imported in the main app module to enable
 * the nested route structure.
 *
 * Routes configured:
 * - /core/lookup/api/v1/lookup-types/:code (GET, PUT, DELETE)
 * - /core/lookup/health/projectors/lookupType (GET)
 * - /core/lookup/health/projectors/lookup-type/metrics (GET)
 */
@Module({
  imports: [
    LookupTypeModule,
    LookupTypeProjectorModule,
    RouterModule.register(lookupTypeRoutes),
  ],
  exports: [LookupTypeModule, LookupTypeProjectorModule],
})
export class LookupTypeRouterModule {}
