// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

export interface UpdateAppConfigProps {
  tenant: string;
  workspaceCode?: string;
  maxRetryAttempts?: number;
  retryBackoffSeconds?: number;
  defaultLocale?: string;
  loggingEnabled?: boolean;
  auditChannelId?: string;
  metadata?: Record<string, unknown>;
}
