// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { CreateMessageRequestProps } from '../../domain/props';
import {
  ApiMessageRequestChannelCode,
  ApiMessageRequestData,
  ApiMessageRequestRecipient,
  ApiMessageRequestTemplateCode,
  ApiMessageRequestWorkspaceCode,
} from './decorators';

export class CreateMessageRequestRequest implements CreateMessageRequestProps {
  @ApiMessageRequestRecipient({ required: false })
  recipient?: string;

  @ApiMessageRequestData({ required: false })
  data?: Record<string, unknown>;

  @ApiMessageRequestWorkspaceCode()
  workspaceCode: string;

  @ApiMessageRequestTemplateCode()
  templateCode: string;

  @ApiMessageRequestChannelCode({ required: false })
  channelCode?: string;
}
