// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { EventDataProcessingUtils } from 'src/shared/infrastructure/events/utilities/event-data-processing.utils';

/**
 * Workspace Field Validator Utility
 *
 * Centralized utility for parsing and validating Workspace aggregate data from EventStore events.
 * Provides consistent field validation patterns that can be reused across repositories
 * and projectors for Workspace domain operations.
 *
 * @domain Notification Context - Workspace Field Validation Utility
 * @layer Infrastructure
 * @pattern Utility Pattern + Field Validation
 */
export class WorkspaceFieldValidatorUtil {
  /**
   * Create projector data with SecretRef objects for Redis storage
   *
   * This method extracts SecretRef objects from event data and serializes them
   * as JSON strings for storage in Redis. The reader repository will deserialize
   * and resolve these SecretRef objects back to actual secret values.
   *
   * @param aggregateData - Raw event data from EventStore containing SecretRef objects
   * @returns Projector data object with SecretRef fields as JSON strings
   */
  static createWorkspaceProjectorDataFromEventData(
    aggregateData: Record<string, any>,
  ): {
    code: string;
    name: string;
    botToken?: string;
    signingSecret?: string;
    appId?: string;
    botUserId?: string;
    defaultChannelId?: string;
    enabled: boolean;
    version: number;
    createdAt: Date;
    updatedAt: Date;
  } {
    const code = aggregateData.code as string;
    const name = aggregateData.name as string;
    const botToken = aggregateData.botToken as string;
    const signingSecret = aggregateData.signingSecret as string;
    const appId = aggregateData.appId as string;
    const botUserId = aggregateData.botUserId as string;
    const defaultChannelId = aggregateData.defaultChannelId as string;
    const enabled =
      aggregateData.enabled === 'true' || aggregateData.enabled === true;

    // Extract version and timestamps with proper type conversion
    const version = EventDataProcessingUtils.extractVersion(aggregateData);
    const { createdAt, updatedAt } =
      EventDataProcessingUtils.extractTimestamps(aggregateData);

    return {
      code,
      name,
      botToken,
      signingSecret,
      appId,
      botUserId,
      defaultChannelId,
      enabled,
      version,
      createdAt,
      updatedAt,
    };
  }
}
