// ===== INTERFACE TOKENS FOR DEPENDENCY INJECTION =====
export const CHECKPOINT_STORE = 'CHECKPOINT_STORE';
export const OUTBOX_REPOSITORY = 'OUTBOX_REPOSITORY';
export const EVENTSTORE_CLIENT = 'EVENTSTORE_CLIENT';
export const IO_REDIS = 'IORedis';
export const REDIS_CLUSTER = 'IORedisCluster';
export const CACHE_SERVICE = 'CACHE_SERVICE';
export const DATA_SOURCE = 'DATA_SOURCE';
export const CATCHUP_RUNNER = 'CATCHUP_RUNNER';
