// @generated by gen v1.0.0 hash:regen
// DO NOT EDIT THIS BLOCK BY HAND. Your changes will be overwritten.
import { DomainError } from 'src/shared/errors';

export interface ConfigContext extends Record<string, unknown> {
  maxRetryAttempts: number;
  retryBackoffSeconds: number;
  defaultLocale: string;
  strategy: string;
  metadata?: Record<string, unknown>;
  userId?: string;
  correlationId?: string;
  operation?: string;
  reason?: string;
}

export const ConfigErrors = {
  AUTHORIZATION_FAILED: {
    code: 'CONFIG.AUTHORIZATION_FAILED',
    title: 'Authorization Failed',
    detail: 'Policy evaluation failed for config operation',
    category: 'domain',
    retryable: false,
  } as DomainError<'CONFIG.AUTHORIZATION_FAILED', ConfigContext>,
  CANNOT_DELETE_CONFIG_WITH_DEPENDENCIES: {
    code: 'CONFIG.CANNOT_DELETE_CONFIG_WITH_DEPENDENCIES',
    title: 'Cannot Delete',
    detail: 'Cannot delete Config with existing dependencies',
    category: 'validation',
    retryable: false,
  } as DomainError<
    'CONFIG.CANNOT_DELETE_CONFIG_WITH_DEPENDENCIES',
    ConfigContext
  >,
  CONCURRENCY_CONFLICT: {
    code: 'CONFIG.CONCURRENCY_CONFLICT',
    title: 'Concurrency Conflict',
    detail: 'Concurrency conflict for Config',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.CONCURRENCY_CONFLICT', ConfigContext>,
  CONFIG_ALREADY_EXISTS: {
    code: 'CONFIG.CONFIG_ALREADY_EXISTS',
    title: 'Already Exists',
    detail: 'Config already exists',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.CONFIG_ALREADY_EXISTS', ConfigContext>,
  CONFIG_FACTORY_CREATION_FAILED: {
    code: 'CONFIG.CONFIG_FACTORY_CREATION_FAILED',
    title: 'Factory Creation Failed',
    detail: 'Failed to create Config using factory.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.CONFIG_FACTORY_CREATION_FAILED', ConfigContext>,
  CONFIG_INVARIANT_VIOLATION: {
    code: 'CONFIG.CONFIG_INVARIANT_VIOLATION',
    title: 'Invariant Violation',
    detail: 'Business invariant violation for Config',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.CONFIG_INVARIANT_VIOLATION', ConfigContext>,
  CONFIG_NOT_FOUND: {
    code: 'CONFIG.CONFIG_NOT_FOUND',
    title: 'Not Found',
    detail: 'Config not found',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.CONFIG_NOT_FOUND', ConfigContext>,
  CONFIG_UPDATE_FACTORY_FAILED: {
    code: 'CONFIG.CONFIG_UPDATE_FACTORY_FAILED',
    title: 'Update Factory Failed',
    detail: 'Failed to update Config using factory.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.CONFIG_UPDATE_FACTORY_FAILED', ConfigContext>,
  CONFIG_UPDATE_RECONSTITUTE_FAILED: {
    code: 'CONFIG.CONFIG_UPDATE_RECONSTITUTE_FAILED',
    title: 'Update Reconstitute Failed',
    detail: 'Failed to reconstitute Config from snapshot for update.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.CONFIG_UPDATE_RECONSTITUTE_FAILED', ConfigContext>,
  CREATED_AT_REQUIRED: {
    code: 'CONFIG.CREATED_AT_REQUIRED',
    title: 'Created At Required',
    detail: 'The config creation timestamp is required.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.CREATED_AT_REQUIRED', ConfigContext>,
  ENUM_NOT_ALLOWED_STRATEGY: {
    code: 'CONFIG.ENUM_NOT_ALLOWED_STRATEGY',
    title: 'Invalid Option',
    detail: 'Strategy must be one of: exponential, linear.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.ENUM_NOT_ALLOWED_STRATEGY', ConfigContext>,
  INVALID_CODE_DATA: {
    code: 'CONFIG.INVALID_CODE_DATA',
    title: 'Invalid Version Data',
    detail: 'The config version data is invalid.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_CODE_DATA', ConfigContext>,
  INVALID_CONFIG_DATA: {
    code: 'CONFIG.INVALID_CONFIG_DATA',
    title: 'Invalid Data',
    detail: 'Invalid Config data provided',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_CONFIG_DATA', ConfigContext>,
  INVALID_DEFAULT_LOCALE: {
    code: 'CONFIG.INVALID_DEFAULT_LOCALE',
    title: 'Value Required',
    detail: 'Default locale is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_DEFAULT_LOCALE', ConfigContext>,
  INVALID_DEFAULT_LOCALE_DATA: {
    code: 'CONFIG.INVALID_DEFAULT_LOCALE_DATA',
    title: 'Value Required',
    detail: 'Default locale is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_DEFAULT_LOCALE_DATA', ConfigContext>,
  INVALID_MAX_RETRY_ATTEMPTS: {
    code: 'CONFIG.INVALID_MAX_RETRY_ATTEMPTS',
    title: 'Value Required',
    detail: 'Max retry attempts is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_MAX_RETRY_ATTEMPTS', ConfigContext>,
  INVALID_MAX_RETRY_ATTEMPTS_DATA: {
    code: 'CONFIG.INVALID_MAX_RETRY_ATTEMPTS_DATA',
    title: 'Value Required',
    detail: 'Max retry attempts is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_MAX_RETRY_ATTEMPTS_DATA', ConfigContext>,
  INVALID_METADATA: {
    code: 'CONFIG.INVALID_METADATA',
    title: 'Value Required',
    detail: 'Metadata is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_METADATA', ConfigContext>,
  INVALID_METADATA_DATA: {
    code: 'CONFIG.INVALID_METADATA_DATA',
    title: 'Value Required',
    detail: 'Metadata is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_METADATA_DATA', ConfigContext>,
  INVALID_RETRY_BACKOFF_SECONDS: {
    code: 'CONFIG.INVALID_RETRY_BACKOFF_SECONDS',
    title: 'Value Required',
    detail: 'Retry backoff seconds is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_RETRY_BACKOFF_SECONDS', ConfigContext>,
  INVALID_RETRY_BACKOFF_SECONDS_DATA: {
    code: 'CONFIG.INVALID_RETRY_BACKOFF_SECONDS_DATA',
    title: 'Value Required',
    detail: 'Retry backoff seconds is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_RETRY_BACKOFF_SECONDS_DATA', ConfigContext>,
  INVALID_STRATEGY: {
    code: 'CONFIG.INVALID_STRATEGY',
    title: 'Value Required',
    detail: 'Strategy is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_STRATEGY', ConfigContext>,
  INVALID_STRATEGY_DATA: {
    code: 'CONFIG.INVALID_STRATEGY_DATA',
    title: 'Value Required',
    detail: 'Strategy is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_STRATEGY_DATA', ConfigContext>,
  INVALID_STRATEGY_TRANSITION: {
    code: 'CONFIG.INVALID_STRATEGY_TRANSITION',
    title: 'Invalid State Transition',
    detail: 'Strategy cannot transition to the requested state.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_STRATEGY_TRANSITION', ConfigContext>,
  INVALID_WEBHOOK_ID: {
    code: 'CONFIG.INVALID_WEBHOOK_ID',
    title: 'Value Required',
    detail: 'Webhook id is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_WEBHOOK_ID', ConfigContext>,
  INVALID_WEBHOOK_ID_DATA: {
    code: 'CONFIG.INVALID_WEBHOOK_ID_DATA',
    title: 'Value Required',
    detail: 'Webhook id is required for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.INVALID_WEBHOOK_ID_DATA', ConfigContext>,
  NOT_IMPLEMENTED: {
    code: 'CONFIG.NOT_IMPLEMENTED',
    title: 'Not Implemented',
    detail: 'Method not implemented for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.NOT_IMPLEMENTED', ConfigContext>,
  NOT_INTEGER_MAX_RETRY_ATTEMPTS: {
    code: 'CONFIG.NOT_INTEGER_MAX_RETRY_ATTEMPTS',
    title: 'Not an Integer',
    detail: 'Max retry attempts must be a whole number.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.NOT_INTEGER_MAX_RETRY_ATTEMPTS', ConfigContext>,
  NOT_INTEGER_RETRY_BACKOFF_SECONDS: {
    code: 'CONFIG.NOT_INTEGER_RETRY_BACKOFF_SECONDS',
    title: 'Not an Integer',
    detail: 'Retry backoff seconds must be a whole number.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.NOT_INTEGER_RETRY_BACKOFF_SECONDS', ConfigContext>,
  OUT_OF_RANGE_MAX_RETRY_ATTEMPTS: {
    code: 'CONFIG.OUT_OF_RANGE_MAX_RETRY_ATTEMPTS',
    title: 'Value Out of Range',
    detail: 'Max retry attempts is outside the allowed range for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.OUT_OF_RANGE_MAX_RETRY_ATTEMPTS', ConfigContext>,
  OUT_OF_RANGE_RETRY_BACKOFF_SECONDS: {
    code: 'CONFIG.OUT_OF_RANGE_RETRY_BACKOFF_SECONDS',
    title: 'Value Out of Range',
    detail: 'Retry backoff seconds is outside the allowed range for Config.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.OUT_OF_RANGE_RETRY_BACKOFF_SECONDS', ConfigContext>,
  PERMISSION_DENIED: {
    code: 'CONFIG.PERMISSION_DENIED',
    title: 'Permission Denied',
    detail: 'Insufficient permissions to access config',
    category: 'domain',
    retryable: false,
  } as DomainError<'CONFIG.PERMISSION_DENIED', ConfigContext>,
  PERMISSION_INVALID: {
    code: 'CONFIG.PERMISSION_INVALID',
    title: 'Invalid Permission',
    detail: 'The provided permission for config is not valid',
    category: 'domain',
    retryable: false,
  } as DomainError<'CONFIG.PERMISSION_INVALID', ConfigContext>,
  PERMISSION_NOT_FOUND: {
    code: 'CONFIG.PERMISSION_NOT_FOUND',
    title: 'Permission Not Found',
    detail: 'The requested permission for config does not exist',
    category: 'domain',
    retryable: false,
  } as DomainError<'CONFIG.PERMISSION_NOT_FOUND', ConfigContext>,
  UPDATED_AT_REQUIRED: {
    code: 'CONFIG.UPDATED_AT_REQUIRED',
    title: 'Updated At Required',
    detail: 'The config update timestamp is required.',
    category: 'validation',
    retryable: false,
  } as DomainError<'CONFIG.UPDATED_AT_REQUIRED', ConfigContext>,
} as const;
