// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Injectable, Inject } from '@nestjs/common';
import { Redis } from 'ioredis';
import { APP_LOGGER, Log, componentLogger, Logger } from 'src/shared/logging';
import { CorrelationUtil } from 'src/shared/utilities/correlation.util';
import { Clock, CLOCK } from 'src/shared/infrastructure/time';
import {
  RepositoryLoggingUtil,
  RepositoryLoggingConfig,
  handleRepositoryError,
  safeParseJSON,
  RepositoryOptions,
} from 'src/shared/infrastructure/repositories';
import { Result, DomainError, err, ok } from 'src/shared/errors';
import { Option } from 'src/shared/domain/types';
import { ActorContext } from 'src/shared/application/context';
import { RepositoryErrorFactory } from 'src/shared/domain/errors/repository.error';
import { CacheMetricsCollector } from 'src/shared/infrastructure/projections/cache-optimization';
import { SecretRefService } from 'src/shared/infrastructure/secret-ref/secret-ref.service';
import { SecretRef } from 'src/shared/infrastructure/secret-ref/secret-ref.types';
import { WEBHOOK_CONFIG_DI_TOKENS } from '../../../webhook-config.constants';
import { SecureTestProjectionKeys } from '../../secure-test-projection-keys';
import { DetailSecureTestResponse } from '../../application/dtos';
import { ISecureTestQuery } from '../../application/ports';

/**
 * Internal secureTest data structure for Redis operations
 * Extends DetailSecureTestResponse with additional fields needed for caching and versioning
 */
interface SecureTestCacheData extends DetailSecureTestResponse {
  version: number;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * SecureTest Query Repository - Interface Segregation Principle Implementation
 *
 * Bounded Context: Notification/SecureTest
 * Handles complex query operations including pagination, filtering, and search.
 * This repository focuses solely on advanced data retrieval operations using Redis projections.
 *
 * ISP Benefits:
 * - Clients that need simple reads don't depend on complex query methods
 * - Can be optimized independently using Redis indexing strategies
 * - Easier to implement caching strategies for query operations
 * - Supports analytical and reporting use cases with Redis sorted sets
 *
 * Redis Features Used:
 * - Hash-based secureTest storage with cluster-safe keys
 * - Sorted set indexing for efficient pagination and sorting
 * - Pattern matching for id and name filtering
 * - SCAN operations for tenant isolation
 * - Production-ready caching with metrics collection
 *
 * @domain Notification Context - SecureTest Query Repository (Redis)
 * @layer Infrastructure
 * @pattern Repository Pattern + Interface Segregation Principle + Redis Projector
 */
@Injectable()
export class SecureTestQueryRepository implements ISecureTestQuery {
  private readonly logger: Logger;
  private readonly loggingConfig: RepositoryLoggingConfig;
  private readonly metricsCollector = new CacheMetricsCollector();

  constructor(
    @Inject(APP_LOGGER) baseLogger: Logger,
    @Inject(CLOCK) private readonly clock: Clock,
    @Inject(WEBHOOK_CONFIG_DI_TOKENS.IO_REDIS)
    private readonly redis: Redis,
    private readonly secretRefService: SecretRefService,
  ) {
    this.loggingConfig = {
      serviceName: 'SecureTestConfigService',
      component: 'SecureTestQueryRepository',
    };
    this.logger = componentLogger(baseLogger, this.loggingConfig.component);

    Log.info(
      this.logger,
      'SecureTestQueryRepository initialized with Redis backend',
      {
        component: this.loggingConfig.component,
        redisStatus: this.redis.status,
        clusterSafe: true,
        cacheOptimized: true,
      },
    );
  }

  /**
   * Find a single secureTest by id using Redis hash lookup
   *
   * Leverages the established Redis patterns from SecureTestProjector
   * with cluster-safe keys and production-ready caching.
   *
   * Features:
   * - Cluster-safe Redis keys with hash tags for co-location
   * - Direct hash lookup for optimal performance (O(1))
   * - Tenant isolation using Redis key patterns
   * - Comprehensive logging and error handling
   * - Production-ready metrics collection
   * - Soft delete awareness
   *
   * @param actor - The actor context containing authentication and request metadata.
   * @param id - The secureTest id to search for.
   * @param options - Optional repository options (e.g., timeout, correlation).
   * @returns A promise resolving to a Result containing the SecureTest response or a DomainError.
   */
  async findById(
    actor: ActorContext,
    id: string,
    options?: RepositoryOptions,
  ): Promise<Result<Option<DetailSecureTestResponse>, DomainError>> {
    const operation = 'findById';
    const correlationId =
      options?.correlationId ??
      CorrelationUtil.generateForOperation('secure-test-query-findById');

    const logContext = this.createLogContext(operation, correlationId, actor, {
      secureTestId: id,
      dataSource: 'redis-projector',
    });

    // Validate actor context with enhanced security logging
    const validation = RepositoryLoggingUtil.validateActorContext(
      this.logger,
      actor,
      logContext,
    );
    if (!validation.ok) return err(validation.error);

    // Guard tenant explicitly
    if (!actor.tenant) {
      return err(
        RepositoryErrorFactory.validationError('tenant', 'Missing tenant id'),
      );
    }

    // Log successful authorization
    RepositoryLoggingUtil.logAuthorizationSuccess(
      this.logger,
      operation,
      logContext,
      {
        operationType: 'secure-test_query_findById',
        scope: 'redis_single_lookup',
        tenant: actor.tenant,
      },
    );

    try {
      // Generate cluster-safe Redis key
      const secureTestKey = this.generateSecureTestKey(actor.tenant, id);

      Log.debug(this.logger, 'Executing Redis hash lookup', {
        ...logContext,
        queryDetails: {
          scope: 'redis_hgetall',
          method: 'redis.hgetall',
          key: secureTestKey,
          clusterSafe: true,
        },
      });

      // Fetch secureTest hash from Redis
      const hashData = await this.redis.hgetall(secureTestKey);

      if (!hashData || Object.keys(hashData).length === 0) {
        Log.debug(this.logger, 'SecureTest not found in Redis', logContext);
        return ok(Option.none());
      }

      // Parse Redis hash to secureTest data
      const secureTest = await this.parseRedisHashToSecureTest(hashData, actor);

      if (!secureTest) {
        // SecureTest exists but is soft deleted or malformed
        Log.debug(
          this.logger,
          'SecureTest exists but is soft deleted or malformed',
          {
            ...logContext,
            softDeleted: !!hashData.deletedAt,
          },
        );
        return ok(Option.none());
      }

      // Transform to DetailSecureTestResponse DTO (excluding internal fields)
      const detailResponse: DetailSecureTestResponse = {
        id: secureTest.id,
        name: secureTest.name,
        description: secureTest.description,
        type: secureTest.type,
        signingSecret: secureTest.signingSecret,
        signatureAlgorithm: secureTest.signatureAlgorithm,
        username: secureTest.username,
        password: secureTest.password,
      };

      Log.debug(this.logger, 'SecureTest found successfully in Redis', {
        ...logContext,
        resultData: {
          secureTestId: detailResponse.id,
          secureTestName: detailResponse.name,
          cacheHit: true,
        },
      });

      return ok(Option.some(detailResponse));
    } catch (error) {
      // Log operation error using shared utility
      RepositoryLoggingUtil.logOperationError(
        this.logger,
        operation,
        logContext,
        error as Error,
        'MEDIUM',
      );

      // Handle and return the classified error using shared utility
      return handleRepositoryError(error);
    }
  }

  /**
   * Generate cluster-safe Redis keys using centralized SecureTestProjectionKeys
   * Ensures consistency with projector key patterns
   */
  private generateSecureTestKey(tenant: string, id: string): string {
    // ✅ Use centralized key generation for consistency
    return SecureTestProjectionKeys.getRedisSecureTestKey(tenant, id);
  }

  /**
   * Generate tenant index key for pagination and sorting using centralized keys
   */
  private generateTenantIndexKey(tenant: string): string {
    return SecureTestProjectionKeys.getRedisSecureTestIndexKey(tenant);
  }

  /**
   * Parse Redis hash data into DetailSecureTestResponse DTO
   * Uses DTO instead of domain props for CQRS compliance
   * Now handles SecretRef objects stored in Redis and resolves them to actual values
   */
  private async parseRedisHashToSecureTest(
    hashData: Record<string, string>,
    actor: ActorContext,
  ): Promise<SecureTestCacheData | null> {
    try {
      if (!hashData || Object.keys(hashData).length === 0) {
        return null;
      }

      // Check for soft deletion
      if (hashData.deletedAt) {
        return null;
      }

      // Type assertion for type - cached data should already be validated
      const type = hashData.type as DetailSecureTestResponse['type'];

      // Type assertion for signatureAlgorithm - cached data should already be validated
      const signatureAlgorithm =
        hashData.signatureAlgorithm as DetailSecureTestResponse['signatureAlgorithm'];

      // Parse and resolve SecretRef objects to actual values
      const signingSecret = await this.resolveSecretRefFromRedis(
        hashData.signingSecretRef,
        'signing secret',
        actor,
      );

      const username = await this.resolveSecretRefFromRedis(
        hashData.usernameRef,
        'username',
        actor,
      );

      const password = await this.resolveSecretRefFromRedis(
        hashData.passwordRef,
        'password',
        actor,
      );

      return {
        id: hashData.id,
        name: hashData.name,
        description: hashData.description || undefined,
        type,
        signingSecret,
        signatureAlgorithm,
        username,
        password,
        version: parseInt(hashData.version, 10),
        createdAt: new Date(hashData.createdAt),
        updatedAt: new Date(hashData.updatedAt),
      };
    } catch (error) {
      Log.error(
        this.logger,
        'Failed to parse Redis hash data to SecureTestSnapshot',
        {
          method: 'parseRedisHashToSecureTest',
          error: (error as Error).message,
          id: hashData?.id,
        },
      );
      return null;
    }
  }

  /**
   * Resolve a SecretRef from Redis hash data to actual secret value
   * @param secretRefJson - JSON string of SecretRef object stored in Redis
   * @param secretType - Type of secret for logging (e.g., 'signing secret', 'username')
   * @param actor - Actor context for secret resolution
   * @returns Resolved secret value or undefined if not found/invalid
   */
  private async resolveSecretRefFromRedis(
    secretRefJson: string | undefined,
    secretType: string,
    actor: ActorContext,
  ): Promise<string | undefined> {
    if (!secretRefJson) {
      return undefined;
    }

    try {
      // Parse SecretRef from JSON
      const secretRef = safeParseJSON<SecretRef>(secretRefJson, secretType);
      if (!secretRef || !secretRef.scheme || !secretRef.provider) {
        Log.warn(this.logger, `Invalid SecretRef format for ${secretType}`, {
          secretRefJson,
          secretType,
        });
        return undefined;
      }

      // Resolve SecretRef to actual value using SecretRefService
      const resolutionContext = {
        tenantId: actor.tenant,
        boundedContext: 'notification',
        purpose: 'db-conn' as const,
        environment:
          (process.env.NODE_ENV as
            | 'development'
            | 'test'
            | 'staging'
            | 'production') || 'development',
      };
      const resolvedSecret = await this.secretRefService.resolve(
        secretRef,
        undefined,
        resolutionContext,
      );

      Log.debug(
        this.logger,
        `Successfully resolved SecretRef for ${secretType}`,
        {
          secretType,
          secretKey: secretRef.key,
          providerLatency: resolvedSecret.providerLatencyMs,
        },
      );

      return resolvedSecret.value;
    } catch (error) {
      Log.error(this.logger, `Error resolving SecretRef for ${secretType}`, {
        secretType,
        error: (error as Error).message,
      });
      return undefined;
    }
  }

  /**
   * Helper to create consistent logging context using shared utilities
   */
  private createLogContext(
    operation: string,
    correlationId: string,
    actor: ActorContext,
    additionalContext?: Record<string, unknown>,
  ): Record<string, unknown> {
    return RepositoryLoggingUtil.createLogContext(
      this.loggingConfig,
      this.clock,
      operation,
      correlationId,
      actor,
      additionalContext,
    );
  }
}
