// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { AuthtypeErrors } from '../errors/authtype.errors';

/**
 * ClientSecretRef Value Object
 * Represents a validated clientSecretRef with business rules
 */
export const AuthtypeClientSecretRef = createStringVO({
  name: 'ClientSecretRef',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  maxLength: 255,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(
    AuthtypeErrors.INVALID_CLIENT_SECRET_REF,
    'ClientSecretRef',
  ),
});

/**
 * Public instance type for ClientSecretRef
 */
export type AuthtypeClientSecretRef = StringVOInstance;

// Convenience creators
export const createAuthtypeClientSecretRef = (s: string) =>
  AuthtypeClientSecretRef.create(s);
export const authtypeClientSecretRefFrom = (v: unknown) =>
  AuthtypeClientSecretRef.from(v);
