// @generated by gen v1.0.0 hash:regen
// DO NOT EDIT THIS BLOCK BY HAND. Your changes will be overwritten.
import { DomainError } from 'src/shared/errors';

export interface RuleContext extends Record<string, unknown> {
  code: string;
  name: string;
  description?: string;
  type: string;
  reference?: boolean;
  reserved?: boolean;
  unique?: boolean;
  uniqueError?: string;
  required?: boolean;
  requiredError?: string;
  regex?: string;
  regexError?: string;
  userId?: string;
  correlationId?: string;
  operation?: string;
  reason?: string;
}

export const RuleErrors = {
  ENUM_NOT_ALLOWED_TYPE: {
    code: 'RULE.ENUM_NOT_ALLOWED_TYPE',
    title: 'Invalid Option',
    detail:
      'Type must be one of: string, boolean, integer, currency, date, datetime, other.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.ENUM_NOT_ALLOWED_TYPE', RuleContext>,
  INVALID_CODE: {
    code: 'RULE.INVALID_CODE',
    title: 'Value Required',
    detail: 'Code is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_CODE', RuleContext>,
  INVALID_DESCRIPTION: {
    code: 'RULE.INVALID_DESCRIPTION',
    title: 'Value Required',
    detail: 'Description is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_DESCRIPTION', RuleContext>,
  INVALID_NAME: {
    code: 'RULE.INVALID_NAME',
    title: 'Value Required',
    detail: 'Name is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_NAME', RuleContext>,
  INVALID_REFERENCE: {
    code: 'RULE.INVALID_REFERENCE',
    title: 'Value Required',
    detail: 'Reference is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_REFERENCE', RuleContext>,
  INVALID_REGEX: {
    code: 'RULE.INVALID_REGEX',
    title: 'Value Required',
    detail: 'Regex is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_REGEX', RuleContext>,
  INVALID_REGEX_ERROR: {
    code: 'RULE.INVALID_REGEX_ERROR',
    title: 'Value Required',
    detail: 'Regex error is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_REGEX_ERROR', RuleContext>,
  INVALID_REQUIRED: {
    code: 'RULE.INVALID_REQUIRED',
    title: 'Value Required',
    detail: 'Required is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_REQUIRED', RuleContext>,
  INVALID_REQUIRED_ERROR: {
    code: 'RULE.INVALID_REQUIRED_ERROR',
    title: 'Value Required',
    detail: 'Required error is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_REQUIRED_ERROR', RuleContext>,
  INVALID_RESERVED: {
    code: 'RULE.INVALID_RESERVED',
    title: 'Value Required',
    detail: 'Reserved is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_RESERVED', RuleContext>,
  INVALID_RULE_CONFIGURATION_DATA: {
    code: 'RULE.INVALID_RULE_CONFIGURATION_DATA',
    title: 'Invalid Configuration Data',
    detail: 'The provided RULE_CONFIGURATION data is invalid.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_RULE_CONFIGURATION_DATA', RuleContext>,
  INVALID_TYPE: {
    code: 'RULE.INVALID_TYPE',
    title: 'Value Required',
    detail: 'Type is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_TYPE', RuleContext>,
  INVALID_TYPE_TRANSITION: {
    code: 'RULE.INVALID_TYPE_TRANSITION',
    title: 'Invalid State Transition',
    detail: 'Type cannot transition to the requested state.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_TYPE_TRANSITION', RuleContext>,
  INVALID_UNIQUE: {
    code: 'RULE.INVALID_UNIQUE',
    title: 'Value Required',
    detail: 'Unique is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_UNIQUE', RuleContext>,
  INVALID_UNIQUE_ERROR: {
    code: 'RULE.INVALID_UNIQUE_ERROR',
    title: 'Value Required',
    detail: 'Unique error is required for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.INVALID_UNIQUE_ERROR', RuleContext>,
  NOT_BOOLEAN_REFERENCE: {
    code: 'RULE.NOT_BOOLEAN_REFERENCE',
    title: 'Not a Boolean',
    detail: 'Reference must be true or false.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.NOT_BOOLEAN_REFERENCE', RuleContext>,
  NOT_BOOLEAN_REQUIRED: {
    code: 'RULE.NOT_BOOLEAN_REQUIRED',
    title: 'Not a Boolean',
    detail: 'Required must be true or false.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.NOT_BOOLEAN_REQUIRED', RuleContext>,
  NOT_BOOLEAN_RESERVED: {
    code: 'RULE.NOT_BOOLEAN_RESERVED',
    title: 'Not a Boolean',
    detail: 'Reserved must be true or false.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.NOT_BOOLEAN_RESERVED', RuleContext>,
  NOT_BOOLEAN_UNIQUE: {
    code: 'RULE.NOT_BOOLEAN_UNIQUE',
    title: 'Not a Boolean',
    detail: 'Unique must be true or false.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.NOT_BOOLEAN_UNIQUE', RuleContext>,
  NOT_IMPLEMENTED: {
    code: 'RULE.NOT_IMPLEMENTED',
    title: 'Not Implemented',
    detail: 'Method not implemented for Rule.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.NOT_IMPLEMENTED', RuleContext>,
  RULE_FACTORY_CREATION_FAILED: {
    code: 'RULE.RULE_FACTORY_CREATION_FAILED',
    title: 'Factory Creation Failed',
    detail: 'Failed to create Rule using factory.',
    category: 'validation',
    retryable: false,
  } as DomainError<'RULE.RULE_FACTORY_CREATION_FAILED', RuleContext>,
} as const;
