// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Result, DomainError } from 'src/shared/errors';
import { ActorContext } from 'src/shared/application/context';
import { SaveReceipt } from 'src/shared/infrastructure/repositories';
import { LookupTypeAggregate } from '../../domain/aggregates';
import { LookupTypeCode } from '../../domain/value-objects';

/**
 * Token for injecting ILookupTypeWriter port implementation
 */
export const LOOKUP_TYPE_WRITER_TOKEN = 'ILookupTypeWriter' as const;

/**
 * LookupType Writer Port - Interface Segregation Principle Implementation
 *
 * Handles write operations (create, update, delete) for LookupType aggregates.
 * This interface focuses solely on data modification operations.
 *
 * ISP Benefits:
 * - Clients that only need to write data don't depend on read methods
 * - Easier to implement write-only scenarios (e.g., event sourcing)
 * - Can be secured separately from read operations
 * - Supports command-only patterns in CQRS architectures
 *
 * @domain Core Context - LookupType Writer Port
 * @layer Application Ports
 * @pattern Interface Segregation Principle
 */
export interface ILookupTypeWriter {
  /**
   * Save a LookupType aggregate (create or update)
   * @param user - The authenticated user context
   * @param lookupType - The LookupType aggregate to save
   * @param expectedVersion - Optional version for optimistic locking
   * @returns Result indicating success or domain error
   */
  save(
    actor: ActorContext,
    lookupType: LookupTypeAggregate,
    expectedVersion?: number,
  ): Promise<Result<SaveReceipt, DomainError>>;

  /**
   * Delete a LookupType by its unique identifier
   * @param user - The authenticated user context
   * @param code - The unique identifier of the LookupType to delete
   * @returns Result indicating success or domain error
   */
  delete(
    actor: ActorContext,
    lookupType: string,
    code: LookupTypeCode,
  ): Promise<Result<SaveReceipt, DomainError>>;
}
