// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { WebhookSnapshotProps } from '../../domain/props';
import { DetailWebhookResponse } from '../dtos';

/**
 * Webhook Snapshot to DTO Mappers
 * Reusable mapping functions for converting domain snapshots to DTOs
 */

/**
 * Map webhook snapshot to DTO response
 */
export const mapWebhookSnapshotToDto = (
  snapshot: WebhookSnapshotProps,
): DetailWebhookResponse => {
  return {
    id: snapshot.id,
    name: snapshot.name,
    description: snapshot.description,
    targetUrl: snapshot.targetUrl,
    eventType: snapshot.eventType,
    method: snapshot.method,
    headers: snapshot.headers,
    signingSecret: snapshot.signingSecret,
    status: snapshot.status,
  };
};
