// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { AuthProps } from './auth.props';

export interface AuthSnapshotProps extends AuthProps {
  createdAt: Date;
  updatedAt: Date;
  version: number;
}
