// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Injectable, Inject } from '@nestjs/common';
import { Result, ok, err, DomainError, withContext } from 'src/shared/errors';
import { Log, Logger } from 'src/shared/logging';
import { ActorContext } from 'src/shared/application/context';
import { Option } from 'src/shared/domain/types';
import { RequestErrors } from '../../domain/errors';
import { SlackRequestServiceConstants } from '../../../service-constants';
import {
  CHANNEL_REFERENCE_READER_TOKEN,
  ChannelReference,
  IChannelReader,
  TEMPLATE_REFERENCE_READER_TOKEN,
  TemplateReference,
  ITemplateReader,
  WORKSPACE_REFERENCE_READER_TOKEN,
  WorkspaceReference,
  IWorkspaceReader,
} from '../ports';

export interface ForeignKeyValidationContext {
  correlationId?: string;
  userId?: string;
  operation: string;
  component: string;
}

/**
 * Request Foreign Key Validation Service
 *
 * Provides centralized validation for foreign key references used in Request domain.
 * This service validates that referenced entities exist before Request creation or updates.
 *
 * Benefits:
 * - Single responsibility for foreign key validation
 * - Reusable across create and update use cases
 * - Consistent error handling and logging
 * - Fail-fast validation to avoid expensive operations
 */
@Injectable()
export class RequestForeignKeyValidatorService {
  constructor(
    @Inject(WORKSPACE_REFERENCE_READER_TOKEN)
    private readonly workspaceReader: IWorkspaceReader,
    @Inject(TEMPLATE_REFERENCE_READER_TOKEN)
    private readonly templateReader: ITemplateReader,
    @Inject(CHANNEL_REFERENCE_READER_TOKEN)
    private readonly channelReader: IChannelReader,
  ) {}
  /**
   * Validates workspaceCode existence
   * @param actor - User context for authorization
   * @param workspaceCode - Workspace code to validate
   * @param context - Validation context for logging and error handling
   * @param logger - Logger instance for structured logging
   * @returns Result indicating validation success or failure
   */
  async validateWorkspaceCode(
    actor: ActorContext,
    workspaceCode: string | undefined,
    context: ForeignKeyValidationContext,
    logger: Logger,
  ): Promise<Result<WorkspaceReference | undefined, DomainError>> {
    if (!workspaceCode) {
      return ok(undefined);
    }
    Log.debug(logger, 'Validating workspaceCode foreign key', {
      application: SlackRequestServiceConstants.SERVICE_NAME,
      component: context.component,
      method: 'validateWorkspaceCode',
      correlationId: context.correlationId,
      userId: context.userId,
      workspaceCode,
      operation: context.operation,
    });

    const workspaceCodeResult = await this.workspaceReader.findWorkspaceByCode(
      actor,
      workspaceCode,
    );

    if (!workspaceCodeResult.ok) {
      Log.error(logger, 'Workspace lookup failed during validation', {
        application: SlackRequestServiceConstants.SERVICE_NAME,
        component: context.component,
        method: 'validateWorkspaceCode',
        correlationId: context.correlationId,
        userId: context.userId,
        workspaceCode,
        operation: context.operation,
        error: workspaceCodeResult.error,
      });
      return err(workspaceCodeResult.error);
    }

    const workspace = workspaceCodeResult.value;

    if (Option.isNone(workspace)) {
      Log.warn(logger, 'Workspace not found during validation', {
        application: SlackRequestServiceConstants.SERVICE_NAME,
        component: context.component,
        method: 'validateWorkspaceCode',
        correlationId: context.correlationId,
        userId: context.userId,
        workspaceCode,
        operation: context.operation,
      });
      return err(
        withContext(RequestErrors.INVALID_WORKSPACE_CODE, {
          correlationId: context.correlationId,
          userId: context.userId,
          operation: context.operation,
          workspaceCode,
          reason: 'Workspace code does not exist in the system',
        }),
      );
    }

    Log.debug(logger, 'Workspace existence validation passed', {
      application: SlackRequestServiceConstants.SERVICE_NAME,
      component: context.component,
      method: 'validateWorkspaceCode',
      correlationId: context.correlationId,
      userId: context.userId,
      workspaceCode,
      operation: context.operation,
    });

    return ok(workspace.value);
  }

  /**
   * Validates templateCode existence
   * @param actor - User context for authorization
   * @param templateCode - Template code to validate
   * @param context - Validation context for logging and error handling
   * @param logger - Logger instance for structured logging
   * @returns Result indicating validation success or failure
   */
  async validateTemplateCode(
    actor: ActorContext,
    templateCode: string | undefined,
    context: ForeignKeyValidationContext,
    logger: Logger,
  ): Promise<Result<TemplateReference | undefined, DomainError>> {
    if (!templateCode) {
      return ok(undefined);
    }
    Log.debug(logger, 'Validating templateCode foreign key', {
      application: SlackRequestServiceConstants.SERVICE_NAME,
      component: context.component,
      method: 'validateTemplateCode',
      correlationId: context.correlationId,
      userId: context.userId,
      templateCode,
      operation: context.operation,
    });

    const templateCodeResult = await this.templateReader.findTemplateByCode(
      actor,
      templateCode,
    );

    if (!templateCodeResult.ok) {
      Log.error(logger, 'Template lookup failed during validation', {
        application: SlackRequestServiceConstants.SERVICE_NAME,
        component: context.component,
        method: 'validateTemplateCode',
        correlationId: context.correlationId,
        userId: context.userId,
        templateCode,
        operation: context.operation,
        error: templateCodeResult.error,
      });
      return err(templateCodeResult.error);
    }

    const template = templateCodeResult.value;

    if (Option.isNone(template)) {
      Log.warn(logger, 'Template not found during validation', {
        application: SlackRequestServiceConstants.SERVICE_NAME,
        component: context.component,
        method: 'validateTemplateCode',
        correlationId: context.correlationId,
        userId: context.userId,
        templateCode,
        operation: context.operation,
      });
      return err(
        withContext(RequestErrors.INVALID_TEMPLATE_CODE, {
          correlationId: context.correlationId,
          userId: context.userId,
          operation: context.operation,
          templateCode,
          reason: 'Template code does not exist in the system',
        }),
      );
    }

    Log.debug(logger, 'Template existence validation passed', {
      application: SlackRequestServiceConstants.SERVICE_NAME,
      component: context.component,
      method: 'validateTemplateCode',
      correlationId: context.correlationId,
      userId: context.userId,
      templateCode,
      operation: context.operation,
    });

    return ok(template.value);
  }

  /**
   * Validates channelCode existence
   * @param actor - User context for authorization
   * @param channelCode - Channel code to validate
   * @param context - Validation context for logging and error handling
   * @param logger - Logger instance for structured logging
   * @returns Result indicating validation success or failure
   */
  async validateChannelCode(
    actor: ActorContext,
    channelCode: string | undefined,
    context: ForeignKeyValidationContext,
    logger: Logger,
  ): Promise<Result<ChannelReference | undefined, DomainError>> {
    if (!channelCode) {
      return ok(undefined);
    }
    Log.debug(logger, 'Validating channelCode foreign key', {
      application: SlackRequestServiceConstants.SERVICE_NAME,
      component: context.component,
      method: 'validateChannelCode',
      correlationId: context.correlationId,
      userId: context.userId,
      channelCode,
      operation: context.operation,
    });

    const channelCodeResult = await this.channelReader.findChannelByCode(
      actor,
      channelCode,
    );

    if (!channelCodeResult.ok) {
      Log.error(logger, 'Channel lookup failed during validation', {
        application: SlackRequestServiceConstants.SERVICE_NAME,
        component: context.component,
        method: 'validateChannelCode',
        correlationId: context.correlationId,
        userId: context.userId,
        channelCode,
        operation: context.operation,
        error: channelCodeResult.error,
      });
      return err(channelCodeResult.error);
    }

    const channel = channelCodeResult.value;

    if (Option.isNone(channel)) {
      Log.warn(logger, 'Channel not found during validation', {
        application: SlackRequestServiceConstants.SERVICE_NAME,
        component: context.component,
        method: 'validateChannelCode',
        correlationId: context.correlationId,
        userId: context.userId,
        channelCode,
        operation: context.operation,
      });
      return err(
        withContext(RequestErrors.INVALID_CHANNEL_CODE, {
          correlationId: context.correlationId,
          userId: context.userId,
          operation: context.operation,
          channelCode,
          reason: 'Channel code does not exist in the system',
        }),
      );
    }

    Log.debug(logger, 'Channel existence validation passed', {
      application: SlackRequestServiceConstants.SERVICE_NAME,
      component: context.component,
      method: 'validateChannelCode',
      correlationId: context.correlationId,
      userId: context.userId,
      channelCode,
      operation: context.operation,
    });

    return ok(channel.value);
  }

  /**
   * Validates all foreign keys for request props
   * @param actor - User context for authorization
   * @param props - Request properties containing foreign key fields
   * @param context - Validation context for logging and error handling
   * @param logger - Logger instance for structured logging
   * @returns Result indicating validation success or failure
   */
  async validateRequestForeignKeys(
    actor: ActorContext,
    props: {
      workspaceCode?: string;
      templateCode?: string;
      channelCode?: string;
    },
    context: ForeignKeyValidationContext,
    logger: Logger,
  ): Promise<
    Result<
      {
        workspaceCode?: WorkspaceReference;
        templateCode?: TemplateReference;
        channelCode?: ChannelReference;
      },
      DomainError
    >
  > {
    // Validate workspaceCode if provided
    const workspaceCodeValidation = await this.validateWorkspaceCode(
      actor,
      props.workspaceCode,
      context,
      logger,
    );
    if (!workspaceCodeValidation.ok) {
      return workspaceCodeValidation;
    }

    // Validate templateCode if provided
    const templateCodeValidation = await this.validateTemplateCode(
      actor,
      props.templateCode,
      context,
      logger,
    );
    if (!templateCodeValidation.ok) {
      return templateCodeValidation;
    }

    // Validate channelCode if provided
    const channelCodeValidation = await this.validateChannelCode(
      actor,
      props.channelCode,
      context,
      logger,
    );
    if (!channelCodeValidation.ok) {
      return channelCodeValidation;
    }

    return ok({
      workspaceCode: workspaceCodeValidation.value,
      templateCode: templateCodeValidation.value,
      channelCode: channelCodeValidation.value,
    });
  }

  /**
   * Generic alias for validateRequestForeignKeys to match shared runner interface
   * @param actor - Actor context for permissions and auditing
   * @param props - Props containing foreign key fields to validate
   * @param context - Validation context for logging and error handling
   * @param logger - Logger instance for structured logging
   * @returns Result indicating validation success or failure
   */
  async validateForeignKeys(
    actor: ActorContext,
    props: {
      workspaceCode?: string;
      templateCode?: string;
      channelCode?: string;
    },
    context: ForeignKeyValidationContext,
    logger: Logger,
  ): Promise<
    Result<
      {
        workspaceCode?: WorkspaceReference;
        templateCode?: TemplateReference;
        channelCode?: ChannelReference;
      },
      DomainError
    >
  > {
    return this.validateRequestForeignKeys(actor, props, context, logger);
  }
}
