// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Module } from '@nestjs/common';
import { WebhookConfigSharedModule } from '../webhook-config-shared.module';
import { AuthtypeController } from './interface/http/controllers';
import {
  AuthtypeApplicationService,
  AuthtypeAuthorizationService,
  AuthtypeAuthorizationAdapter,
  AuthtypeForeignKeyValidatorService,
} from './application/services';
import {
  IUpsertAuthtypeUseCase,
  UpsertAuthtypeUseCase,
  IDeleteAuthtypeUseCase,
  DeleteAuthtypeUseCase,
  IGetAuthtypeUseCase,
  GetAuthtypeUseCase,
} from './application/use-cases';

// import { IAuthtypeRepository } from './application/ports';
import {
  AuthtypeQueryRepository,
  AuthtypeReaderRepository,
  AuthtypeWriterRepository,
  WebhookReaderRepository,
} from './infrastructure/repositories';

// Tokens for injection - imported directly from port files
import {
  AUTHTYPE_READER_TOKEN,
  AUTHTYPE_WRITER_TOKEN,
  WEBHOOK_REFERENCE_READER_TOKEN,
  AUTHTYPE_QUERY_TOKEN,
} from './application/ports';
@Module({
  imports: [
    WebhookConfigSharedModule, // Provides all common infrastructure and services
  ],
  controllers: [AuthtypeController],
  providers: [
    // Repository implementations with tokens (before services that depend on them)
    {
      provide: AUTHTYPE_READER_TOKEN,
      useClass: AuthtypeReaderRepository,
    },
    {
      provide: AUTHTYPE_WRITER_TOKEN,
      useClass: AuthtypeWriterRepository,
    },
    {
      provide: AUTHTYPE_QUERY_TOKEN,
      useClass: AuthtypeQueryRepository,
    },

    // Bounded Context Reader Repositories
    {
      provide: WEBHOOK_REFERENCE_READER_TOKEN,
      useClass: WebhookReaderRepository,
    },

    // Services that depend on repositories
    AuthtypeApplicationService,
    AuthtypeAuthorizationService,
    AuthtypeAuthorizationAdapter,
    AuthtypeForeignKeyValidatorService,

    // Use case implementations
    {
      provide: IUpsertAuthtypeUseCase,
      useClass: UpsertAuthtypeUseCase,
    },
    {
      provide: IDeleteAuthtypeUseCase,
      useClass: DeleteAuthtypeUseCase,
    },
    {
      provide: IGetAuthtypeUseCase,
      useClass: GetAuthtypeUseCase,
    },
  ],
  exports: [
    // Repository tokens for external module consumption
    AUTHTYPE_READER_TOKEN,
    AUTHTYPE_WRITER_TOKEN,
    AUTHTYPE_QUERY_TOKEN,
    // Bounded Context Reader tokens
    WEBHOOK_REFERENCE_READER_TOKEN,
  ],
})
export class AuthtypeModule {}
