// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK
import {
  SecureTestSignatureAlgorithmValue,
  SecureTestTypeValue,
} from '../../application/dtos';

import {
  DopplerSecretRef,
  SealedSecretRef,
} from 'src/shared/infrastructure/secret-ref/domain/sealed-secret-ref.types';
import { SecretRefUtils } from 'src/shared/infrastructure/secret-ref/utilities/secret-ref.utils';
import { EventDataProcessingUtils } from 'src/shared/infrastructure/events/utilities/event-data-processing.utils';

/**
 * SecureTest Field Validator Utility
 *
 * Centralized utility for parsing and validating SecureTest aggregate data from EventStore events.
 * Provides consistent field validation patterns that can be reused across repositories
 * and projectors for SecureTest domain operations.
 *
 * @domain Notification Context - SecureTest Field Validation Utility
 * @layer Infrastructure
 * @pattern Utility Pattern + Field Validation
 */
export class SecureTestFieldValidatorUtil {
  /**
   * Create projector data with SecretRef objects for Redis storage
   *
   * This method extracts SecretRef objects from event data and serializes them
   * as JSON strings for storage in Redis. The reader repository will deserialize
   * and resolve these SecretRef objects back to actual secret values.
   *
   * @param aggregateData - Raw event data from EventStore containing SecretRef objects
   * @returns Projector data object with SecretRef fields as JSON strings
   */
  static createSecureTestProjectorDataFromEventData(
    aggregateData: Record<string, any>,
  ): {
    id: string;
    name: string;
    description?: string;
    type: SecureTestTypeValue;
    signingSecret?: string;
    signatureAlgorithm?: SecureTestSignatureAlgorithmValue;
    username?: string;
    password?: string;
    version: number;
    createdAt: Date;
    updatedAt: Date;
  } {
    // Extract simple fields directly from event data
    const id = aggregateData.id as string;
    const name = aggregateData.name as string;
    const description = aggregateData.description as string;
    const type = aggregateData.type as SecureTestTypeValue;
    const signatureAlgorithm =
      aggregateData.signatureAlgorithm as SecureTestSignatureAlgorithmValue;

    // Handle SecretRef objects from encrypted event data
    // The writer repository stores encrypted SecretRef objects in these fields
    const signingSecretRef = aggregateData.signingSecret
      ? JSON.stringify(aggregateData.signingSecret)
      : undefined;

    const usernameRef = aggregateData.username
      ? JSON.stringify(aggregateData.username)
      : undefined;

    const passwordRef = aggregateData.password
      ? JSON.stringify(aggregateData.password)
      : undefined;

    // Store plain text values directly for now (not encrypted)
    // This preserves the user-provided values per record
    // Extract credentials for validation (they're handled via SecretRef below)

    // Extract version and timestamps with proper type conversion
    const version = EventDataProcessingUtils.extractVersion(aggregateData);
    const { createdAt, updatedAt } =
      EventDataProcessingUtils.extractTimestamps(aggregateData);

    return {
      id,
      name,
      description,
      type,
      signingSecret: signingSecretRef,
      signatureAlgorithm,
      username: usernameRef,
      password: passwordRef,
      version,
      createdAt,
      updatedAt,
    };
  }

  /**
   * Create a Doppler SecretRef with enhanced validation
   */
  static createDopplerSecretRefForField(
    baseKey: string,
    tenant: string = 'core',
  ): DopplerSecretRef {
    return SecretRefUtils.createDopplerSecretRefForField(baseKey, tenant, {
      version: 'latest',
      algHint: 'doppler-v1',
    });
  }

  /**
   * Create a Sealed SecretRef for new webhook configurations
   */
  static createSealedSecretRefForField(
    tenant: string,
    context: string,
    algorithm: 'XCHACHA20-POLY1305' | 'AES-256-GCM' = 'XCHACHA20-POLY1305',
  ): SealedSecretRef {
    return SecretRefUtils.createSealedSecretRefForField(
      tenant,
      context,
      algorithm,
    );
  }
}
