// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { EventDataProcessingUtils } from 'src/shared/infrastructure/events/utilities/event-data-processing.utils';
import {
  SecureTestSignatureAlgorithmValue,
  SecureTestTypeValue,
} from '../../application/dtos';

/**
 * SecureTest Field Validator Utility
 *
 * Centralized utility for parsing and validating SecureTest aggregate data from EventStore events.
 * Provides consistent field validation patterns that can be reused across repositories
 * and projectors for SecureTest domain operations.
 *
 * @domain Notification Context - SecureTest Field Validation Utility
 * @layer Infrastructure
 * @pattern Utility Pattern + Field Validation
 */
export class SecureTestFieldValidatorUtil {
  /**
   * Create projector data with SecretRef objects for Redis storage
   *
   * This method extracts SecretRef objects from event data and serializes them
   * as JSON strings for storage in Redis. The reader repository will deserialize
   * and resolve these SecretRef objects back to actual secret values.
   *
   * @param aggregateData - Raw event data from EventStore containing SecretRef objects
   * @returns Projector data object with SecretRef fields as JSON strings
   */
  static createSecureTestProjectorDataFromEventData(
    aggregateData: Record<string, any>,
  ): {
    id: string;
    name: string;
    description?: string;
    type: SecureTestTypeValue;
    signingSecret?: string;
    signatureAlgorithm?: SecureTestSignatureAlgorithmValue;
    username?: string;
    password?: string;
    options?: string;
    version: number;
    createdAt: Date;
    updatedAt: Date;
  } {
    const id = aggregateData.id as string;
    const name = aggregateData.name as string;
    const description = aggregateData.description as string;
    const type = aggregateData.type as SecureTestTypeValue;
    const signingSecret = aggregateData.signingSecret
      ? JSON.stringify(aggregateData.signingSecret)
      : undefined;
    const signatureAlgorithm =
      aggregateData.signatureAlgorithm as SecureTestSignatureAlgorithmValue;
    const username = aggregateData.username
      ? JSON.stringify(aggregateData.username)
      : undefined;
    const password = aggregateData.password
      ? JSON.stringify(aggregateData.password)
      : undefined;
    const options = aggregateData.options
      ? JSON.stringify(aggregateData.options)
      : undefined;

    // Extract version and timestamps with proper type conversion
    const version = EventDataProcessingUtils.extractVersion(aggregateData);
    const { createdAt, updatedAt } =
      EventDataProcessingUtils.extractTimestamps(aggregateData);

    return {
      id,
      name,
      description,
      type,
      signingSecret,
      signatureAlgorithm,
      username,
      password,
      options,
      version,
      createdAt,
      updatedAt,
    };
  }
}
