// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

/**
 * LookupXxx State Infrastructure Mappers
 *
 * Bidirectional mapping between pure VO domain state and primitive persistence snapshot.
 * Handles conversion between rich domain objects and raw database data.
 */

import {
  LookupXxxCreatedAt,
  LookupXxxUpdatedAt,
  LookupXxxVersion,
  LookupXxxLookupType,
  LookupXxxCode,
  LookupXxxName,
  LookupXxxDescription,
  LookupXxxEnabled,
  LookupXxxAttributes,
} from '../../domain/value-objects';
import { Result, ok, err, DomainError } from 'src/shared/errors';
import { LookupXxxDomainState } from '../../domain/state/lookup-xxx.state';
import { LookupXxxSnapshotProps } from '../../domain/props';

/**
 * Infrastructure State Mapper
 *
 * Handles conversion between domain VOs and persistence primitives.
 * This is where primitive obsession is eliminated - converting between
 * rich domain objects and raw database data.
 */
export class LookupXxxStateMapper {
  /**
   * Convert primitive persistence snapshot to rich domain state
   *
   * @param snapshot - Raw database/persistence data
   * @returns Rich domain state with VOs or error
   */
  static toDomain(
    snapshot: LookupXxxSnapshotProps,
  ): Result<LookupXxxDomainState, DomainError> {
    const errors: Array<{ field: string; error: DomainError }> = [];

    // Helper function to validate and collect errors
    const validateField = <T>(
      fieldName: string,
      result: Result<T, DomainError>,
    ): T | null => {
      if (!result.ok) {
        errors.push({ field: fieldName, error: result.error });
        return null;
      }
      return result.value;
    };

    // Convert each primitive to its corresponding VO with error collection
    const lookupType = validateField(
      'lookupType',
      LookupXxxLookupType.from(snapshot.lookupType),
    );
    const code = validateField('code', LookupXxxCode.from(snapshot.code));
    const name = validateField('name', LookupXxxName.from(snapshot.name));
    const description = snapshot.description
      ? validateField(
          'description',
          LookupXxxDescription.from(snapshot.description),
        )
      : undefined;
    const enabled = snapshot.enabled
      ? validateField('enabled', LookupXxxEnabled.from(snapshot.enabled))
      : undefined;
    const attributes = snapshot.attributes
      ? validateField(
          'attributes',
          LookupXxxAttributes.from(snapshot.attributes),
        )
      : undefined;
    const version = validateField(
      'version',
      LookupXxxVersion.from(snapshot.version),
    );
    const createdAt = validateField(
      'createdAt',
      LookupXxxCreatedAt.from(snapshot.createdAt),
    );
    const updatedAt = validateField(
      'updatedAt',
      LookupXxxUpdatedAt.from(snapshot.updatedAt),
    );

    // If any validations failed, return aggregated error
    if (errors.length > 0) {
      return err({
        code: 'LOOKUP_XXX.MAPPER_VALIDATION_FAILED',
        title: 'Domain State Mapping Failed',
        detail: `Failed to create domain state from persistence snapshot. ${errors.length} validation error(s) occurred.`,
        category: 'infrastructure',
        retryable: false,
        context: {
          validationErrors: errors.map((e) => ({
            field: e.field,
            errorCode: e.error.code,
            errorMessage: e.error.detail,
          })),
          snapshotCode: snapshot.code,
        },
      });
    }

    // All validations passed, construct the rich domain state
    const domainState: LookupXxxDomainState = {
      lookupType: lookupType!,
      code: code!,
      name: name!,
      description: description || undefined,
      enabled: enabled || undefined,
      attributes: attributes || undefined,
      version: version!,
      createdAt: createdAt!,
      updatedAt: updatedAt!,
    };

    return ok(domainState);
  }

  /**
   * Convert rich domain state to primitive persistence snapshot
   *
   * @param domainState - Rich domain state with VOs
   * @returns Raw persistence data for database storage
   */
  static toSnapshot(domainState: LookupXxxDomainState): LookupXxxSnapshotProps {
    return {
      // Extract primitive values from VOs
      lookupType: domainState.lookupType.value,
      code: domainState.code.value,
      name: domainState.name.value,
      description: domainState.description?.value,
      enabled: domainState.enabled?.value,
      attributes: domainState.attributes?.value,
      version: domainState.version.value,
      createdAt: domainState.createdAt.value,
      updatedAt: domainState.updatedAt.value,
    };
  }
}
