// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsOptional, IsNotEmpty } from 'class-validator';

/**
 * Options for property decorators (boolean)
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Template Enabled
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiTemplateEnabled(options: PropOptions = {}) {
  const { required = true } = options;

  return applyDecorators(
    ApiProperty({
      description: `Template availability toggle. Disabled templates cannot be used for new notifications but existing scheduled notifications will continue to use them.`,
      example: true,
      type: Boolean,
      required,
    }),
    IsBoolean(),
    required ? IsNotEmpty() : IsOptional(),
  );
}
