// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { INestApplication } from '@nestjs/common';
import { SwaggerConfigUtil } from 'src/docs/swagger-config.util';
import { AuthtypeModule } from '../authtype.module';
/**
 * Authtype documentation endpoints interface
 */
export interface AuthtypeDocumentationUrls {
  authtype: string;
}

/**
 * Authtype Documentation
 * This module handles the Swagger documentation for authtypes
 *
 */
export class AuthtypeDocumentation {
  static setup(app: INestApplication, port: string | number): void {
    const config = new DocumentBuilder()
      .addBearerAuth(
        { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
        'bearer',
      )
      .setTitle('📱 Authtype Management API')
      .setDescription(
        `
## bounded context: notification
[← Back to documentation](/api/docs/notification)

### application: webhook-config
[← Back to documentation](/api/docs/notification/webhook-config)
`,
      )
      .setVersion('1.0.0')
      .addTag('Authtypes', `Configuration for authtype table`);

    // Add dynamic server configuration
    SwaggerConfigUtil.addServers(config, port);

    const document = SwaggerModule.createDocument(app, config.build(), {
      include: [AuthtypeModule],
      extraModels: [],
    });

    SwaggerModule.setup(
      'api/docs/notification/webhook-config/authtype',
      app,
      document,
    );
  }

  /**
   * Setup all authtype-related documentation endpoints
   * This method centralizes the setup of all authtype module documentation
   */
  static setupAll(
    app: INestApplication,
    port: string | number,
  ): AuthtypeDocumentationUrls {
    // Setup main authtype documentation
    AuthtypeDocumentation.setup(app, port);

    // Setup sub-module documentation

    // Return all endpoint URLs
    return {
      authtype: AuthtypeDocumentation.getEndpoint(port),
    };
  }

  static getEndpoint(port: string | number): string {
    return `${SwaggerConfigUtil.getServerUrl(port)}/api/docs/notification/webhook-config/authtype`;
  }
}
