// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  AuthCreatedAt,
  AuthUpdatedAt,
  AuthVersion,
  AuthApiKey,
  AuthApiKeyHeader,
  AuthApiKeyQueryParam,
  AuthCa,
  AuthCert,
  AuthClientId,
  AuthClientSecret,
  AuthKey,
  AuthPassword,
  AuthScope,
  AuthSignatureAlgorithm,
  AuthSigningSecret,
  AuthTokenUrl,
  AuthType,
  AuthUsername,
  AuthVerifyTls,
  AuthWebhookId,
} from '../value-objects';

/**
 * Auth Domain State
 *
 * Domain state interface that uses value objects to model business concepts
 * while maintaining compatibility with entity operations. Business fields are
 * modeled as value objects with proper validation and domain rules.
 *
 * Domain-First State Interface
 *
 * This interface represents the domain model where business concepts
 * are properly encapsulated as value objects when appropriate.
 */

export interface AuthDomainState {
  webhookId: AuthWebhookId;
  type: AuthType;
  verifyTls?: AuthVerifyTls;
  signingSecret?: AuthSigningSecret;
  signatureAlgorithm?: AuthSignatureAlgorithm;
  username?: AuthUsername;
  password?: AuthPassword;
  apiKey?: AuthApiKey;
  apiKeyHeader?: AuthApiKeyHeader;
  apiKeyQueryParam?: AuthApiKeyQueryParam;
  tokenUrl?: AuthTokenUrl;
  clientId?: AuthClientId;
  clientSecret?: AuthClientSecret;
  scope?: AuthScope;
  cert?: AuthCert;
  key?: AuthKey;
  ca?: AuthCa;
  version: AuthVersion;
  createdAt: AuthCreatedAt;
  updatedAt: AuthUpdatedAt;
}

export type AuthDomainStateOptional = Partial<AuthDomainState>;
