// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { AuthErrors } from '../errors/auth.errors';

/**
 * ApiKeyHeader Value Object
 * Represents a validated apiKeyHeader with business rules
 */
export const AuthApiKeyHeader = createStringVO({
  name: 'ApiKeyHeader',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  maxLength: 100,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(
    AuthErrors.INVALID_API_KEY_HEADER,
    'ApiKeyHeader',
  ),
});

/**
 * Public instance type for ApiKeyHeader
 */
export type AuthApiKeyHeader = StringVOInstance;

// Convenience creators
export const createAuthApiKeyHeader = (s: string) => AuthApiKeyHeader.create(s);
export const authApiKeyHeaderFrom = (v: unknown) => AuthApiKeyHeader.from(v);
