// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { AuthErrors } from '../errors/auth.errors';

/**
 * ClientId Value Object
 * Represents a validated clientId with business rules
 */
export const AuthClientId = createStringVO({
  name: 'ClientId',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  maxLength: 255,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(AuthErrors.INVALID_CLIENT_ID, 'ClientId'),
});

/**
 * Public instance type for ClientId
 */
export type AuthClientId = StringVOInstance;

// Convenience creators
export const createAuthClientId = (s: string) => AuthClientId.create(s);
export const authClientIdFrom = (v: unknown) => AuthClientId.from(v);
