// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { AuthErrors } from '../errors/auth.errors';

/**
 * Scope Value Object
 * Represents a validated scope with business rules
 */
export const AuthScope = createStringVO({
  name: 'Scope',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  maxLength: 500,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(AuthErrors.INVALID_SCOPE, 'Scope'),
});

/**
 * Public instance type for Scope
 */
export type AuthScope = StringVOInstance;

// Convenience creators
export const createAuthScope = (s: string) => AuthScope.create(s);
export const authScopeFrom = (v: unknown) => AuthScope.from(v);
