// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { AttributeRuleErrors } from '../../errors/attribute-rule.errors';

/**
 * RequiredError Value Object
 * Represents a validated requiredError with business rules
 */
export const AttributeRuleRequiredError = createStringVO({
  name: 'RequiredError',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  maxLength: 255,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(
    AttributeRuleErrors.INVALID_REQUIRED_ERROR,
    'RequiredError',
  ),
});

/**
 * Public instance type for RequiredError
 */
export type AttributeRuleRequiredError = StringVOInstance;

// Convenience creators
export const createAttributeRuleRequiredError = (s: string) =>
  AttributeRuleRequiredError.create(s);
export const attributeRuleRequiredErrorFrom = (v: unknown) =>
  AttributeRuleRequiredError.from(v);
