// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsNotEmpty, IsString, MaxLength } from 'class-validator';

/**
 * Options for property decorators
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for SecureTest Password
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiSecureTestPassword(options: PropOptions = {}) {
  const { required = false } = options;

  return applyDecorators(
    ApiProperty({
      description: `Secret reference for Basic Auth password. Used with 'basic' authentication type for HTTP Basic Authentication.`,
      type: String,
      required,
    }),
    IsString(),
    MaxLength(255),
    required ? IsNotEmpty() : IsOptional(),
  );
}
