// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { UpdateAttributeRuleSetProps } from '../../domain/props';
import {
  ApiAttributeRuleSetAttributesRequest,
  ApiAttributeRuleSetDescription,
  ApiAttributeRuleSetEnabled,
  ApiAttributeRuleSetName,
} from './decorators';
import type { UpdateAttributeRuleRequest } from './';

export class UpdateAttributeRuleSetRequest
  implements UpdateAttributeRuleSetProps
{
  @ApiAttributeRuleSetName({ required: false })
  name?: string;

  @ApiAttributeRuleSetDescription({ required: false })
  description?: string;

  @ApiAttributeRuleSetEnabled({ required: false })
  enabled?: boolean;

  @ApiAttributeRuleSetAttributesRequest({ required: false })
  attributes?: Record<string, UpdateAttributeRuleRequest>;
}
