// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsInt, IsOptional, IsNotEmpty } from 'class-validator';
/**
 * Options for property decorators
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Config DlqMaxAgeSeconds
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiConfigDlqMaxAgeSeconds(options: PropOptions = {}) {
  const { required = false } = options;

  return applyDecorators(
    ApiProperty({
      description: `Dead letter queue max age in seconds`,
      type: Number,
      required,
    }),
    IsInt(),
    required ? IsNotEmpty() : IsOptional(),
  );
}
