// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { QueryHandler, IQueryHandler } from '@nestjs/cqrs';
import { DetailAuthtypeResponse } from '../dtos';
import { GetAuthtypeUseCase } from '../use-cases';
import { GetAuthtypeQuery } from '../queries';
import { Result, DomainError } from 'src/shared/errors';

@QueryHandler(GetAuthtypeQuery)
export class GetAuthtypeHandler implements IQueryHandler<GetAuthtypeQuery> {
  constructor(private readonly getAuthtypeUseCase: GetAuthtypeUseCase) {}

  async execute(
    query: GetAuthtypeQuery,
  ): Promise<Result<DetailAuthtypeResponse | null, DomainError>> {
    return this.getAuthtypeUseCase.execute({
      user: query.user,
      id: query.id,
      correlationId: query.correlationId || 'query-handler',
    });
  }
}
