// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { SecureTestErrors } from '../errors/secure-test.errors';

/**
 * Id Value Object
 * Represents a validated id with business rules
 */
export const SecureTestId = createStringVO({
  name: 'Id',
  trim: true,
  caseTransform: 'none',
  allowEmpty: false,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(SecureTestErrors.INVALID_ID, 'Id'),
});

/**
 * Public instance type for Id
 */
export type SecureTestId = StringVOInstance;

// Convenience creators
export const createSecureTestId = (s: string) => SecureTestId.create(s);
export const secureTestIdFrom = (v: unknown) => SecureTestId.from(v);
