// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { SecureTestErrors } from '../errors/secure-test.errors';

/**
 * Username Value Object
 * Represents a validated username with business rules
 */
export const SecureTestUsername = createStringVO({
  name: 'Username',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  maxLength: 255,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(SecureTestErrors.INVALID_USERNAME, 'Username'),
});

/**
 * Public instance type for Username
 */
export type SecureTestUsername = StringVOInstance;

// Convenience creators
export const createSecureTestUsername = (s: string) =>
  SecureTestUsername.create(s);
export const secureTestUsernameFrom = (v: unknown) =>
  SecureTestUsername.from(v);
