// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

/**
 * LookupType Created Event Payload
 * Contains only business facts - no envelope metadata, timestamps, or versioning
 */
export interface LookupTypeCreatedEventPayload {
  lookupType: string;
  code: string;
  name: string;
  description?: string;
  enabled?: boolean;
  attributes?: Record<string, unknown>;
}

/**
 * LookupType Created Domain Event
 *
 * Emitted when a new lookupType is successfully created.
 * Contains complete lookupType information and creation metadata.
 * Enhanced with security metadata and PII protection capabilities.
 */
export class LookupTypeCreatedEvent {
  public readonly eventType = 'CoreLookupLookupTypeCreated.v1';
  public readonly eventVersion = 'v1';

  constructor(public readonly payload: LookupTypeCreatedEventPayload) {}

  // Factory method - no metadata needed, just business data
  static create(data: LookupTypeCreatedEventPayload): LookupTypeCreatedEvent {
    return new LookupTypeCreatedEvent(data);
  }

  get lookupType(): string {
    return this.payload.lookupType;
  }

  get code(): string {
    return this.payload.code;
  }

  get name(): string {
    return this.payload.name;
  }

  get description(): string | undefined {
    return this.payload.description;
  }

  get enabled(): boolean | undefined {
    return this.payload.enabled;
  }

  get attributes(): Record<string, unknown> | undefined {
    return this.payload.attributes;
  }
}
