// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import type { AttributeruleProps } from '../props';

/**
 * LookupType Updated Event Payload
 * Domain-shaped payload with no PII
 * Same shape as Created event for consistent replayability
 */
export interface LookupTypeUpdatedEventPayload {
  code: string;
  name: string;
  description?: string;
  enabled?: boolean;
  attributes: Record<string, Record<string, AttributeruleProps>>;
}

/**
 * LookupType Updated Domain Event
 *
 * Emitted when lookupType information is modified.
 * Contains complete domain state (same shape as Created event) for replayability.
 */
export class LookupTypeUpdatedEvent {
  public readonly eventType = 'CoreLookupLookupTypeUpdated.v1';
  public readonly eventVersion = 'v1';

  constructor(public readonly payload: LookupTypeUpdatedEventPayload) {}

  // Factory method - simple domain data, no metadata in payload
  static create(data: LookupTypeUpdatedEventPayload): LookupTypeUpdatedEvent {
    return new LookupTypeUpdatedEvent(data);
  }

  get code(): string {
    return this.payload.code;
  }

  get name(): string {
    return this.payload.name;
  }

  get description(): string | undefined {
    return this.payload.description;
  }

  get enabled(): boolean | undefined {
    return this.payload.enabled;
  }

  get attributes(): Record<string, Record<string, AttributeruleProps>> {
    return this.payload.attributes;
  }
}
