// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

/**
 * Simple Generic Store
 *
 * Direct, no-nonsense storage for any projections.
 * Used by both projectors (write) and repositories (read).
 */

import { BaseProjection, SimpleStore } from 'src/shared/infrastructure/stores';
import { DetailChannelResponse } from '../../application/dtos';

/**
 * Channel projection data
 */
export interface ChannelProjection
  extends DetailChannelResponse,
    BaseProjection {
  lastStreamRevision: string;
}

/**
 * Channel-specific store instance - shared across projectors and repositories
 */
export const channelStore = new SimpleStore<ChannelProjection>(5000, 'channel');
