// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { DomainError, Result, ok, err } from 'src/shared/errors';
import {
  createIntegerVO,
  createIntegerVOErrors,
  IntegerVOInstance,
  createDateTimeVO,
  createDateTimeVOErrors,
  DateTimeVOInstance,
} from 'src/shared/domain/value-objects';
import { Clock } from 'src/shared/domain/clock';
import { ExecuteErrors } from '../errors/execute.errors';

/**
 * Execute Instance Value Objects
 *
 * Instance VOs for Execute aggregate lifecycle management.
 * Includes creation timestamps, update timestamps, and version tracking.
 * Follows the Clock injection pattern for deterministic testing.
 */

// ===========================================
// Execute Created At Instance VO
// ===========================================

const ExecuteCreatedAtErrors = createDateTimeVOErrors(
  ExecuteErrors.CREATED_AT_REQUIRED,
  'Execute Created At',
);

export const ExecuteCreatedAt = createDateTimeVO({
  name: 'ExecuteCreatedAt',
  allowFuture: false, // Cannot create execute in the future
  allowPast: true, // Can create with past timestamps (data migration)
  customValidation: (date: Date): Result<void, DomainError> => {
    // Optional: Add domain-specific creation time validation
    // For example, cannot be more than 1 year in the past
    const oneYearAgo = new Date();
    oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);

    if (date < oneYearAgo) {
      return err({
        ...ExecuteErrors.CREATED_AT_REQUIRED,
        detail: 'Execute creation date cannot be more than 1 year in the past',
        context: { value: date, maxPastDate: oneYearAgo },
      } as DomainError);
    }

    return ok(undefined);
  },
  errors: ExecuteCreatedAtErrors,
});

export type ExecuteCreatedAt = DateTimeVOInstance;

// ===========================================
// Execute Updated At Instance VO
// ===========================================

const ExecuteUpdatedAtErrors = createDateTimeVOErrors(
  ExecuteErrors.UPDATED_AT_REQUIRED,
  'Execute Updated At',
);

export const ExecuteUpdatedAt = createDateTimeVO({
  name: 'ExecuteUpdatedAt',
  allowFuture: false, // Cannot update execute in the future
  allowPast: true, // Can update with past timestamps (data correction)
  errors: ExecuteUpdatedAtErrors,
});

export type ExecuteUpdatedAt = DateTimeVOInstance;

// ===========================================
// Execute Version Instance VO
// ===========================================

const ExecuteVersionErrors = createIntegerVOErrors(
  ExecuteErrors.INVALID_CODE_DATA, // Reusing existing error until specific version error is added
  'Execute Version',
);

export const ExecuteVersion = createIntegerVO({
  name: 'ExecuteVersion',
  min: 0, // Version starts at 0
  allowNegative: false,
  errors: ExecuteVersionErrors,
});

export type ExecuteVersion = IntegerVOInstance;

// ===========================================
// Clock-Based Helper Functions (Explicit Dependencies)
// ===========================================

/**
 * Create ExecuteCreatedAt from Clock (explicit dependency)
 * Deterministic and testable - pass a fake clock in tests
 */
export const createdAtNow = (
  clock: Clock,
): Result<ExecuteCreatedAt, DomainError> =>
  ExecuteCreatedAt.create(clock.now());

/**
 * Create ExecuteUpdatedAt from Clock (explicit dependency)
 * Deterministic and testable - pass a fake clock in tests
 */
export const updatedAtNow = (
  clock: Clock,
): Result<ExecuteUpdatedAt, DomainError> =>
  ExecuteUpdatedAt.create(clock.now());

/**
 * Bump version by 1 (domain business rule)
 */
export const bumpVersion = (
  currentVersion: ExecuteVersion,
): Result<ExecuteVersion, DomainError> =>
  ExecuteVersion.create(currentVersion.value + 1);

/**
 * Create initial version (starts at 1 for new aggregates)
 */
export const initialVersion = (): Result<ExecuteVersion, DomainError> =>
  ExecuteVersion.create(1);

// ===========================================
// Direct Creation Functions (Non-Clock Based)
// ===========================================

/**
 * Create ExecuteCreatedAt from Date
 */
export const createExecuteCreatedAt = (
  date: Date,
): Result<ExecuteCreatedAt, DomainError> => ExecuteCreatedAt.create(date);

/**
 * Create ExecuteUpdatedAt from Date
 */
export const createExecuteUpdatedAt = (
  date: Date,
): Result<ExecuteUpdatedAt, DomainError> => ExecuteUpdatedAt.create(date);

/**
 * Create ExecuteVersion from number
 */
export const createExecuteVersion = (
  version: number,
): Result<ExecuteVersion, DomainError> => ExecuteVersion.create(version);

// ===========================================
// Domain Invariants & Validation
// ===========================================

/**
 * Validate that updatedAt is not before createdAt (monotonic time)
 */
export const validateMonotonicTime = (
  createdAt: ExecuteCreatedAt,
  updatedAt: ExecuteUpdatedAt,
): Result<void, DomainError> => {
  if (updatedAt.value < createdAt.value) {
    return err({
      ...ExecuteErrors.UPDATED_AT_REQUIRED,
      detail: 'Updated at cannot be before created at',
      context: {
        createdAt: createdAt.value.toISOString(),
        updatedAt: updatedAt.value.toISOString(),
      },
    } as DomainError);
  }
  return ok(undefined);
};

// ===========================================
// Legacy Compatibility (DEPRECATED)
// ===========================================

/**
 * @deprecated Use createdAtNow(clock) instead for better testability
 * This function hides the Date dependency and makes testing harder
 */
export function createExecuteCreatedAtNow(): Result<
  ExecuteCreatedAt,
  DomainError
> {
  return ExecuteCreatedAt.create(new Date());
}

/**
 * @deprecated Use updatedAtNow(clock) instead for better testability
 * This function hides the Date dependency and makes testing harder
 */
export function createExecuteUpdatedAtNow(): Result<
  ExecuteUpdatedAt,
  DomainError
> {
  return ExecuteUpdatedAt.create(new Date());
}
