// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Result, DomainError } from 'src/shared/errors';
import { ActorContext } from 'src/shared/application/context';
import { SaveReceipt } from 'src/shared/infrastructure/repositories';
import { MessageRequestAggregate } from '../../domain/aggregates';
import { MessageRequestId } from '../../domain/value-objects';

/**
 * Token for injecting IMessageRequestWriter port implementation
 */
export const MESSAGE_REQUEST_WRITER_TOKEN = 'IMessageRequestWriter' as const;

/**
 * MessageRequest Writer Port - Interface Segregation Principle Implementation
 *
 * Handles write operations (create, update, delete) for MessageRequest aggregates.
 * This interface focuses solely on data modification operations.
 *
 * ISP Benefits:
 * - Clients that only need to write data don't depend on read methods
 * - Easier to implement write-only scenarios (e.g., event sourcing)
 * - Can be secured separately from read operations
 * - Supports command-only patterns in CQRS architectures
 *
 * @domain Notification Context - MessageRequest Writer Port
 * @layer Application Ports
 * @pattern Interface Segregation Principle
 */
export interface IMessageRequestWriter {
  /**
   * Save a MessageRequest aggregate (create or update)
   * @param user - The authenticated user context
   * @param messageRequest - The MessageRequest aggregate to save
   * @param expectedVersion - Optional version for optimistic locking
   * @returns Result indicating success or domain error
   */
  save(
    actor: ActorContext,
    messageRequest: MessageRequestAggregate,
    expectedVersion?: number,
  ): Promise<Result<SaveReceipt, DomainError>>;

  /**
   * Delete a MessageRequest by its unique identifier
   * @param user - The authenticated user context
   * @param id - The unique identifier of the MessageRequest to delete
   * @returns Result indicating success or domain error
   */
  delete(
    actor: ActorContext,
    id: MessageRequestId,
  ): Promise<Result<SaveReceipt, DomainError>>;
}
