// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  TemplateCreatedAt,
  TemplateUpdatedAt,
  TemplateVersion,
  TemplateCode,
  TemplateContentBlocks,
  TemplateDescription,
  TemplateEnabled,
  TemplateName,
  TemplateSamplePayload,
  TemplateVariables,
  TemplateWorkspaceId,
} from '../value-objects';

/**
 * Template Domain State
 *
 * Domain state interface that uses value objects to model business concepts
 * while maintaining compatibility with entity operations. Business fields are
 * modeled as value objects with proper validation and domain rules.
 *
 * Domain-First State Interface
 *
 * This interface represents the domain model where business concepts
 * are properly encapsulated as value objects when appropriate.
 */

export interface TemplateDomainState {
  code: TemplateCode;
  workspaceId: TemplateWorkspaceId;
  name: TemplateName;
  description?: TemplateDescription;
  contentBlocks: TemplateContentBlocks;
  variables?: TemplateVariables;
  samplePayload?: TemplateSamplePayload;
  enabled: TemplateEnabled;
  version: TemplateVersion;
  createdAt: TemplateCreatedAt;
  updatedAt: TemplateUpdatedAt;
}

export type TemplateDomainStateOptional = Partial<TemplateDomainState>;
