// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import type {
  ConfigOrderingValue,
  ConfigRetryStrategyValue,
  ConfigSignatureAlgorithmValue,
  ConfigStrategyValue,
} from '../value-objects';

export interface UpdateConfigProps {
  webhookId: string;
  strategy?: ConfigStrategyValue;
  maxRetryAttempts?: number;
  retryBackoffSeconds?: number;
  retryStrategy?: ConfigRetryStrategyValue;
  backoffJitterPct?: number;
  requestTimeoutMs?: number;
  connectTimeoutMs?: number;
  signatureAlgorithm?: ConfigSignatureAlgorithmValue;
  includeTimestampHeader?: boolean;
  maxConcurrent?: number;
  dlqEnabled?: boolean;
  dlqMaxAgeSeconds?: number;
  ordering?: ConfigOrderingValue;
  defaultLocale?: string;
  metadata?: Record<string, unknown>;
}
