// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { BaseCommand } from 'src/shared/application/commands/base.command';
import { IUserToken } from 'src/shared/security';
import { CorrelationUtil } from 'src/shared/utilities/correlation.util';
import { SecurityMetadata } from 'src/shared/domain/events/event-metadata';
import { FailedFullMessageProps } from '../../domain/props';

/**
 * Enhanced Failed Full message Command with security context and metadata
 */
export class FailedFullMessageCommand extends BaseCommand {
  constructor(
    user: IUserToken,
    public readonly props: FailedFullMessageProps,
    correlationId: string,
    securityContext: SecurityMetadata,
  ) {
    super(correlationId, user, securityContext);
  }

  /**
   * Factory method to create command with automatic security context
   */
  static create(
    user: IUserToken,
    props: FailedFullMessageProps,
    correlationId: string = CorrelationUtil.generate(),
    additionalSecurityContext?: Partial<SecurityMetadata>,
  ): FailedFullMessageCommand {
    const securityContext = BaseCommand.createSecurityMetadata(
      user,
      additionalSecurityContext,
    );

    return new FailedFullMessageCommand(
      user,
      props,
      correlationId,
      securityContext,
    );
  }
}
