// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

/**
 * Abstract Use Case Contracts for Request Operations
 *
 * These abstract classes are used instead of interfaces to work with NestJS DI.
 * TypeScript interfaces are erased at runtime and cannot be injected.
 */

import { Result, DomainError } from 'src/shared/errors';
import type { IUserToken } from 'src/shared/security';
import type {
  CreateRequestProps,
  FailedRequestProps,
  SentRequestProps,
} from '../../domain/props';
import type {
  DetailRequestResponse,
  RequestPageResponse,
  ListRequestFilterRequest,
} from '../dtos';

export abstract class ICreateRequestUseCase {
  abstract execute(params: {
    user: IUserToken;
    props: CreateRequestProps;
    correlationId: string;
    authorizationReason: string;
  }): Promise<Result<DetailRequestResponse, DomainError>>;
}

export abstract class ISentRequestUseCase {
  abstract execute(params: {
    user: IUserToken;
    props: SentRequestProps;
    correlationId: string;
    authorizationReason: string;
  }): Promise<Result<DetailRequestResponse, DomainError>>;
}

export abstract class IFailedRequestUseCase {
  abstract execute(params: {
    user: IUserToken;
    props: FailedRequestProps;
    correlationId: string;
    authorizationReason: string;
  }): Promise<Result<DetailRequestResponse, DomainError>>;
}

export abstract class IGetRequestUseCase {
  abstract execute(params: {
    user: IUserToken;
    code: string;
    correlationId: string;
  }): Promise<Result<DetailRequestResponse, DomainError>>;
}
export abstract class IListRequestUseCase {
  abstract execute(params: {
    user: IUserToken;
    filter?: ListRequestFilterRequest;
    correlationId: string;
  }): Promise<Result<RequestPageResponse, DomainError>>;
}
