// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { WebhookErrors } from '../errors/webhook.errors';

/**
 * Description Value Object
 * Represents a validated description with business rules
 */
export const WebhookDescription = createStringVO({
  name: 'Description',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(
    WebhookErrors.INVALID_DESCRIPTION,
    'Description',
  ),
});

/**
 * Public instance type for Description
 */
export type WebhookDescription = StringVOInstance;

// Convenience creators
export const createWebhookDescription = (s: string) =>
  WebhookDescription.create(s);
export const webhookDescriptionFrom = (v: unknown) =>
  WebhookDescription.from(v);
