// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  RecordVOInstance,
  createRecordVO,
  createRecordVOErrors,
} from 'src/shared/domain/value-objects';
import { WebhookErrors } from '../errors/webhook.errors';

/**
 * Headers Record Value Object
 * Validates a plain object (Record<string, unknown>); deepFreeze.
 */
export const WebhookHeaders = createRecordVO({
  name: 'Headers',
  // JSON key validation - must start with letter/underscore, contain only alphanumeric, underscore
  keyPattern: /^[a-zA-Z_][a-zA-Z0-9_]*$/,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createRecordVOErrors(WebhookErrors.INVALID_HEADERS, 'Headers'),
});

/** Public instance type for Headers */
export type WebhookHeaders = RecordVOInstance;

// Convenience creators
export const createWebhookHeaders = (v: Record<string, unknown>) =>
  WebhookHeaders.create(v);

export const webhookHeadersFrom = (v: unknown) => WebhookHeaders.from(v);
