// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { DomainError, Result, ok, err } from 'src/shared/errors';
import {
  createIntegerVO,
  createIntegerVOErrors,
  IntegerVOInstance,
  createDateTimeVO,
  createDateTimeVOErrors,
  DateTimeVOInstance,
} from 'src/shared/domain/value-objects';
import { Clock } from 'src/shared/domain/clock';
import { WebhookErrors } from '../errors/webhook.errors';

/**
 * Webhook Instance Value Objects
 *
 * Instance VOs for Webhook aggregate lifecycle management.
 * Includes creation timestamps, update timestamps, and version tracking.
 * Follows the Clock injection pattern for deterministic testing.
 */

// ===========================================
// Webhook Created At Instance VO
// ===========================================

const WebhookCreatedAtErrors = createDateTimeVOErrors(
  WebhookErrors.CREATED_AT_REQUIRED,
  'Webhook Created At',
);

export const WebhookCreatedAt = createDateTimeVO({
  name: 'WebhookCreatedAt',
  allowFuture: false, // Cannot create webhook in the future
  allowPast: true, // Can create with past timestamps (data migration)
  customValidation: (date: Date): Result<void, DomainError> => {
    // Optional: Add domain-specific creation time validation
    // For example, cannot be more than 1 year in the past
    const oneYearAgo = new Date();
    oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);

    if (date < oneYearAgo) {
      return err({
        ...WebhookErrors.CREATED_AT_REQUIRED,
        detail: 'Webhook creation date cannot be more than 1 year in the past',
        context: { value: date, maxPastDate: oneYearAgo },
      } as DomainError);
    }

    return ok(undefined);
  },
  errors: WebhookCreatedAtErrors,
});

export type WebhookCreatedAt = DateTimeVOInstance;

// ===========================================
// Webhook Updated At Instance VO
// ===========================================

const WebhookUpdatedAtErrors = createDateTimeVOErrors(
  WebhookErrors.UPDATED_AT_REQUIRED,
  'Webhook Updated At',
);

export const WebhookUpdatedAt = createDateTimeVO({
  name: 'WebhookUpdatedAt',
  allowFuture: false, // Cannot update webhook in the future
  allowPast: true, // Can update with past timestamps (data correction)
  errors: WebhookUpdatedAtErrors,
});

export type WebhookUpdatedAt = DateTimeVOInstance;

// ===========================================
// Webhook Version Instance VO
// ===========================================

const WebhookVersionErrors = createIntegerVOErrors(
  WebhookErrors.INVALID_CODE_DATA, // Reusing existing error until specific version error is added
  'Webhook Version',
);

export const WebhookVersion = createIntegerVO({
  name: 'WebhookVersion',
  min: 0, // Version starts at 0
  allowNegative: false,
  errors: WebhookVersionErrors,
});

export type WebhookVersion = IntegerVOInstance;

// ===========================================
// Clock-Based Helper Functions (Explicit Dependencies)
// ===========================================

/**
 * Create WebhookCreatedAt from Clock (explicit dependency)
 * Deterministic and testable - pass a fake clock in tests
 */
export const createdAtNow = (
  clock: Clock,
): Result<WebhookCreatedAt, DomainError> =>
  WebhookCreatedAt.create(clock.now());

/**
 * Create WebhookUpdatedAt from Clock (explicit dependency)
 * Deterministic and testable - pass a fake clock in tests
 */
export const updatedAtNow = (
  clock: Clock,
): Result<WebhookUpdatedAt, DomainError> =>
  WebhookUpdatedAt.create(clock.now());

/**
 * Bump version by 1 (domain business rule)
 */
export const bumpVersion = (
  currentVersion: WebhookVersion,
): Result<WebhookVersion, DomainError> =>
  WebhookVersion.create(currentVersion.value + 1);

/**
 * Create initial version (starts at 1 for new aggregates)
 */
export const initialVersion = (): Result<WebhookVersion, DomainError> =>
  WebhookVersion.create(1);

// ===========================================
// Direct Creation Functions (Non-Clock Based)
// ===========================================

/**
 * Create WebhookCreatedAt from Date
 */
export const createWebhookCreatedAt = (
  date: Date,
): Result<WebhookCreatedAt, DomainError> => WebhookCreatedAt.create(date);

/**
 * Create WebhookUpdatedAt from Date
 */
export const createWebhookUpdatedAt = (
  date: Date,
): Result<WebhookUpdatedAt, DomainError> => WebhookUpdatedAt.create(date);

/**
 * Create WebhookVersion from number
 */
export const createWebhookVersion = (
  version: number,
): Result<WebhookVersion, DomainError> => WebhookVersion.create(version);

// ===========================================
// Domain Invariants & Validation
// ===========================================

/**
 * Validate that updatedAt is not before createdAt (monotonic time)
 */
export const validateMonotonicTime = (
  createdAt: WebhookCreatedAt,
  updatedAt: WebhookUpdatedAt,
): Result<void, DomainError> => {
  if (updatedAt.value < createdAt.value) {
    return err({
      ...WebhookErrors.UPDATED_AT_REQUIRED,
      detail: 'Updated at cannot be before created at',
      context: {
        createdAt: createdAt.value.toISOString(),
        updatedAt: updatedAt.value.toISOString(),
      },
    } as DomainError);
  }
  return ok(undefined);
};

// ===========================================
// Legacy Compatibility (DEPRECATED)
// ===========================================

/**
 * @deprecated Use createdAtNow(clock) instead for better testability
 * This function hides the Date dependency and makes testing harder
 */
export function createWebhookCreatedAtNow(): Result<
  WebhookCreatedAt,
  DomainError
> {
  return WebhookCreatedAt.create(new Date());
}

/**
 * @deprecated Use updatedAtNow(clock) instead for better testability
 * This function hides the Date dependency and makes testing harder
 */
export function createWebhookUpdatedAtNow(): Result<
  WebhookUpdatedAt,
  DomainError
> {
  return WebhookUpdatedAt.create(new Date());
}
