// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { WorkspaceErrors } from '../errors/workspace.errors';

/**
 * SigningSecret Value Object
 * Represents a validated signingSecret with business rules
 */
export const WorkspaceSigningSecret = createStringVO({
  name: 'SigningSecret',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(
    WorkspaceErrors.INVALID_SIGNING_SECRET,
    'SigningSecret',
  ),
});

/**
 * Public instance type for SigningSecret
 */
export type WorkspaceSigningSecret = StringVOInstance;

// Convenience creators
export const createWorkspaceSigningSecret = (s: string) =>
  WorkspaceSigningSecret.create(s);
export const workspaceSigningSecretFrom = (v: unknown) =>
  WorkspaceSigningSecret.from(v);
