// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

// Framework imports
import { Injectable, Inject } from '@nestjs/common';
import { Result, DomainError, ok, err } from 'src/shared/errors';
import { ActorContext } from 'src/shared/application/context';

// Shared utilities and infrastructure
import { APP_LOGGER, componentLogger, Logger } from 'src/shared/logging';
import { Clock, CLOCK } from 'src/shared/infrastructure/time';
import { Option } from 'src/shared/domain/types';
import { runUseCaseWithSecurity } from 'src/shared/application/utils';
import { extractDefinedFields } from 'src/shared/utilities';
import {
  UseCaseLoggingUtil,
  UseCaseLoggingConfig,
} from 'src/shared/application/utils/use-case-logging.util';
import { IUserToken } from 'src/shared/security';

// Service configuration
import { LookupServiceConstants } from '../../../service-constants';

// Domain types and errors
import { LookupTypeAggregate } from '../../domain/aggregates';
import {
  CreateLookupTypeProps,
  UpsertLookupTypeProps,
} from '../../domain/props';
import { LookupTypeCode } from '../../domain/value-objects';
import {
  createLookupTypeAggregateFromProps,
  updateLookupTypeAggregateFromSnapshot,
} from '../../domain/factories';
import { LookupTypeErrors } from '../../domain/errors';

// Application layer
import {
  ILookupTypeReader,
  ILookupTypeWriter,
  LOOKUP_TYPE_READER_TOKEN,
  LOOKUP_TYPE_WRITER_TOKEN,
} from '../ports';
import { UpsertLookupTypeCommand } from '../commands';
import { IUpsertLookupTypeUseCase } from './contracts';

import { LookupTypeAuthorizationAdapter } from '../services';
import { DetailLookupTypeResponse } from '../dtos';
import { LookupTypeDtoAssembler } from '../assemblers';

type LookupTypeSnapshot = Parameters<
  typeof updateLookupTypeAggregateFromSnapshot
>[0];

@Injectable()
export class UpsertLookupTypeUseCase implements IUpsertLookupTypeUseCase {
  private readonly logger: Logger;
  private readonly loggingConfig: UseCaseLoggingConfig;

  constructor(
    @Inject(LOOKUP_TYPE_READER_TOKEN)
    private readonly lookupTypeReader: ILookupTypeReader,
    @Inject(LOOKUP_TYPE_WRITER_TOKEN)
    private readonly lookupTypeWriter: ILookupTypeWriter,
    private readonly authorizationService: LookupTypeAuthorizationAdapter,
    @Inject(APP_LOGGER)
    readonly moduleLogger: Logger,
    @Inject(CLOCK)
    private readonly clock: Clock,
  ) {
    this.loggingConfig = {
      serviceName: LookupServiceConstants.SERVICE_NAME,
      component: 'UpsertLookupTypeUseCase',
      domain: 'lookup',
      entityType: 'lookup-type',
    };
    this.logger = componentLogger(moduleLogger, this.loggingConfig.component);
  }
  async execute(params: {
    user: IUserToken;
    code: string;
    props: UpsertLookupTypeProps;
    correlationId: string;
    authorizationReason: string;
  }): Promise<Result<DetailLookupTypeResponse, DomainError>> {
    const operation = 'upsert_lookup_type';
    const startTime = this.clock.nowMs();

    // Create a command-like object for internal use
    const command = {
      user: params.user,
      code: params.code,
      props: params.props,
      correlationId: params.correlationId,
      authorizationReason: params.authorizationReason,
      securityContext: {
        tenant: params.user.tenant,
        userId: params.user.sub,
        roles: params.user.roles,
      },
      timestamp: this.clock.now(),
    };

    // Step 1: Validate command (before creating any log context to avoid PII logging)
    const validation = UseCaseLoggingUtil.validateCommand(
      this.logger,
      command,
      {}, // Empty context to avoid PII logging during validation
    );
    if (!validation.ok) {
      return err(validation.error);
    }

    // Step 2: Create basic log context for audit trail
    const safeLogContext = UseCaseLoggingUtil.createLogContext(
      this.loggingConfig,
      this.clock,
      operation,
      {
        correlationId: command.correlationId,
        user: command.user,
        securityContext: command.securityContext,
        timestamp: command.timestamp,
      },
      {
        lookupTypeCode: command.code,
        operationRisk: UseCaseLoggingUtil.assessOperationRisk(operation),
      },
    );

    // Step 3: Process upsert with audit logging
    const rawProps = command.props; // Keep original for domain processing
    const fieldsToUpdate = extractDefinedFields(rawProps || {});

    // Note: UpsertLookupTypeProps approach provides cleaner validation semantics
    // The unified props structure eliminates complex type mappings and assertions

    // ---- UPSERT CORE ------------------------------------------------------
    // We first try to load; if not found, we'll "create" instead of erroring.

    // Discover existence ahead of time to configure auth intent correctly
    const codeR = LookupTypeCode.create(command.code);
    if (!codeR.ok) return err(codeR.error);

    // Create actor context using the standard utility
    const actor: ActorContext = {
      tenant: command.user.tenant,
      userId: command.user.sub,
      tenant_userId: command.user.tenant_id || '',
      username: command.user.email,
      roles: command.user.roles,
    };

    const existsR = await this.lookupTypeReader.exists(
      actor,
      command.props.lookupType ?? '',
      codeR.value,
    );
    if (!existsR.ok) return err(existsR.error);

    const isCreate = !existsR.value;
    const authType = isCreate ? 'create' : 'update';

    const aggregateResult = await runUseCaseWithSecurity<
      UpsertLookupTypeCommand,
      LookupTypeAggregate,
      LookupTypeSnapshot
    >({
      serviceName: LookupServiceConstants.SERVICE_NAME,
      component: 'UpsertLookupTypeUseCase',
      operation: isCreate ? 'create_lookup_type' : 'update_lookup_type',
      source: 'lookup-type-config.application.upsert-lookup-type',
      command,
      logger: this.logger,
      clock: this.clock,

      repo: {
        save: async (
          actor: ActorContext,
          lookupType: LookupTypeAggregate,
          expectedVersion?: number,
        ) => {
          const result = await this.lookupTypeWriter.save(
            actor,
            lookupType,
            expectedVersion,
          );
          return result.ok ? ok(undefined) : result;
        },
      },

      propsMissingError: LookupTypeErrors.INVALID_LOOKUP_TYPE_DATA,

      authorizationService: this.authorizationService,
      authorization: isCreate
        ? {
            type: 'create' as const,
            operation: 'create' as const,
          }
        : {
            type: 'update' as const,
            operation: 'update' as const,
            resourceId: command.code,
            fields: fieldsToUpdate.map(String),
          },
      authContext: {
        userId: command.user.sub,
        tenant: command.user.tenant,
        tenant_userId: command.user.tenant_id || '',
        roles: command.user.roles,
        operationType: authType,
      },

      // Load (if exists) but DO NOT error on missing → allow create path
      // For upsert operations, only load if we know it exists
      loadExisting: async () => {
        if (!isCreate) {
          // We know it exists, so load it for update
          const foundR = await this.lookupTypeReader.findById(
            actor,
            command.props.lookupType ?? '',
            codeR.value,
          );
          if (!foundR.ok) return foundR;

          // Handle Option type - extract value from Some or treat None as undefined
          if (Option.isNone(foundR.value)) {
            return ok(undefined as unknown as LookupTypeSnapshot);
          }

          return ok(foundR.value.value);
        }
        // Return ok with undefined for create path; runDomain will create
        return Promise.resolve(ok(undefined as unknown as LookupTypeSnapshot));
      },

      // Merge/update when existing, otherwise create with props
      runDomain: ({ existing, metadata, clock }) => {
        if (existing) {
          // UPDATE path - use existing update logic
          return updateLookupTypeAggregateFromSnapshot(
            existing,
            rawProps || {},
            metadata,
            clock,
          );
        }
        // CREATE path - Validate and transform, no default creation
        const upsertProps = {
          ...(rawProps || {}),
          code: command.code,
        };

        const createProps = upsertProps as CreateLookupTypeProps;
        return createLookupTypeAggregateFromProps(createProps, metadata, clock);
      },
    });

    if (!aggregateResult.ok) {
      UseCaseLoggingUtil.logOperationError(
        this.logger,
        operation,
        safeLogContext,
        aggregateResult.error,
        'HIGH',
      );
      return aggregateResult;
    }

    const aggregate = aggregateResult.value;
    const domainState = aggregate.toDomainState();
    const dto = LookupTypeDtoAssembler.toDetailResponse(domainState);

    const executionTime = this.clock.nowMs() - startTime;
    UseCaseLoggingUtil.logOperationSuccess(
      this.logger,
      operation,
      safeLogContext,
      {
        executionTimeMs: executionTime,
        aggregateVersion: aggregate.version,
        eventCount: aggregate.uncommittedEvents?.length ?? 0,
        businessData: {
          fieldsUpdated: Object.keys(fieldsToUpdate).length,
          upsertAction: isCreate ? 'created' : 'updated',
        },
      },
    );

    return ok(dto);
  }
}
