// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsNotEmpty, IsString } from 'class-validator';

/**
 * Options for property decorators
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Webhook TargetUrl
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiWebhookTargetUrl(options: PropOptions = {}) {
  const { required = true } = options;

  return applyDecorators(
    ApiProperty({
      description: `The complete HTTPS/HTTP URL where webhook events will be delivered. Must be a valid, accessible endpoint that can receive POST requests.`,
      type: String,
      required,
    }),
    IsString(),
    required ? IsNotEmpty() : IsOptional(),
  );
}
