// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsOptional, IsNotEmpty } from 'class-validator';

/**
 * Options for property decorators (boolean)
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Webhook VerifyTls
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiWebhookVerifyTls(options: PropOptions = {}) {
  const { required = false } = options;

  return applyDecorators(
    ApiProperty({
      description: `Whether to verify SSL/TLS certificates when making webhook requests. Set to false only for development/testing environments with self-signed certificates.`,
      type: Boolean,
      required,
    }),
    IsBoolean(),
    required ? IsNotEmpty() : IsOptional(),
  );
}
