// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsNotEmpty, IsString, MaxLength } from 'class-validator';

/**
 * Options for property decorators
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Webhook WebhookEventType
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiWebhookWebhookEventType(options: PropOptions = {}) {
  const { required = true } = options;

  return applyDecorators(
    ApiProperty({
      description: `Specific event type this webhook subscribes to, using dot notation format (e.g., 'order.created.v1', 'user.updated.v2'). Determines which events trigger this webhook.`,
      type: String,
      required,
    }),
    IsString(),
    MaxLength(128),
    required ? IsNotEmpty() : IsOptional(),
  );
}
