// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Result, DomainError } from 'src/shared/errors';
import { RepositoryOptions } from 'src/shared/infrastructure/repositories';
import { ActorContext } from 'src/shared/application/context';
import { Option } from 'src/shared/domain/types';
import { ConfigSnapshotProps } from '../../domain/props';
import { ConfigWorkspaceCode } from '../../domain/value-objects';

/**
 * Token for injecting IConfigReader port implementation
 */
export const CONFIG_READER_TOKEN = 'IConfigReader' as const;

/**
 * Config Reader Port - Interface Segregation Principle Implementation
 *
 * Handles basic read operations for Config aggregates.
 * This interface focuses solely on simple retrieval operations.
 *
 * ISP Benefits:
 * - Clients only depend on methods they actually use
 * - Easier to mock and test specific read scenarios
 * - Can be implemented independently from write operations
 * - Supports read-only implementations (e.g., reporting services)
 *
 * @domain Notification Context - Config Reader Port
 * @layer Application Ports
 * @pattern Interface Segregation Principle
 */
export interface IConfigReader {
  /**
   * Find a Config by its unique identifier
   * @param actor - The authenticated user context
   * @param workspaceCode - The unique identifier of the Config
   * @param options - Optional repository options
   * @returns Result containing the Config snapshot or null if not found
   */
  findById(
    actor: ActorContext,
    workspaceCode: ConfigWorkspaceCode,
    options?: RepositoryOptions,
  ): Promise<Result<Option<ConfigSnapshotProps>, DomainError>>;

  /**
   * Check if a config exists by ID (for write-path validation)
   * @param actor - The authenticated user context
   * @param workspaceCode - The unique identifier of the Config
   * @param options - Optional repository options
   * @returns Result containing boolean indicating existence
   */
  exists(
    actor: ActorContext,
    workspaceCode: ConfigWorkspaceCode,
    options?: RepositoryOptions,
  ): Promise<Result<boolean, DomainError>>;

  /**
   * Get config version for optimistic concurrency control
   * @param actor - The authenticated user context
   * @param workspaceCode - The unique identifier of the Config
   * @param options - Optional repository options
   * @returns Result containing version number or null if not found
   */
  getVersion(
    actor: ActorContext,
    workspaceCode: ConfigWorkspaceCode,
    options?: RepositoryOptions,
  ): Promise<Result<Option<number>, DomainError>>;

  /**
   * Get minimal config data for write-path operations
   * @param actor - The authenticated user context
   * @param workspaceCode - The unique identifier of the Config
   * @param options - Optional repository options
   * @returns Result containing minimal config data or null if not found
   */
  getMinimal(
    actor: ActorContext,
    workspaceCode: ConfigWorkspaceCode,
    options?: RepositoryOptions,
  ): Promise<
    Result<Option<{ workspaceCode: string; version: number }>, DomainError>
  >;
}
