// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Module } from '@nestjs/common';

// SlackConfig Application
import { NotificationSlackSlackConfigModule } from './slack-config/slack-config.module';

/**
 * NotificationSlack Bounded Context Module
 *
 * This module represents the notification-slack bounded context and aggregates
 * all applications within this domain.
 *
 * Applications in this context:
 * - SlackConfig: slack-config application
 */
@Module({
  imports: [NotificationSlackSlackConfigModule],
  controllers: [],
  providers: [],
  exports: [NotificationSlackSlackConfigModule],
})
export class NotificationSlackModule {}
