// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Result, DomainError } from 'src/shared/errors';
import { RepositoryOptions } from 'src/shared/infrastructure/repositories';
import { ActorContext } from 'src/shared/application/context';
import { Option } from 'src/shared/domain/types';
import { AuthSnapshotProps } from '../../domain/props';
import { AuthWebhookId } from '../../domain/value-objects';

/**
 * Token for injecting IAuthReader port implementation
 */
export const AUTH_READER_TOKEN = 'IAuthReader' as const;

/**
 * Auth Reader Port - Interface Segregation Principle Implementation
 *
 * Handles basic read operations for Auth aggregates.
 * This interface focuses solely on simple retrieval operations.
 *
 * ISP Benefits:
 * - Clients only depend on methods they actually use
 * - Easier to mock and test specific read scenarios
 * - Can be implemented independently from write operations
 * - Supports read-only implementations (e.g., reporting services)
 *
 * @domain Notification Context - Auth Reader Port
 * @layer Application Ports
 * @pattern Interface Segregation Principle
 */
export interface IAuthReader {
  /**
   * Find a Auth by its unique identifier
   * @param actor - The authenticated user context
   * @param webhookId - The unique identifier of the Auth
   * @param options - Optional repository options
   * @returns Result containing the Auth snapshot or null if not found
   */
  findById(
    actor: ActorContext,
    webhookId: AuthWebhookId,
    options?: RepositoryOptions,
  ): Promise<Result<Option<AuthSnapshotProps>, DomainError>>;

  /**
   * Check if a auth exists by ID (for write-path validation)
   * @param actor - The authenticated user context
   * @param webhookId - The unique identifier of the Auth
   * @param options - Optional repository options
   * @returns Result containing boolean indicating existence
   */
  exists(
    actor: ActorContext,
    webhookId: AuthWebhookId,
    options?: RepositoryOptions,
  ): Promise<Result<boolean, DomainError>>;

  /**
   * Get auth version for optimistic concurrency control
   * @param actor - The authenticated user context
   * @param webhookId - The unique identifier of the Auth
   * @param options - Optional repository options
   * @returns Result containing version number or null if not found
   */
  getVersion(
    actor: ActorContext,
    webhookId: AuthWebhookId,
    options?: RepositoryOptions,
  ): Promise<Result<Option<number>, DomainError>>;

  /**
   * Get minimal auth data for write-path operations
   * @param actor - The authenticated user context
   * @param webhookId - The unique identifier of the Auth
   * @param options - Optional repository options
   * @returns Result containing minimal auth data or null if not found
   */
  getMinimal(
    actor: ActorContext,
    webhookId: AuthWebhookId,
    options?: RepositoryOptions,
  ): Promise<
    Result<Option<{ webhookId: string; version: number }>, DomainError>
  >;
}
