// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { LookupXxxDomainState } from '../../domain/state';
import { DetailLookupXxxResponse, ListLookupXxxResponse } from '../dtos';

/**
 * LookupXxx DTO Assembler
 *
 * Converts LookupXxxDomainState (pure VOs) to transport DTOs.
 * Bridges the gap between rich domain objects and API response format.
 * Uses existing generated DTOs and follows established patterns.
 */

/**
 * Assembles DTOs from LookupXxxDomainState for API transport
 */
export class LookupXxxDtoAssembler {
  /**
   * Convert LookupXxxDomainState to detailed response DTO
   *
   * @param domainState - Rich domain state with VOs
   * @returns Clean DTO for API response
   */
  static toDetailResponse(
    domainState: LookupXxxDomainState,
  ): DetailLookupXxxResponse {
    const dto = new DetailLookupXxxResponse();

    // Extract primitive values from VOs
    dto.lookupType = domainState.lookupType.value;
    dto.code = domainState.code.value;
    dto.name = domainState.name.value;
    dto.description = domainState.description?.value;
    dto.enabled = domainState.enabled?.value;
    dto.attributes = domainState.attributes?.value;

    return dto;
  }

  /**
   * Convert LookupXxxDomainState to list response DTO
   *
   * @param domainState - Rich domain state with VOs
   * @returns Clean DTO for list API response
   */
  static toListResponse(
    domainState: LookupXxxDomainState,
  ): ListLookupXxxResponse {
    const dto = new ListLookupXxxResponse();

    // Extract primitive values from VOs
    dto.lookupType = domainState.lookupType.value;
    dto.code = domainState.code.value;
    dto.name = domainState.name.value;
    dto.description = domainState.description?.value;
    dto.enabled = domainState.enabled?.value;
    dto.attributes = domainState.attributes?.value;

    return dto;
  }

  /**
   * Convert array of LookupXxxDomainState to array of list DTOs
   *
   * @param domainStates - Array of rich domain states
   * @returns Array of clean DTOs for list API response
   */
  static toListResponseArray(
    domainStates: LookupXxxDomainState[],
  ): ListLookupXxxResponse[] {
    return domainStates.map((domainState) => this.toListResponse(domainState));
  }

  /**
   * Convert array of LookupXxxDomainState to array of detail DTOs
   *
   * @param domainStates - Array of rich domain states
   * @returns Array of clean DTOs for detail API response
   */
  static toDetailResponseArray(
    domainStates: LookupXxxDomainState[],
  ): DetailLookupXxxResponse[] {
    return domainStates.map((domainState) =>
      this.toDetailResponse(domainState),
    );
  }
}
