// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import type {
  SecureTestSignatureAlgorithmValue,
  SecureTestTypeValue,
} from './decorators';
import {
  ApiSecureTestDescription,
  ApiSecureTestId,
  ApiSecureTestName,
  ApiSecureTestOptions,
  ApiSecureTestPassword,
  ApiSecureTestSignatureAlgorithm,
  ApiSecureTestSigningSecret,
  ApiSecureTestType,
  ApiSecureTestUsername,
} from './decorators';
import type { DetailOptionsResponse } from './';

export class DetailSecureTestResponse {
  @ApiSecureTestId()
  id: string;

  @ApiSecureTestName()
  name: string;

  @ApiSecureTestDescription({ required: false })
  description?: string;

  @ApiSecureTestType()
  type: SecureTestTypeValue;

  @ApiSecureTestSigningSecret({ required: false })
  signingSecret?: string;

  @ApiSecureTestSignatureAlgorithm({ required: false })
  signatureAlgorithm?: SecureTestSignatureAlgorithmValue;

  @ApiSecureTestUsername({ required: false })
  username?: string;

  @ApiSecureTestPassword({ required: false })
  password?: string;

  @ApiSecureTestOptions()
  options: Record<string, DetailOptionsResponse>;
}
