// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Injectable, Inject } from '@nestjs/common';
import { Redis } from 'ioredis';
import { APP_LOGGER, Log, componentLogger, Logger } from 'src/shared/logging';
import { CorrelationUtil } from 'src/shared/utilities/correlation.util';
import { Clock, CLOCK } from 'src/shared/infrastructure/time';
import {
  RepositoryLoggingUtil,
  RepositoryLoggingConfig,
  handleRepositoryError,
  safeParseJSON,
  safeParseJSONArray,
  RepositoryOptions,
} from 'src/shared/infrastructure/repositories';
import { Result, DomainError, err, ok } from 'src/shared/errors';
import { Option } from 'src/shared/domain/types';
import { ActorContext } from 'src/shared/application/context';
import { RepositoryErrorFactory } from 'src/shared/domain/errors/repository.error';
import { CacheMetricsCollector } from 'src/shared/infrastructure/projections/cache-optimization';
import { WEBHOOK_CONFIG_DI_TOKENS } from '../../../webhook-config.constants';
import { AuthtypeProjectionKeys } from '../../authtype-projection-keys';
import { DetailAuthtypeResponse } from '../../application/dtos';
import { IAuthtypeQuery } from '../../application/ports';

/**
 * Internal authtype data structure for Redis operations
 * Extends DetailAuthtypeResponse with additional fields needed for caching and versioning
 */
interface AuthtypeCacheData extends DetailAuthtypeResponse {
  version: number;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Authtype Query Repository - Interface Segregation Principle Implementation
 *
 * Bounded Context: Notification/Authtype
 * Handles complex query operations including pagination, filtering, and search.
 * This repository focuses solely on advanced data retrieval operations using Redis projections.
 *
 * ISP Benefits:
 * - Clients that need simple reads don't depend on complex query methods
 * - Can be optimized independently using Redis indexing strategies
 * - Easier to implement caching strategies for query operations
 * - Supports analytical and reporting use cases with Redis sorted sets
 *
 * Redis Features Used:
 * - Hash-based authtype storage with cluster-safe keys
 * - Sorted set indexing for efficient pagination and sorting
 * - Pattern matching for id and name filtering
 * - SCAN operations for tenant isolation
 * - Production-ready caching with metrics collection
 *
 * @domain Notification Context - Authtype Query Repository (Redis)
 * @layer Infrastructure
 * @pattern Repository Pattern + Interface Segregation Principle + Redis Projector
 */
@Injectable()
export class AuthtypeQueryRepository implements IAuthtypeQuery {
  private readonly logger: Logger;
  private readonly loggingConfig: RepositoryLoggingConfig;
  private readonly metricsCollector = new CacheMetricsCollector();

  constructor(
    @Inject(APP_LOGGER) baseLogger: Logger,
    @Inject(CLOCK) private readonly clock: Clock,
    @Inject(WEBHOOK_CONFIG_DI_TOKENS.IO_REDIS)
    private readonly redis: Redis,
  ) {
    this.loggingConfig = {
      serviceName: 'AuthtypeConfigService',
      component: 'AuthtypeQueryRepository',
    };
    this.logger = componentLogger(baseLogger, this.loggingConfig.component);

    Log.info(
      this.logger,
      'AuthtypeQueryRepository initialized with Redis backend',
      {
        component: this.loggingConfig.component,
        redisStatus: this.redis.status,
        clusterSafe: true,
        cacheOptimized: true,
      },
    );
  }

  /**
   * Find a single authtype by id using Redis hash lookup
   *
   * Leverages the established Redis patterns from AuthtypeProjector
   * with cluster-safe keys and production-ready caching.
   *
   * Features:
   * - Cluster-safe Redis keys with hash tags for co-location
   * - Direct hash lookup for optimal performance (O(1))
   * - Tenant isolation using Redis key patterns
   * - Comprehensive logging and error handling
   * - Production-ready metrics collection
   * - Soft delete awareness
   *
   * @param actor - The actor context containing authentication and request metadata.
   * @param id - The authtype id to search for.
   * @param options - Optional repository options (e.g., timeout, correlation).
   * @returns A promise resolving to a Result containing the Authtype response or a DomainError.
   */
  async findById(
    actor: ActorContext,
    id: string,
    options?: RepositoryOptions,
  ): Promise<Result<Option<DetailAuthtypeResponse>, DomainError>> {
    const operation = 'findById';
    const correlationId =
      options?.correlationId ??
      CorrelationUtil.generateForOperation('authtype-query-findById');

    const logContext = this.createLogContext(operation, correlationId, actor, {
      authtypeId: id,
      dataSource: 'redis-projector',
    });

    // Validate actor context with enhanced security logging
    const validation = RepositoryLoggingUtil.validateActorContext(
      this.logger,
      actor,
      logContext,
    );
    if (!validation.ok) return err(validation.error);

    // Guard tenant explicitly
    if (!actor.tenant) {
      return err(
        RepositoryErrorFactory.validationError('tenant', 'Missing tenant id'),
      );
    }

    // Log successful authorization
    RepositoryLoggingUtil.logAuthorizationSuccess(
      this.logger,
      operation,
      logContext,
      {
        operationType: 'authtype_query_findById',
        scope: 'redis_single_lookup',
        tenant: actor.tenant,
      },
    );

    try {
      // Generate cluster-safe Redis key
      const authtypeKey = this.generateAuthtypeKey(actor.tenant, id);

      Log.debug(this.logger, 'Executing Redis hash lookup', {
        ...logContext,
        queryDetails: {
          scope: 'redis_hgetall',
          method: 'redis.hgetall',
          key: authtypeKey,
          clusterSafe: true,
        },
      });

      // Fetch authtype hash from Redis
      const hashData = await this.redis.hgetall(authtypeKey);

      if (!hashData || Object.keys(hashData).length === 0) {
        Log.debug(this.logger, 'Authtype not found in Redis', logContext);
        return ok(Option.none());
      }

      // Parse Redis hash to authtype data
      const authtype = this.parseRedisHashToAuthtype(hashData);

      if (!authtype) {
        // Authtype exists but is soft deleted or malformed
        Log.debug(
          this.logger,
          'Authtype exists but is soft deleted or malformed',
          {
            ...logContext,
            softDeleted: !!hashData.deletedAt,
          },
        );
        return ok(Option.none());
      }

      // Transform to DetailAuthtypeResponse DTO (excluding internal fields)
      const detailResponse: DetailAuthtypeResponse = {
        id: authtype.id,
        webhookId: authtype.webhookId,
        type: authtype.type,
        signingSecretRef: authtype.signingSecretRef,
        signatureAlgorithm: authtype.signatureAlgorithm,
        usernameRef: authtype.usernameRef,
        passwordRef: authtype.passwordRef,
        apiKeyRef: authtype.apiKeyRef,
        apiKeyHeader: authtype.apiKeyHeader,
        apiKeyQueryParam: authtype.apiKeyQueryParam,
        tokenUrl: authtype.tokenUrl,
        clientIdRef: authtype.clientIdRef,
        clientSecretRef: authtype.clientSecretRef,
        scope: authtype.scope,
        certRef: authtype.certRef,
        keyRef: authtype.keyRef,
        caRef: authtype.caRef,
      };

      Log.debug(this.logger, 'Authtype found successfully in Redis', {
        ...logContext,
        resultData: {
          authtypeId: detailResponse.id,
          cacheHit: true,
        },
      });

      return ok(Option.some(detailResponse));
    } catch (error) {
      // Log operation error using shared utility
      RepositoryLoggingUtil.logOperationError(
        this.logger,
        operation,
        logContext,
        error as Error,
        'MEDIUM',
      );

      // Handle and return the classified error using shared utility
      return handleRepositoryError(error);
    }
  }

  /**
   * Generate cluster-safe Redis keys using centralized AuthtypeProjectionKeys
   * Ensures consistency with projector key patterns
   */
  private generateAuthtypeKey(tenant: string, id: string): string {
    // ✅ Use centralized key generation for consistency
    return AuthtypeProjectionKeys.getRedisAuthtypeKey(tenant, id);
  }

  /**
   * Generate tenant index key for pagination and sorting using centralized keys
   */
  private generateTenantIndexKey(tenant: string): string {
    return AuthtypeProjectionKeys.getRedisAuthtypeIndexKey(tenant);
  }

  /**
   * Parse Redis hash data into DetailAuthtypeResponse DTO
   * Uses DTO instead of domain props for CQRS compliance
   */
  private parseRedisHashToAuthtype(
    hashData: Record<string, string>,
  ): AuthtypeCacheData | null {
    try {
      if (!hashData || Object.keys(hashData).length === 0) {
        return null;
      }

      // Check for soft deletion
      if (hashData.deletedAt) {
        return null;
      }

      // Parse array fields using safeParseJSONArray utility

      // Parse object fields using safeParseJSON utility
      // Extract basic fields directly from hash data

      // Type assertion for type - cached data should already be validated
      const type = hashData.type as DetailAuthtypeResponse['type'];

      // Type assertion for signatureAlgorithm - cached data should already be validated
      const signatureAlgorithm =
        hashData.signatureAlgorithm as DetailAuthtypeResponse['signatureAlgorithm'];

      return {
        id: hashData.id,
        webhookId: hashData.webhookId,
        type,
        signingSecretRef: hashData.signingSecretRef || undefined,
        signatureAlgorithm,
        usernameRef: hashData.usernameRef || undefined,
        passwordRef: hashData.passwordRef || undefined,
        apiKeyRef: hashData.apiKeyRef || undefined,
        apiKeyHeader: hashData.apiKeyHeader || undefined,
        apiKeyQueryParam: hashData.apiKeyQueryParam || undefined,
        tokenUrl: hashData.tokenUrl || undefined,
        clientIdRef: hashData.clientIdRef || undefined,
        clientSecretRef: hashData.clientSecretRef || undefined,
        scope: hashData.scope || undefined,
        certRef: hashData.certRef || undefined,
        keyRef: hashData.keyRef || undefined,
        caRef: hashData.caRef || undefined,
        version: parseInt(hashData.version, 10),
        createdAt: new Date(hashData.createdAt),
        updatedAt: new Date(hashData.updatedAt),
      };
    } catch (error) {
      Log.error(
        this.logger,
        'Failed to parse Redis hash data to AuthtypeSnapshot',
        {
          method: 'parseRedisHashToAuthtype',
          error: (error as Error).message,
          id: hashData?.id,
        },
      );
      return null;
    }
  }
  /**
   * Helper to create consistent logging context using shared utilities
   */
  private createLogContext(
    operation: string,
    correlationId: string,
    actor: ActorContext,
    additionalContext?: Record<string, unknown>,
  ): Record<string, unknown> {
    return RepositoryLoggingUtil.createLogContext(
      this.loggingConfig,
      this.clock,
      operation,
      correlationId,
      actor,
      additionalContext,
    );
  }
}
