// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { AttributeRulePermission } from '../../domain/permissions/attribute-rule.permissions';

/**
 * Field-level permission matrix for AttributeRule updates.
 * Maps attributeRule fields to the required permissions for modification.
 */
export class AttributeRuleFieldPermissionMatrix {
  private static readonly fieldPermissions: Record<
    string,
    AttributeRulePermission[]
  > = {
    // Basic attributeRule information fields - require standard update permission
    name: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],
    description: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],
    category: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],

    // Status fields - may require special permissions or admin rights
    active: [
      AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE,
      AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_ADMIN,
    ],
    status: [
      AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE,
      AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_ADMIN,
    ],

    // Financial fields - typically require higher permissions
    fees: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],
    rates: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],
    pricing: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],

    // Configuration fields
    channelCodes: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],
    railCodes: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],
    configuration: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],

    // Administrative fields - require admin permissions
    tenant: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_ADMIN],
    auditInfo: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_ADMIN],
    metadata: [AttributeRulePermission.DOMAIN_ATTRIBUTE_RULE_UPDATE],
  };

  /**
   * Get required permissions for a specific field.
   * Returns empty array if field has no special permission requirements.
   */
  static getRequiredPermissions(fieldName: string): AttributeRulePermission[] {
    return this.fieldPermissions[fieldName] || [];
  }

  /**
   * Check if a field has specific permission requirements.
   */
  static hasSpecialPermissions(fieldName: string): boolean {
    return fieldName in this.fieldPermissions;
  }

  /**
   * Get all fields that require a specific permission.
   */
  static getFieldsForPermission(permission: AttributeRulePermission): string[] {
    return Object.entries(this.fieldPermissions)
      .filter(([, perms]) => perms.includes(permission))
      .map(([field]) => field);
  }

  /**
   * Get all defined field permissions.
   */
  static getAllFieldPermissions(): Record<string, AttributeRulePermission[]> {
    return { ...this.fieldPermissions };
  }

  /**
   * Add or update permission requirements for a field.
   */
  static setFieldPermissions(
    fieldName: string,
    permissions: AttributeRulePermission[],
  ): void {
    this.fieldPermissions[fieldName] = [...permissions];
  }
}
