// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  ChannelCreatedAt,
  ChannelUpdatedAt,
  ChannelVersion,
  ChannelCode,
  ChannelEnabled,
  ChannelIsDm,
  ChannelIsPrivate,
  ChannelName,
  ChannelPurpose,
  ChannelSubscribedEvents,
  ChannelTopic,
  ChannelWorkspaceCode,
} from '../value-objects';

/**
 * Channel Domain State
 *
 * Domain state interface that uses value objects to model business concepts
 * while maintaining compatibility with entity operations. Business fields are
 * modeled as value objects with proper validation and domain rules.
 *
 * Domain-First State Interface
 *
 * This interface represents the domain model where business concepts
 * are properly encapsulated as value objects when appropriate.
 */

export interface ChannelDomainState {
  code: ChannelCode;
  name: ChannelName;
  workspaceCode: ChannelWorkspaceCode;
  isPrivate: ChannelIsPrivate;
  isDm: ChannelIsDm;
  topic?: ChannelTopic;
  purpose?: ChannelPurpose;
  subscribedEvents?: ChannelSubscribedEvents;
  enabled: ChannelEnabled;
  version: ChannelVersion;
  createdAt: ChannelCreatedAt;
  updatedAt: ChannelUpdatedAt;
}

export type ChannelDomainStateOptional = Partial<ChannelDomainState>;
