// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { Inject } from '@nestjs/common';
import { Result, DomainError } from 'src/shared/errors';
import { APP_LOGGER, componentLogger, Logger } from 'src/shared/logging';
import { CommandHandlerUtil } from 'src/shared/application';
import { DetailWebhookResponse } from '../dtos';
import { UpsertWebhookUseCase } from '../use-cases';
import { UpsertWebhookCommand } from '../commands';

/**
 * Enhanced Upsert Webhook Handler with security context support
 */
@CommandHandler(UpsertWebhookCommand)
export class UpsertWebhookHandler
  implements ICommandHandler<UpsertWebhookCommand>
{
  private readonly logger: Logger;

  constructor(
    @Inject(UpsertWebhookUseCase)
    private readonly upsertWebhookUseCase: UpsertWebhookUseCase,
    @Inject(APP_LOGGER) moduleLogger: Logger,
  ) {
    this.logger = componentLogger(moduleLogger, 'UpsertWebhookHandler');
  }

  /**
   * Executes the upsert webhook command with enhanced security and validation
   */
  async execute(
    command: UpsertWebhookCommand,
  ): Promise<Result<DetailWebhookResponse, DomainError>> {
    const commandName = 'UpsertWebhookCommand';

    // Log command execution start
    CommandHandlerUtil.logCommandStart(this.logger, commandName, command, {
      application: 'webhook-config',
      component: 'UpsertWebhookHandler',
      extractCommandData: (cmd: UpsertWebhookCommand) => ({
        propsKeys: Object.keys(cmd.props || {}),
      }),
    });

    // Transform command to use case parameters
    const result = await this.upsertWebhookUseCase.execute({
      user: command.user,
      id: command.id,
      props: command.props,
      correlationId: command.correlationId,
      authorizationReason: 'CQRS Command Handler',
    });

    // Log result with enhanced context
    if (result.ok) {
      CommandHandlerUtil.logCommandSuccess(
        this.logger,
        commandName,
        command,
        result.value,
        {
          application: 'webhook-config',
          component: 'UpsertWebhookHandler',
        },
      );
    } else {
      // Use shared error handling with custom context
      CommandHandlerUtil.logValidationError(
        this.logger,
        commandName,
        result.error,
        command,
        {
          application: 'webhook-config',
          component: 'UpsertWebhookHandler',
          extractErrorContext: (cmd: UpsertWebhookCommand) => ({
            inputStructure: {
              hasProps: !!cmd.props,
              propsKeys: cmd.props ? Object.keys(cmd.props) : [],
            },
          }),
        },
      );
    }

    return result;
  }
}
