// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Injectable, Inject } from '@nestjs/common';
import { APP_LOGGER, Log, componentLogger, Logger } from 'src/shared/logging';
import { CorrelationUtil } from 'src/shared/utilities/correlation.util';
import { Clock, CLOCK } from 'src/shared/infrastructure/time';
import {
  RepositoryLoggingUtil,
  RepositoryLoggingConfig,
  handleRepositoryError,
  RepositoryOptions,
} from 'src/shared/infrastructure/repositories';
import { Result, DomainError, ok } from 'src/shared/errors';
import { ActorContext } from 'src/shared/application/context';
import { Option } from 'src/shared/domain/types';
import { CacheMetricsCollector } from 'src/shared/infrastructure/projections/cache-optimization';
import { DetailLookupTypeResponse } from '../../application/dtos';
import {
  lookupTypeStore,
  LookupTypeProjection,
} from '../stores/lookup-type.store';
import { ILookupTypeQuery } from '../../application/ports';

/**
 * LookupType Read Model - In-Memory Projection
 * Used internally by the query repository to work with read-optimized data
 * Uses DTOs consistently throughout (proper CQRS pattern - no domain props in read model)
 */
interface LookupTypeReadModel {
  lookupType: string;
  code: string;
  name: string;
  description?: string;
  enabled?: boolean;
  attributes?: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
  version: number;
}

/**
 * Domain Props to DTO Conversion Utilities
 * Used when converting from the in-memory store (domain props) to the read model (DTOs)


/**
 * LookupType Query Repository - CQRS Read Model Implementation (In-Memory)
 *
 * Bounded Context: Core/LookupType
 * Handles complex query operations including pagination, filtering, and search using in-memory projector
 * as the data source. Returns DTOs/ViewModels optimized for read operations, NOT domain props.
 *
 * CQRS Benefits:
 * - Returns read-optimized DTOs (DetailLookupTypeResponse, ListLookupTypeResponse)
 * - No dependency on domain props (proper read/write model separation)
 * - Zero external database dependencies
 * - Ultra-fast query operations (LRU cache)
 * - Perfect for testing, prototyping, and shadow validation
 * - Comprehensive logging and error handling
 *
 * ISP Benefits:
 * - Clients that need simple reads don't depend on complex query methods
 * - Can be optimized independently using in-memory indexing strategies
 * - Easier to implement caching strategies for query operations
 * - Supports analytical and reporting use cases with in-memory operations
 *
 * @domain Core Context - LookupType Query Repository (Read Side)
 * @layer Infrastructure
 * @pattern CQRS + Repository Pattern + Interface Segregation Principle + In-Memory Projector
 */
@Injectable()
export class LookupTypeQueryRepository implements ILookupTypeQuery {
  private readonly logger: Logger;
  private readonly loggingConfig: RepositoryLoggingConfig;
  private readonly metricsCollector = new CacheMetricsCollector();

  constructor(
    @Inject(APP_LOGGER) baseLogger: Logger,
    @Inject(CLOCK) private readonly clock: Clock,
  ) {
    this.loggingConfig = {
      serviceName: 'LookupTypeConfigService',
      component: 'LookupTypeQueryRepository',
    };
    this.logger = componentLogger(baseLogger, this.loggingConfig.component);

    Log.info(
      this.logger,
      'LookupTypeQueryRepository initialized with in-memory backend',
      {
        component: this.loggingConfig.component,
        architecture: 'in-memory-shared-store',
        dataSource: 'in-memory-projector',
        cacheOptimized: true,
      },
    );
  }

  /**
   * Convert LookupTypeProjection to LookupTypeReadModel (reusable conversion logic)
   */
  private projectionToReadModel(
    projection: LookupTypeProjection,
  ): LookupTypeReadModel {
    return {
      lookupType: projection.lookupType,
      code: projection.code,
      name: projection.name,
      description: projection.description,
      enabled: projection.enabled,
      attributes: projection.attributes,
      createdAt: projection.createdAt || this.clock.now(),
      updatedAt: projection.updatedAt || this.clock.now(),
      version: projection.version || 1,
    };
  }

  /**
   * Get all lookup-types for a tenant from the in-memory store
   * Filters out soft-deleted lookup-types and converts to read model
   */
  private getLookupTypesForTenant(tenant: string): LookupTypeReadModel[] {
    const allProjections = lookupTypeStore.getAll();
    const lookupTypes: LookupTypeReadModel[] = [];

    for (const [key, projection] of allProjections) {
      // Parse key to extract tenant and code
      const [projectionTenantId] = key.split(':');

      // Only include lookup-types for the requested tenant
      if (projectionTenantId === tenant && !projection.deletedAt) {
        // Convert projection to read model using shared conversion logic
        const readModel = this.projectionToReadModel(projection);
        lookupTypes.push(readModel);
      }
    }

    return lookupTypes;
  }

  /**
   * Transform LookupTypeReadModel to DetailLookupTypeResponse DTO
   */
  private toDetailResponse(
    lookupType: LookupTypeReadModel,
  ): DetailLookupTypeResponse {
    return {
      lookupType: lookupType.lookupType,
      code: lookupType.code,
      name: lookupType.name,
      description: lookupType.description,
      enabled: lookupType.enabled,
      attributes: lookupType.attributes,
    } as DetailLookupTypeResponse;
  }
  /**
   * Helper to create consistent logging context using shared utilities
   */
  private createLogContext(
    operation: string,
    correlationId: string,
    actor: ActorContext,
    additionalContext?: Record<string, unknown>,
  ): Record<string, unknown> {
    return RepositoryLoggingUtil.createLogContext(
      this.loggingConfig,
      this.clock,
      operation,
      correlationId,
      actor,
      additionalContext,
    );
  }

  /**
   * Find a single LookupType by its unique identifier (for CQRS query operations)
   * @param actor - The actor context containing authentication and request metadata
   * @param code - The unique identifier of the LookupType
   * @param options - Optional repository options
   * @returns A promise resolving to a Result containing the LookupType or null if not found
   */
  findById(
    actor: ActorContext,
    code: string,
    options?: RepositoryOptions,
  ): Promise<Result<Option<DetailLookupTypeResponse>, DomainError>> {
    const operation = 'findById';
    const correlationId =
      options?.correlationId ??
      CorrelationUtil.generateForOperation('lookupType-query-findById');

    const logContext = this.createLogContext(operation, correlationId, actor, {
      lookupTypeCode: code,
    });

    try {
      Log.debug(this.logger, 'Finding lookupType by code', {
        ...logContext,
        queryDetails: {
          scope: 'shared_lookupType_store',
          method: 'lookupTypeStore.get',
          tenant: actor.tenant,
        },
      });

      // Find the lookupType in the store
      const projection = lookupTypeStore.get(
        actor.tenant || 'default-tenant',
        code,
      );

      if (!projection) {
        Log.debug(this.logger, 'LookupType not found', logContext);
        return Promise.resolve(ok(Option.none()));
      }

      // Convert projection to read model, then transform to DetailLookupTypeResponse DTO
      const readModel = this.projectionToReadModel(projection);
      const detailResponse = this.toDetailResponse(readModel);

      Log.debug(this.logger, 'LookupType found successfully', {
        ...logContext,
        resultData: {
          lookupTypeCode: detailResponse.code,
          lookupTypeName: detailResponse.name,
        },
      });

      return Promise.resolve(ok(Option.some(detailResponse)));
    } catch (error) {
      RepositoryLoggingUtil.logOperationError(
        this.logger,
        operation,
        logContext,
        error as Error,
        'MEDIUM',
      );
      return Promise.resolve(handleRepositoryError(error));
    }
  }
}
