// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Injectable, Inject } from '@nestjs/common';
import { Redis } from 'ioredis';
import { APP_LOGGER, Log, componentLogger, Logger } from 'src/shared/logging';
import { CorrelationUtil } from 'src/shared/utilities/correlation.util';
import { Clock, CLOCK } from 'src/shared/infrastructure/time';
import {
  RepositoryLoggingUtil,
  RepositoryLoggingConfig,
  handleRepositoryError,
  safeParseJSON,
  safeParseJSONArray,
  RepositoryOptions,
} from 'src/shared/infrastructure/repositories';
import { Result, DomainError, err, ok } from 'src/shared/errors';
import { Option } from 'src/shared/domain/types';
import { ActorContext } from 'src/shared/application/context';
import { RepositoryErrorFactory } from 'src/shared/domain/errors/repository.error';
import { CacheMetricsCollector } from 'src/shared/infrastructure/projections/cache-optimization';
import { LOOKUP_DI_TOKENS } from '../../../lookup.constants';
import { LookupTypeProjectionKeys } from '../../lookup-type-projection-keys';
import {
  DetailLookupTypeResponse,
  LookupTypePageResponse,
  ListLookupTypeFilterRequest,
  ListLookupTypeResponse,
} from '../../application/dtos';
import { PaginationMetaResponse } from 'src/shared/application/dtos';
import { ILookupTypeQuery } from '../../application/ports';

/**
 * Internal lookupType data structure for Redis operations
 * Extends DetailLookupTypeResponse with additional fields needed for caching and versioning
 */
interface LookupTypeCacheData extends DetailLookupTypeResponse {
  version: number;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * LookupType Query Repository - Interface Segregation Principle Implementation
 *
 * Bounded Context: Core/LookupType
 * Handles complex query operations including pagination, filtering, and search.
 * This repository focuses solely on advanced data retrieval operations using Redis projections.
 *
 * ISP Benefits:
 * - Clients that need simple reads don't depend on complex query methods
 * - Can be optimized independently using Redis indexing strategies
 * - Easier to implement caching strategies for query operations
 * - Supports analytical and reporting use cases with Redis sorted sets
 *
 * Redis Features Used:
 * - Hash-based lookupType storage with cluster-safe keys
 * - Sorted set indexing for efficient pagination and sorting
 * - Pattern matching for code and name filtering
 * - SCAN operations for tenant isolation
 * - Production-ready caching with metrics collection
 *
 * @domain Core Context - LookupType Query Repository (Redis)
 * @layer Infrastructure
 * @pattern Repository Pattern + Interface Segregation Principle + Redis Projector
 */
@Injectable()
export class LookupTypeQueryRepository implements ILookupTypeQuery {
  private readonly logger: Logger;
  private readonly loggingConfig: RepositoryLoggingConfig;
  private readonly metricsCollector = new CacheMetricsCollector();

  constructor(
    @Inject(APP_LOGGER) baseLogger: Logger,
    @Inject(CLOCK) private readonly clock: Clock,
    @Inject(LOOKUP_DI_TOKENS.IO_REDIS)
    private readonly redis: Redis,
  ) {
    this.loggingConfig = {
      serviceName: 'LookupTypeConfigService',
      component: 'LookupTypeQueryRepository',
    };
    this.logger = componentLogger(baseLogger, this.loggingConfig.component);

    Log.info(
      this.logger,
      'LookupTypeQueryRepository initialized with Redis backend',
      {
        component: this.loggingConfig.component,
        redisStatus: this.redis.status,
        clusterSafe: true,
        cacheOptimized: true,
      },
    );
  }

  /**
   * Find a single lookupType by code using Redis hash lookup
   *
   * Leverages the established Redis patterns from LookupTypeProjector
   * with cluster-safe keys and production-ready caching.
   *
   * Features:
   * - Cluster-safe Redis keys with hash tags for co-location
   * - Direct hash lookup for optimal performance (O(1))
   * - Tenant isolation using Redis key patterns
   * - Comprehensive logging and error handling
   * - Production-ready metrics collection
   * - Soft delete awareness
   *
   * @param actor - The actor context containing authentication and request metadata.
   * @param code - The lookupType code to search for.
   * @param options - Optional repository options (e.g., timeout, correlation).
   * @returns A promise resolving to a Result containing the LookupType response or a DomainError.
   */
  async findById(
    actor: ActorContext,
    lookupType: string,
    code: string,
    options?: RepositoryOptions,
  ): Promise<Result<Option<DetailLookupTypeResponse>, DomainError>> {
    const operation = 'findById';
    const correlationId =
      options?.correlationId ??
      CorrelationUtil.generateForOperation('lookup-type-query-findById');

    const logContext = this.createLogContext(operation, correlationId, actor, {
      lookupTypeCode: code,
      dataSource: 'redis-projector',
    });

    // Validate actor context with enhanced security logging
    const validation = RepositoryLoggingUtil.validateActorContext(
      this.logger,
      actor,
      logContext,
    );
    if (!validation.ok) return err(validation.error);

    // Guard tenant explicitly
    if (!actor.tenant) {
      return err(
        RepositoryErrorFactory.validationError('tenant', 'Missing tenant id'),
      );
    }

    // Log successful authorization
    RepositoryLoggingUtil.logAuthorizationSuccess(
      this.logger,
      operation,
      logContext,
      {
        operationType: 'lookup-type_query_findById',
        scope: 'redis_single_lookup',
        tenant: actor.tenant,
      },
    );

    try {
      // Generate cluster-safe Redis key
      const lookupTypeKey = this.generateLookupTypeKey(actor.tenant, code);

      Log.debug(this.logger, 'Executing Redis hash lookup', {
        ...logContext,
        queryDetails: {
          scope: 'redis_hgetall',
          method: 'redis.hgetall',
          key: lookupTypeKey,
          clusterSafe: true,
        },
      });

      // Fetch lookupType hash from Redis
      const hashData = await this.redis.hgetall(lookupTypeKey);

      if (!hashData || Object.keys(hashData).length === 0) {
        Log.debug(this.logger, 'LookupType not found in Redis', logContext);
        return ok(Option.none());
      }

      // Parse Redis hash to lookupType data
      const lookupType = this.parseRedisHashToLookupType(hashData);

      if (!lookupType) {
        // LookupType exists but is soft deleted or malformed
        Log.debug(
          this.logger,
          'LookupType exists but is soft deleted or malformed',
          {
            ...logContext,
            softDeleted: !!hashData.deletedAt,
          },
        );
        return ok(Option.none());
      }

      // Transform to DetailLookupTypeResponse DTO (excluding internal fields)
      const detailResponse: DetailLookupTypeResponse = {
        code: lookupType.code,
        lookupType: lookupType.lookupType,
        name: lookupType.name,
        description: lookupType.description,
        enabled: lookupType.enabled,
        attributes: lookupType.attributes,
      };

      Log.debug(this.logger, 'LookupType found successfully in Redis', {
        ...logContext,
        resultData: {
          lookupTypeCode: detailResponse.code,
          lookupTypeName: detailResponse.name,
          cacheHit: true,
        },
      });

      return ok(Option.some(detailResponse));
    } catch (error) {
      // Log operation error using shared utility
      RepositoryLoggingUtil.logOperationError(
        this.logger,
        operation,
        logContext,
        error as Error,
        'MEDIUM',
      );

      // Handle and return the classified error using shared utility
      return handleRepositoryError(error);
    }
  }

  /**
   * Generate cluster-safe Redis keys using centralized LookupTypeProjectionKeys
   * Ensures consistency with projector key patterns
   */
  private generateLookupTypeKey(tenant: string, id: string): string {
    // ✅ Use centralized key generation for consistency
    return LookupTypeProjectionKeys.getRedisLookupTypeKey(tenant, id);
  }

  /**
   * Generate tenant index key for pagination and sorting using centralized keys
   */
  private generateTenantIndexKey(tenant: string): string {
    return LookupTypeProjectionKeys.getRedisLookupTypeIndexKey(tenant);
  }

  /**
   * Parse Redis hash data into DetailLookupTypeResponse DTO
   * Uses DTO instead of domain props for CQRS compliance
   */
  private parseRedisHashToLookupType(
    hashData: Record<string, string>,
  ): LookupTypeCacheData | null {
    try {
      if (!hashData || Object.keys(hashData).length === 0) {
        return null;
      }

      // Check for soft deletion
      if (hashData.deletedAt) {
        return null;
      }

      // Parse array fields using safeParseJSONArray utility

      // Parse object fields using safeParseJSON utility
      const attributes = safeParseJSON<Record<string, unknown>>(
        hashData.attributes,
        'attributes',
      );
      // Extract basic fields directly from hash data

      return {
        lookupType: hashData.lookupType,
        code: hashData.code,
        name: hashData.name,
        description: hashData.description || undefined,
        enabled: hashData.enabled === 'true',
        attributes,
        version: parseInt(hashData.version, 10),
        createdAt: new Date(hashData.createdAt),
        updatedAt: new Date(hashData.updatedAt),
      };
    } catch (error) {
      Log.error(
        this.logger,
        'Failed to parse Redis hash data to LookupTypeSnapshot',
        {
          method: 'parseRedisHashToLookupType',
          error: (error as Error).message,
          code: hashData?.code,
        },
      );
      return null;
    }
  }

  /**
   * Transform LookupType CacheData to ListLookupTypeResponse DTO
   */
  private toListResponse(
    lookupType: LookupTypeCacheData,
  ): ListLookupTypeResponse {
    return {
      lookupType: lookupType.lookupType,
      code: lookupType.code,
      name: lookupType.name,
      description: lookupType.description,
      enabled: lookupType.enabled,
      attributes: lookupType.attributes,
    } as ListLookupTypeResponse;
  }

  /**
   * Apply filters to lookupType data using Redis pattern matching and client-side filtering
   */
  private matchesFilter(
    lookupType: LookupTypeCacheData,
    filter?: ListLookupTypeFilterRequest,
  ): boolean {
    if (!filter) return true;

    // Filter by name (partial match)
    if (filter.name) {
      if (lookupType.name?.toLowerCase().includes(filter.name.toLowerCase())) {
        return false;
      }
    }
    // Filter by code (partial match)
    if (filter.code) {
      if (lookupType.code?.toLowerCase().includes(filter.code.toLowerCase())) {
        return false;
      }
    }

    return true;
  }

  /**
   * Sort lookupTypes based on sort criteria
   * Handles undefined/null values properly and provides stable sorting
   */
  private sortLookupTypes(
    lookupTypes: LookupTypeCacheData[],
    sortBy?: Record<string, string>,
  ): LookupTypeCacheData[] {
    if (!sortBy || Object.keys(sortBy).length === 0) {
      // No sorting criteria provided, return as-is
      return lookupTypes;
    }

    return lookupTypes.sort((a, b) => {
      for (const [field, direction] of Object.entries(sortBy)) {
        let aVal: number | Date | string | undefined;
        let bVal: number | Date | string | undefined;

        switch (field) {
          case 'name':
            aVal = a.name;
            bVal = b.name;
            break;
          case 'code':
            aVal = a.code;
            bVal = b.code;
            break;
          case 'createdAt':
            aVal = a.createdAt;
            bVal = b.createdAt;
            break;
          case 'updatedAt':
            aVal = a.updatedAt;
            bVal = b.updatedAt;
            break;
          default:
            continue;
        }

        // Handle undefined/null values - put them at the end
        if (aVal == null && bVal == null) continue;
        if (aVal == null) return 1; // null values go to the end
        if (bVal == null) return -1; // null values go to the end

        if (aVal === bVal) continue;

        let comparison: number;

        // Handle different types properly
        if (aVal instanceof Date && bVal instanceof Date) {
          comparison = aVal.getTime() - bVal.getTime() < 0 ? -1 : 1;
        } else if (typeof aVal === 'number' && typeof bVal === 'number') {
          comparison = aVal - bVal < 0 ? -1 : 1;
        } else {
          // String comparison (convert to string if needed)
          const aStr = String(aVal).toLowerCase();
          const bStr = String(bVal).toLowerCase();
          comparison = aStr < bStr ? -1 : 1;
        }

        return direction?.toLowerCase() === 'desc' ? -comparison : comparison;
      }
      return 0;
    });
  }
  /**
   * Helper to create consistent logging context using shared utilities
   */
  private createLogContext(
    operation: string,
    correlationId: string,
    actor: ActorContext,
    additionalContext?: Record<string, unknown>,
  ): Record<string, unknown> {
    return RepositoryLoggingUtil.createLogContext(
      this.loggingConfig,
      this.clock,
      operation,
      correlationId,
      actor,
      additionalContext,
    );
  }

  /**
   * Find LookupType records with pagination and filtering using Redis projections.
   *
   * Leverages the established Redis patterns from LookupTypeProjector and LookupTypeReaderRepository
   * with cluster-safe keys and production-ready caching.
   *
   * Features:
   * - Cluster-safe Redis keys with hash tags for co-location
   * - Client-side filtering for code patterns and name search
   * - Efficient in-memory sorting with configurable directions
   * - Pagination with total count calculation
   * - Tenant isolation using Redis key patterns
   * - Comprehensive logging and error handling
   * - Production-ready metrics collection
   *
   * @param actor - The actor context containing authentication and request metadata.
   * @param filter - Optional filter criteria for the lookup-type search.
   * @param options - Optional repository options (e.g., pagination, sorting).
   * @returns A promise resolving to a Result containing paginated LookupType responses or a DomainError.
   */
  async findPaginated(
    actor: ActorContext,
    lookupType: string,
    filter?: ListLookupTypeFilterRequest,
    options?: RepositoryOptions,
  ): Promise<Result<LookupTypePageResponse, DomainError>> {
    const operation = 'findPaginated';
    const correlationId =
      options?.correlationId ??
      CorrelationUtil.generateForOperation('lookup-type-query-paginated');

    const logContext = this.createLogContext(operation, correlationId, actor, {
      filterName: filter?.name,
      filterCode: filter?.code,
      page: filter?.page,
      size: filter?.size,
      sortBy: filter?.getSortByRecord?.() || {},
      dataSource: 'redis-projector',
    });

    // Validate actor context with enhanced security logging
    const validation = RepositoryLoggingUtil.validateActorContext(
      this.logger,
      actor,
      logContext,
    );
    if (!validation.ok) return err(validation.error);

    // Guard tenant explicitly
    if (!actor.tenant) {
      return err(
        RepositoryErrorFactory.validationError('tenant', 'Missing tenant id'),
      );
    }

    // Log successful authorization
    RepositoryLoggingUtil.logAuthorizationSuccess(
      this.logger,
      operation,
      logContext,
      {
        operationType: 'lookup-type_query_paginated',
        scope: 'redis_projection_search',
        tenant: actor.tenant,
      },
    );

    try {
      const page = filter?.page ?? 1;
      const size = Math.min(filter?.size ?? 20, 100); // Cap at 100 items per page

      // Generate the proper Redis key pattern using centralized LookupTypeProjectionKeys
      const pattern = LookupTypeProjectionKeys.getRedisTenantLookupTypePattern(
        actor.tenant,
      );

      Log.debug(this.logger, 'Scanning Redis for tenant lookup-types', {
        ...logContext,
        queryDetails: {
          scope: 'redis_scan',
          method: 'redis.scan',
          pattern,
          clusterSafe: true,
        },
      });

      // Use Redis SCAN to find all lookup-type keys for the tenant
      const lookupTypeKeys: string[] = [];
      const scanIterator = this.redis.scanStream({
        match: pattern,
        count: 1000, // Batch size for scanning
      });

      for await (const keys of scanIterator) {
        lookupTypeKeys.push(...(keys as string[]));
      }

      if (lookupTypeKeys.length === 0) {
        // No lookup-types found for tenant
        const meta = new PaginationMetaResponse({
          page,
          size,
          totalItems: 0,
          totalPages: 0,
          hasNextPage: false,
          hasPreviousPage: false,
        });

        const response = LookupTypePageResponse.create([], meta);

        Log.debug(this.logger, 'No lookup-types found for tenant', {
          ...logContext,
          totalItems: 0,
        });

        return ok(response);
      }

      // Batch fetch all lookup-type hashes using pipeline for efficiency
      const pipeline = this.redis.pipeline();
      lookupTypeKeys.forEach((key) => {
        pipeline.hgetall(key);
      });

      const results = await pipeline.exec();

      if (!results) {
        throw new Error('Redis pipeline execution failed');
      }

      // Parse all lookup-types from Redis hashes
      const allLookupTypes: LookupTypeCacheData[] = [];
      for (let i = 0; i < results.length; i++) {
        const [error, hashData] = results[i];
        if (!error && hashData) {
          const lookupType = this.parseRedisHashToLookupType(
            hashData as Record<string, string>,
          );
          if (lookupType) {
            allLookupTypes.push(lookupType);
          }
        }
      }

      // Apply client-side filtering
      const filteredLookupTypes = allLookupTypes.filter((lookupType) =>
        this.matchesFilter(lookupType, filter),
      );

      // Apply client-side sorting
      const sortedLookupTypes = this.sortLookupTypes(
        filteredLookupTypes,
        filter?.getSortByRecord?.(),
      );

      // Calculate pagination metadata
      const totalItems = sortedLookupTypes.length;
      const totalPages = Math.ceil(totalItems / size);
      const hasNextPage = page < totalPages;
      const hasPreviousPage = page > 1;

      // Apply pagination
      const startIndex = (page - 1) * size;
      const endIndex = startIndex + size;
      const paginatedLookupTypes = sortedLookupTypes.slice(
        startIndex,
        endIndex,
      );

      // Transform to DTOs
      const lookupTypeResponses = paginatedLookupTypes.map((lookupType) =>
        this.toListResponse(lookupType),
      );

      const meta = new PaginationMetaResponse({
        page,
        size,
        totalItems,
        totalPages,
        hasNextPage,
        hasPreviousPage,
      });

      const response = LookupTypePageResponse.create(lookupTypeResponses, meta);

      // Log successful query metrics
      RepositoryLoggingUtil.logQueryMetrics(
        this.logger,
        operation,
        logContext,
        {
          resultCount: paginatedLookupTypes.length,
          dataQuality: paginatedLookupTypes.length > 0 ? 'good' : 'empty',
          sampleData: {
            totalItems,
            totalKeysScanned: lookupTypeKeys.length,
            filteredCount: filteredLookupTypes.length,
            page,
            size,
            hasFilters: !!(filter?.name || filter?.code),
            sortFields: Object.keys(filter?.getSortByRecord?.() ?? {}),
          },
        },
      );

      return ok(response);
    } catch (error) {
      // Log operation error using shared utility
      RepositoryLoggingUtil.logOperationError(
        this.logger,
        operation,
        logContext,
        error as Error,
        'HIGH',
      );

      // Handle and return the classified error using shared utility
      return handleRepositoryError(error);
    }
  }
}
