// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import type { MessageRequestStatusValue } from '../value-objects';
/**
 * MessageRequest Created Event Payload
 * Contains only business facts - no envelope metadata, timestamps, or versioning
 */
export interface MessageRequestCreatedEventPayload {
  id: string;
  workspaceId: string;
  templateCode: string;
  recipient?: string;
  data?: Record<string, unknown>;
  status?: MessageRequestStatusValue;
}

/**
 * MessageRequest Created Domain Event
 *
 * Emitted when a new messageRequest is successfully created.
 * Contains complete messageRequest information and creation metadata.
 * Enhanced with security metadata and PII protection capabilities.
 */
export class MessageRequestCreatedEvent {
  public readonly eventType =
    'NotificationSlackRequestMessageRequestCreated.v1';
  public readonly eventVersion = 'v1';

  constructor(public readonly payload: MessageRequestCreatedEventPayload) {}

  // Factory method - no metadata needed, just business data
  static create(
    data: MessageRequestCreatedEventPayload,
  ): MessageRequestCreatedEvent {
    return new MessageRequestCreatedEvent(data);
  }

  get id(): string {
    return this.payload.id;
  }

  get workspaceId(): string {
    return this.payload.workspaceId;
  }

  get templateCode(): string {
    return this.payload.templateCode;
  }

  get recipient(): string | undefined {
    return this.payload.recipient;
  }

  get data(): Record<string, unknown> | undefined {
    return this.payload.data;
  }

  get status(): MessageRequestStatusValue | undefined {
    return this.payload.status;
  }
}
