// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Module } from '@nestjs/common';

// Import shared infrastructure
import { SlackConfigSharedModule } from './slack-config-shared.module';

// Import all slack-config domain modules
import { WorkspaceRouterModule } from './workspace/interface/http/workspace.router';

import { WorkspaceProjectorModule } from './workspace/workspace-projector.module';
import { ChannelRouterModule } from './channel/interface/http/channel.router';

import { ChannelProjectorModule } from './channel/channel-projector.module';
import { TemplateRouterModule } from './template/interface/http/template.router';

import { TemplateProjectorModule } from './template/template-projector.module';
import { ConfigRouterModule } from './config/interface/http/config.router';

import { ConfigProjectorModule } from './config/config-projector.module';

/**
 * SlackConfig Module - Bounded Context Entry Point
 *
 * This module serves as the single entry point for the entire slack-config bounded context.
 * It aggregates all domain modules and their corresponding projector modules, providing
 * a clean separation between the app module and domain-specific concerns.
 *
 * Architecture Benefits:
 * - Single import in app.module.ts instead of individual domain modules
 * - Clear bounded context boundaries
 * - Easier management of domain module dependencies
 * - Consistent projector module organization
 *
 * Each domain includes both:
 * - Domain Module: Commands, queries, business logic
 * - Projector Module: Read-side projections and event handling
 */
@Module({
  imports: [
    // Shared infrastructure (imported once for all domains)
    SlackConfigSharedModule,
    WorkspaceRouterModule,
    WorkspaceProjectorModule,
    ChannelRouterModule,
    ChannelProjectorModule,
    TemplateRouterModule,
    TemplateProjectorModule,
    ConfigRouterModule,
    ConfigProjectorModule,
  ],
  exports: [
    // Export all modules for potential cross-domain dependencies
    WorkspaceRouterModule,
    WorkspaceProjectorModule,
    ChannelRouterModule,
    ChannelProjectorModule,
    TemplateRouterModule,
    TemplateProjectorModule,
    ConfigRouterModule,
    ConfigProjectorModule,
  ],
})
export class NotificationSlackConfigModule {}
