// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { Module } from '@nestjs/common';

// Import shared infrastructure
import { SlackConfigSharedModule } from './slack-config-shared.module';

// Import all slack-config domain modules
import { WorkspaceModule } from './workspace/workspace.module';
import { WorkspaceProjectorModule } from './workspace/workspace-projector.module';

/**
 * Product Config Module - Bounded Context Entry Point
 *
 * This module serves as the single entry point for the entire slack-config bounded context.
 * It aggregates all domain modules and their corresponding projector modules, providing
 * a clean separation between the app module and domain-specific concerns.
 *
 * Architecture Benefits:
 * - Single import in app.module.ts instead of individual domain modules
 * - Clear bounded context boundaries
 * - Easier management of domain module dependencies
 * - Consistent projector module organization
 *
 * Each domain includes both:
 * - Domain Module: Commands, queries, business logic
 * - Projector Module: Read-side projections and event handling
 */
@Module({
  imports: [
    // Shared infrastructure (imported once for all domains)
    SlackConfigSharedModule,
    WorkspaceModule,
    WorkspaceProjectorModule,
  ],
  exports: [
    // Export all modules for potential cross-domain dependencies
    WorkspaceModule,
    WorkspaceProjectorModule,
  ],
})
export class NotificationSlackConfigModule {}
