// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsOptional, IsNotEmpty } from 'class-validator';
import {
  AttributeRuleTypeValues,
  AttributeRuleTypeValue,
} from '../../../../domain/value-objects';

export { AttributeRuleTypeValues, AttributeRuleTypeValue };
/**
 * Options for property decorators (enum)
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for AttributeRule Type with required option
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiAttributeRuleType(options: PropOptions = {}) {
  const { required = true } = options;
  return applyDecorators(
    ApiProperty({
      description: `Data type classification for the attribute field. Determines validation logic, storage format, and UI input controls to be used for this attribute. Values include string, boolean, integer, currency, date, datetime, other.`,
      example: `string`,
      type: String,
      enum: AttributeRuleTypeValues,
      required,
    }),
    IsEnum(AttributeRuleTypeValues),
    required ? IsNotEmpty() : IsOptional(),
  );
}
