// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { UpdateOptionsProps } from '../../../domain/props';
import { ApiOptionsName } from './../decorators//options';

export class UpdateOptionsRequest implements UpdateOptionsProps {
  @ApiOptionsName()
  name?: string;
}
