// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { LookupXxxSnapshotProps } from '../../domain/props';
import { DetailLookupXxxResponse } from '../dtos';

/**
 * LookupXxx Snapshot to DTO Mappers
 * Reusable mapping functions for converting domain snapshots to DTOs
 */

/**
 * Map lookupXxx snapshot to DTO response
 */
export const mapLookupXxxSnapshotToDto = (
  snapshot: LookupXxxSnapshotProps,
): DetailLookupXxxResponse => {
  return {
    lookupType: snapshot.lookupType,
    code: snapshot.code,
    name: snapshot.name,
    description: snapshot.description,
    enabled: snapshot.enabled,
    attributes: snapshot.attributes,
  };
};
