// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  ApiLookupXxxAttributes,
  ApiLookupXxxDescription,
  ApiLookupXxxEnabled,
  ApiLookupXxxName,
} from './decorators';

export class UpdateLookupXxxRequest {
  @ApiLookupXxxName({ required: false })
  name?: string;

  @ApiLookupXxxDescription({ required: false })
  description?: string;

  @ApiLookupXxxEnabled({ required: false })
  enabled?: boolean;

  @ApiLookupXxxAttributes({ required: false })
  attributes?: Record<string, unknown>;
}
