// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

/**
 * TypeORM Migration: CreateAppConfigsTable
 *
 * ARCHITECTURE OVERVIEW:
 * This migration creates a read model table for the AppConfig domain.
 *
 * EVENT SOURCING ARCHITECTURE:
 * - EventStoreDB serves as the source of truth for all domain events
 * - This PostgreSQL table acts as a read model projection for query optimization
 * - Data flows: EventStoreDB -> Projector -> PostgreSQL Read Model
 *
 * PROJECTION STRATEGY:
 * - Events from EventStoreDB are projected into this table by domain projectors
 * - The projector handles event replay and real-time projection updates
 * - This table should only be modified through the projection process
 *
 * PERFORMANCE CONSIDERATIONS:
 * - Indexes are optimized for multi-tenant query patterns
 * - JSONB columns provide flexible storage for complex domain data
 * - Composite indexes support efficient filtering and sorting operations
 */

import { MigrationInterface, QueryRunner } from 'typeorm';

// 0 ms → 1970-01-01 00:00:00 UTC
// CREATE TABLE IF NOT EXISTS "app_configs" (

export class CreateAppConfigsTable0000000000002 implements MigrationInterface {
  name = 'CreateAppConfigsTable0000000000002';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "slack_config"."app_configs" (
        "id" INTEGER NOT NULL,
        "workspace_id" VARCHAR(64) NOT NULL,
        "max_retry_attempts" INTEGER NOT NULL,
        "retry_backoff_seconds" INTEGER NOT NULL,
        "default_locale" VARCHAR(16) NOT NULL,
        "logging_enabled" BOOLEAN NOT NULL,
        "audit_channel_id" VARCHAR(64),
        "metadata" JSONB,
        "tenant_id" VARCHAR(100) NOT NULL,
        "version" INTEGER NOT NULL DEFAULT 0,
        "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
        "deleted_at" TIMESTAMP,
        "last_stream_revision" VARCHAR(50),
        PRIMARY KEY ("tenant_id", "id")
      );
    `);

    // Create performance indexes for multi-tenant architecture
    await queryRunner.query(`
      CREATE INDEX "idx_app_configs_tenant_id" ON "slack_config"."app_configs" ("tenant_id");
    `);

    await queryRunner.query(`
      CREATE INDEX "idx_app_configs_created_at" ON "slack_config"."app_configs" ("created_at");
    `);

    await queryRunner.query(`
      CREATE INDEX "idx_app_configs_updated_at" ON "slack_config"."app_configs" ("updated_at");
    `);

    // Add unique constraints if needed

    // Add table comment for documentation
    await queryRunner.query(`
      COMMENT ON TABLE "slack_config"."app_configs" IS 'Read model projection for AppConfig domain. Source of truth: EventStoreDB. Updated via domain projectors.';
    `);

    // Add column comments for better documentation
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."id" IS 'Auto-incrementing primary key for app configuration records. Each workspace typically has one configuration record.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."workspace_id" IS 'Foreign key reference to the workspace these operational settings apply to. Allows per-workspace customization of retry logic and behavior.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."max_retry_attempts" IS 'Maximum number of retry attempts for failed message deliveries before marking as permanently failed. Higher values increase reliability but consume more resources.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."retry_backoff_seconds" IS 'Initial delay in seconds between retry attempts. Actual delay may use exponential backoff strategy to avoid overwhelming Slack API rate limits.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."default_locale" IS 'Default language/locale for message content when user-specific locale is not available. Follows ISO 639-1 language codes combined with ISO 3166-1 country codes.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."logging_enabled" IS 'Controls whether detailed message delivery logs are recorded for audit and debugging purposes. Essential for compliance and troubleshooting failed deliveries.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."audit_channel_id" IS 'Optional dedicated channel for system operational logs, error reports, and delivery confirmations. Separate from business notification channels for administrative clarity.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."metadata" IS 'Flexible JSON object for storing additional workspace-specific configuration options, feature flags, and custom settings that don't warrant dedicated columns.';
    `);

    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."tenant_id" IS 'Multi-tenant isolation key - identifies which tenant this channel belongs to.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."version" IS 'Aggregate version for optimistic concurrency control and event ordering.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."deleted_at" IS 'Soft delete timestamp - NULL means active channel, non-NULL means logically deleted.';
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN "slack_config"."app_configs"."last_stream_revision" IS 'EventStore stream revision for idempotency and duplicate event detection.';
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "slack_config"."app_configs"`);
  }
}
