// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  WebhookCreatedAt,
  WebhookUpdatedAt,
  WebhookVersion,
  WebhookConnectTimeoutMs,
  WebhookDescription,
  WebhookEventType,
  WebhookHeaders,
  WebhookId,
  WebhookMethod,
  WebhookName,
  WebhookRateLimitPerMinute,
  WebhookRequestTimeoutMs,
  WebhookSigningSecretRef,
  WebhookStatus,
  WebhookTargetUrl,
  WebhookVerifyTls,
} from '../value-objects';

/**
 * Webhook Domain State
 *
 * Domain state interface that uses value objects to model business concepts
 * while maintaining compatibility with entity operations. Business fields are
 * modeled as value objects with proper validation and domain rules.
 *
 * Domain-First State Interface
 *
 * This interface represents the domain model where business concepts
 * are properly encapsulated as value objects when appropriate.
 */

export interface WebhookDomainState {
  id: WebhookId;
  name: WebhookName;
  description?: WebhookDescription;
  targetUrl: WebhookTargetUrl;
  eventType: WebhookEventType;
  method: WebhookMethod;
  headers?: WebhookHeaders;
  signingSecretRef?: WebhookSigningSecretRef;
  status: WebhookStatus;
  verifyTls?: WebhookVerifyTls;
  requestTimeoutMs?: WebhookRequestTimeoutMs;
  connectTimeoutMs?: WebhookConnectTimeoutMs;
  rateLimitPerMinute?: WebhookRateLimitPerMinute;
  version: WebhookVersion;
  createdAt: WebhookCreatedAt;
  updatedAt: WebhookUpdatedAt;
}

export type WebhookDomainStateOptional = Partial<WebhookDomainState>;
