// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { TemplateProps } from './template.props';

export interface TemplateSnapshotProps extends TemplateProps {
  createdAt: Date;
  updatedAt: Date;
  version: number;
}
