// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsOptional, IsNotEmpty } from 'class-validator';

/**
 * Options for property decorators (boolean)
 */
interface PropOptions {
  required?: boolean;
}

/**
 * Property decorator for Rule Unique
 * @param {Object} options - Options for the decorator
 * @returns {PropertyDecorator}
 */
export function ApiRuleUnique(options: PropOptions = {}) {
  const { required = false } = options;

  return applyDecorators(
    ApiProperty({
      description: `Enforces uniqueness constraint across all entities using this attribute. When true, duplicate values will be rejected with validation error.`,
      example: true,
      type: Boolean,
      required,
    }),
    IsBoolean(),
    required ? IsNotEmpty() : IsOptional(),
  );
}
