// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { MessageRequestErrors } from '../errors/message-request.errors';

/**
 * ChannelCode Value Object
 * Represents a validated channelCode with business rules
 */
export const MessageRequestChannelCode = createStringVO({
  name: 'ChannelCode',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,
  minLength: 10,
  maxLength: 32,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(
    MessageRequestErrors.INVALID_CHANNEL_CODE,
    'ChannelCode',
  ),
});

/**
 * Public instance type for ChannelCode
 */
export type MessageRequestChannelCode = StringVOInstance;

// Convenience creators
export const createMessageRequestChannelCode = (s: string) =>
  MessageRequestChannelCode.create(s);
export const messageRequestChannelCodeFrom = (v: unknown) =>
  MessageRequestChannelCode.from(v);
