// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { MessageRequestErrors } from '../errors/message-request.errors';

/**
 * WorkspaceId Value Object
 * Represents a validated workspaceId with business rules
 */
export const MessageRequestWorkspaceId = createStringVO({
  name: 'WorkspaceId',
  trim: true,
  caseTransform: 'none',
  allowEmpty: false,

  maxLength: 64,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(
    MessageRequestErrors.INVALID_WORKSPACE_ID,
    'WorkspaceId',
  ),
});

/**
 * Public instance type for WorkspaceId
 */
export type MessageRequestWorkspaceId = StringVOInstance;

// Convenience creators
export const createMessageRequestWorkspaceId = (s: string) =>
  MessageRequestWorkspaceId.create(s);
export const messageRequestWorkspaceIdFrom = (v: unknown) =>
  MessageRequestWorkspaceId.from(v);
