// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { AppConfigSnapshotProps } from '../../domain/props';
import { DetailAppConfigResponse } from '../dtos';

/**
 * AppConfig Snapshot to DTO Mappers
 * Reusable mapping functions for converting domain snapshots to DTOs
 */

/**
 * Map appConfig snapshot to DTO response
 */
export const mapAppConfigSnapshotToDto = (
  snapshot: AppConfigSnapshotProps,
): DetailAppConfigResponse => {
  return {
    workspaceCode: snapshot.workspaceCode,
    maxRetryAttempts: snapshot.maxRetryAttempts,
    retryBackoffSeconds: snapshot.retryBackoffSeconds,
    defaultLocale: snapshot.defaultLocale,
    loggingEnabled: snapshot.loggingEnabled,
    auditChannelId: snapshot.auditChannelId,
    metadata: snapshot.metadata,
  };
};
