// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

/**
 * Application Port for Request outcome reporting
 *
 * Allows the executor (worker) to report delivery outcomes back to the
 * Request bounded context via clean application layer interfaces.
 */
export interface IRequestAppPort {
  /**
   * Record successful message delivery
   */
  recordSent(input: {
    code: string; // requestId
    attempts: number;
    tenant?: string;
    correlationId?: string;
    causationId?: string;
  }): Promise<void>;

  /**
   * Record failed message delivery
   */
  recordFailed(input: {
    code: string;
    reason: string; // normalized error code (e.g., 'invalid_auth')
    attempts: number;
    retryable?: boolean;
    lastError?: string;
    tenant?: string;
    correlationId?: string;
    causationId?: string;
  }): Promise<void>;
}

/**
 * DI Token for the Request Application Port
 */
export const REQUEST_APP_PORT = Symbol('REQUEST_APP_PORT');
