// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { RuleErrors } from '../../errors/rule.errors';

/**
 * Description Value Object
 * Represents a validated description with business rules
 */
export const RuleDescription = createStringVO({
  name: 'Description',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(RuleErrors.INVALID_DESCRIPTION, 'Description'),
});

/**
 * Public instance type for Description
 */
export type RuleDescription = StringVOInstance;

// Convenience creators
export const createRuleDescription = (s: string) => RuleDescription.create(s);
export const ruleDescriptionFrom = (v: unknown) => RuleDescription.from(v);
