// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { RuleErrors } from '../../errors/rule.errors';

/**
 * UniqueError Value Object
 * Represents a validated uniqueError with business rules
 */
export const RuleUniqueError = createStringVO({
  name: 'UniqueError',
  trim: true,
  caseTransform: 'none',
  allowEmpty: true,

  maxLength: 255,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(RuleErrors.INVALID_UNIQUE_ERROR, 'UniqueError'),
});

/**
 * Public instance type for UniqueError
 */
export type RuleUniqueError = StringVOInstance;

// Convenience creators
export const createRuleUniqueError = (s: string) => RuleUniqueError.create(s);
export const ruleUniqueErrorFrom = (v: unknown) => RuleUniqueError.from(v);
