// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  StringVOInstance,
  createStringVO,
  createStringVOErrors,
} from 'src/shared/domain/value-objects';
import { LookupXxxErrors } from '../errors/lookup-xxx.errors';

/**
 * LookupType Value Object
 * Represents a validated lookupType with business rules
 */
export const LookupXxxLookupType = createStringVO({
  name: 'LookupType',
  trim: true,
  caseTransform: 'none',
  allowEmpty: false,

  maxLength: 64,

  // Optional: declarative refinements for advanced validation
  // refinements: [
  // ],

  errors: createStringVOErrors(
    LookupXxxErrors.INVALID_LOOKUP_TYPE,
    'LookupType',
  ),
});

/**
 * Public instance type for LookupType
 */
export type LookupXxxLookupType = StringVOInstance;

// Convenience creators
export const createLookupXxxLookupType = (s: string) =>
  LookupXxxLookupType.create(s);
export const lookupXxxLookupTypeFrom = (v: unknown) =>
  LookupXxxLookupType.from(v);
