// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  ConfigAuditChannelId,
  ConfigDefaultLocale,
  ConfigLoggingEnabled,
  ConfigMaxRetryAttempts,
  ConfigMetadata,
  ConfigRetryBackoffSeconds,
  ConfigWorkspaceCode,
} from '../value-objects';

export interface ValidatedConfigUpdateFields {
  workspaceCode?: ConfigWorkspaceCode;
  maxRetryAttempts?: ConfigMaxRetryAttempts;
  retryBackoffSeconds?: ConfigRetryBackoffSeconds;
  defaultLocale?: ConfigDefaultLocale;
  loggingEnabled?: ConfigLoggingEnabled;
  auditChannelId?: ConfigAuditChannelId;
  metadata?: ConfigMetadata;
}
