// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import {
  IntegerVOInstance,
  createIntegerVO,
  createIntegerVOErrors,
} from 'src/shared/domain/value-objects';
import { ConfigErrors } from '../errors/config.errors';

/**
 * DlqMaxAgeSeconds Integer Value Object
 * Validates whole numbers.
 *
 * Integer VO Refinements (commented examples):
 *
 * Age validation:
 * - Range validation: { minValue: 0, maxValue: 150 }
 * - Non-negative: { nonNegative: true }
 *
 * Quantity/Count validation:
 * - Inventory count: { minValue: 0, maxValue: 999999 }
 * - Zero-allowed quantity: { minValue: 0 }
 *
 * ID/Sequence validation:
 * - Primary key: { minValue: 1 }
 * - Positive integer only: { minValue: 1 }
 *
 * Score/Rating validation:
 * - Percentage score: { minValue: 0, maxValue: 100 }
 * - Star rating: { minValue: 1, maxValue: 5 }
 */
export const ConfigDlqMaxAgeSeconds = createIntegerVO({
  name: 'DlqMaxAgeSeconds',

  errors: createIntegerVOErrors(
    ConfigErrors.INVALID_DLQ_MAX_AGE_SECONDS,
    'DlqMaxAgeSeconds',
  ),
});

/** Public instance type for DlqMaxAgeSeconds */
export type ConfigDlqMaxAgeSeconds = IntegerVOInstance;

// Convenience creators
export const createConfigDlqMaxAgeSeconds = (v: number) =>
  ConfigDlqMaxAgeSeconds.create(v);
export const configDlqMaxAgeSecondsFrom = (v: unknown) =>
  ConfigDlqMaxAgeSeconds.from(v);
