// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

/**
 * Channel Application Service
 *
 * Application-layer service that coordinates authorization with business operations.
 */

// Framework imports
import { Inject, Injectable } from '@nestjs/common';

// Shared utilities and infrastructure
import { APP_LOGGER, Log, componentLogger, Logger } from 'src/shared/logging';
import { Result, DomainError, err, ok, withContext } from 'src/shared/errors';
import type { IUserToken } from 'src/shared/security';
import { CorrelationUtil } from 'src/shared/utilities/correlation.util';
import { Clock, CLOCK } from 'src/shared/infrastructure/time';

// Service configuration
import { SlackExecuteServiceConstants } from '../../../service-constants';

// Domain types and errors
import { ChannelErrors } from '../../domain/errors/channel.errors';
import type {
  CreateChannelProps,
  UpdateChannelProps,
} from '../../domain/props';
import { DetailChannelResponse } from '../dtos';

// Application layer
import { ChannelAuthorizationService } from './channel-authorization.service';
import { ChannelAuthContext } from '../types/channel-auth-context';

// Use case contracts
import {
  IUpsertChannelUseCase,
  IGetChannelUseCase,
} from '../use-cases/contracts';

/**
 * Application Service for Channel operations with integrated authorization
 */
@Injectable()
export class ChannelApplicationService {
  private readonly logger: Logger;

  constructor(
    private readonly channelAuthorizationService: ChannelAuthorizationService,
    private readonly upsertChannelUseCase: IUpsertChannelUseCase,
    private readonly getChannelUseCase: IGetChannelUseCase,
    @Inject(CLOCK) private readonly clock: Clock,
    @Inject(APP_LOGGER) moduleLogger: Logger,
  ) {
    this.logger = componentLogger(moduleLogger, 'ChannelApplicationService');
  }

  /**
   * Helper to create ChannelAuthContext from user token
   */
  private createAuthContext(
    user: IUserToken,
    operation: string,
  ): ChannelAuthContext {
    return {
      tenantId: user.tenant_id,
      roles: user.roles || [],
      operationType: operation,
      metadata: {
        userId: user.sub,
        timestamp: this.clock.nowIso(),
      },
    };
  }

  /**
   * Helper to create consistent logging context
   */
  private createLogContext(
    operation: string,
    correlationId: string,
    userId: string,
    additionalContext?: Record<string, unknown>,
  ): Record<string, unknown> {
    return {
      serviceName: SlackExecuteServiceConstants.SERVICE_NAME,
      component: 'ChannelApplicationService',
      operation,
      correlationId,
      userId,
      ...additionalContext,
    };
  }

  /**
   * Helper to validate required id input
   */
  private validateId(
    id: string,
    operation: string,
    correlationId?: string,
  ): Result<string, DomainError> {
    if (!id?.trim()) {
      return err(
        withContext(ChannelErrors.INVALID_CHANNEL_DATA, {
          operation,
          correlationId:
            correlationId ||
            CorrelationUtil.generateForOperation(`channel-${operation}`),
        }),
      );
    }
    return ok(id.trim());
  }

  /**
   * Centralized auth → log → execute → catch pattern
   */
  private async authorizeThenExecute<T>(args: {
    operation: 'create' | 'update' | 'read';
    user: IUserToken;
    id?: string;
    correlationIdPrefix: string;
    doAuthorize: () => Promise<Result<boolean, DomainError>>;
    doExecute: () => Promise<Result<T, DomainError>>;
    logContext?: Record<string, unknown>;
  }): Promise<Result<T, DomainError>> {
    const corrId = CorrelationUtil.generateForOperation(
      args.correlationIdPrefix,
    );
    const ctx = {
      ...this.createLogContext(
        `${args.operation}_channel`,
        corrId,
        args.user.sub,
        args.logContext,
      ),
    };

    const auth = await args.doAuthorize();
    if (!auth.ok) {
      Log.warn(this.logger, `${args.operation} authorization failed`, {
        ...ctx,
        authDecision: 'deny',
      });
      return err(auth.error);
    }
    if (!auth.value) {
      Log.warn(this.logger, `${args.operation} permission denied`, {
        ...ctx,
        authDecision: 'deny',
      });
      return err(
        withContext(ChannelErrors.PERMISSION_DENIED, {
          correlationId: corrId,
          userId: args.user.sub,
          operation: args.operation,
          id: args.id,
          category: 'security',
        }),
      );
    }

    Log.info(this.logger, `Channel ${args.operation} authorized`, {
      ...ctx,
      authDecision: 'allow',
    });

    try {
      return await args.doExecute();
    } catch (error) {
      Log.error(this.logger, `Channel ${args.operation} use case failed`, {
        ...ctx,
        error: error instanceof Error ? error.message : String(error),
      });
      return err({
        code: `DOMAIN.CHANNEL.${args.operation.toUpperCase()}_FAILED`,
        title: `Channel ${args.operation} failed`,
        detail: error instanceof Error ? error.message : 'Unknown error',
        category: 'application',
        context: {
          correlationId: corrId,
          id: args.id,
          operation: `${args.operation}_channel`,
        },
      });
    }
  }

  /**
   * Create a new channel with authorization
   */
  async createChannel(
    user: IUserToken,
    props: CreateChannelProps,
    options?: { idempotencyKey?: string; correlationId?: string },
  ): Promise<Result<DetailChannelResponse, DomainError>> {
    const authContext = this.createAuthContext(user, 'create');
    const correlationId =
      options?.correlationId ||
      CorrelationUtil.generateForOperation('channel-create');

    return this.authorizeThenExecute<DetailChannelResponse>({
      operation: 'create',
      user,
      correlationIdPrefix: 'channel-create',
      doAuthorize: () =>
        this.channelAuthorizationService.canCreateChannel(
          user.sub,
          correlationId,
          authContext,
        ),
      doExecute: () =>
        this.upsertChannelUseCase.execute({
          user,
          id: props.id,
          props,
          correlationId,
          authorizationReason: 'create_channel',
          ...(options?.idempotencyKey && {
            idempotencyKey: options.idempotencyKey,
          }),
        }),
    });
  }

  /**
   * Update an existing channel with authorization
   */
  async updateChannel(
    user: IUserToken,
    id: string,
    props: UpdateChannelProps,
    options?: { idempotencyKey?: string; correlationId?: string },
  ): Promise<Result<DetailChannelResponse, DomainError>> {
    // Early input validation
    const idValidation = this.validateId(id, 'update');
    if (!idValidation.ok) {
      return err(idValidation.error);
    }

    const validatedid = idValidation.value;
    const authContext = this.createAuthContext(user, 'update');
    const correlationId =
      options?.correlationId ||
      CorrelationUtil.generateForOperation('channel-update');

    // Optional: Field-level authorization
    // Uncomment when ChannelAuthorizationService supports authorizeChannelOperation
    /*
    const fields = extractDefinedFields(props); // Use shared utility
    const opAuth = await this.channelAuthorizationService.authorizeChannelOperation(
      user.sub, 
      'update', 
      CorrelationUtil.generateForOperation('channel-update'), 
      validatedid, 
      fields, 
      authContext
    );
    if (!opAuth.ok) return err(opAuth.error);
    if (!opAuth.value.authorized) {
      return err(withContext(ChannelErrors.PERMISSION_DENIED, { 
        operation: 'update', 
        id: validatedid, 
        userId: user.sub,
        category: 'security'
      }));
    }
    */

    return this.authorizeThenExecute<DetailChannelResponse>({
      operation: 'update',
      user,
      id: validatedid,
      correlationIdPrefix: 'channel-update',
      doAuthorize: () =>
        this.channelAuthorizationService.canUpdateChannel(
          user.sub,
          validatedid,
          correlationId,
          authContext,
        ),
      doExecute: () =>
        this.upsertChannelUseCase.execute({
          user,
          id: validatedid,
          props,
          correlationId,
          authorizationReason: 'update_channel',
          ...(options?.idempotencyKey && {
            idempotencyKey: options.idempotencyKey,
          }),
        }),
      logContext: { id: validatedid },
    });
  }

  /**
   * Get a channel by ID with authorization
   */
  async getChannelById(
    user: IUserToken,
    id: string,
  ): Promise<Result<DetailChannelResponse, DomainError>> {
    // Early input validation
    const idValidation = this.validateId(id, 'read');
    if (!idValidation.ok) {
      return err(idValidation.error);
    }

    const validatedid = idValidation.value;
    const authContext = this.createAuthContext(user, 'read');

    return this.authorizeThenExecute<DetailChannelResponse>({
      operation: 'read',
      user,
      id: validatedid,
      correlationIdPrefix: 'channel-read',
      doAuthorize: () =>
        this.channelAuthorizationService.canReadChannel(
          user.sub,
          validatedid,
          CorrelationUtil.generateForOperation('channel-read'),
          authContext,
        ),
      doExecute: () =>
        this.getChannelUseCase.execute({
          user,
          id: validatedid,
          correlationId: CorrelationUtil.generateForOperation('channel-read'),
        }),
      logContext: { id: validatedid },
    });
  }
}
