// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import type {
  ConfigOrderingValue,
  ConfigRetryStrategyValue,
  ConfigSignatureAlgorithmValue,
} from '../../domain/value-objects';
import { CreateConfigProps } from '../../domain/props';
import {
  ApiConfigBackoffJitterPct,
  ApiConfigConnectTimeoutMs,
  ApiConfigDefaultLocale,
  ApiConfigDlqEnabled,
  ApiConfigDlqMaxAgeSeconds,
  ApiConfigIncludeTimestampHeader,
  ApiConfigMaxConcurrent,
  ApiConfigMaxRetryAttempts,
  ApiConfigMetadata,
  ApiConfigOrdering,
  ApiConfigRateLimitPerMinute,
  ApiConfigRequestTimeoutMs,
  ApiConfigRetryBackoffSeconds,
  ApiConfigRetryStrategy,
  ApiConfigSignatureAlgorithm,
  ApiConfigWebhookId,
} from './decorators';

export class CreateConfigRequest implements CreateConfigProps {
  @ApiConfigWebhookId()
  webhookId: string;

  @ApiConfigRateLimitPerMinute({ required: false })
  rateLimitPerMinute?: number;

  @ApiConfigMaxRetryAttempts()
  maxRetryAttempts: number;

  @ApiConfigRetryBackoffSeconds()
  retryBackoffSeconds: number;

  @ApiConfigRetryStrategy({ required: false })
  retryStrategy?: ConfigRetryStrategyValue;

  @ApiConfigBackoffJitterPct({ required: false })
  backoffJitterPct?: number;

  @ApiConfigRequestTimeoutMs({ required: false })
  requestTimeoutMs?: number;

  @ApiConfigConnectTimeoutMs({ required: false })
  connectTimeoutMs?: number;

  @ApiConfigSignatureAlgorithm({ required: false })
  signatureAlgorithm?: ConfigSignatureAlgorithmValue;

  @ApiConfigIncludeTimestampHeader({ required: false })
  includeTimestampHeader?: boolean;

  @ApiConfigMaxConcurrent({ required: false })
  maxConcurrent?: number;

  @ApiConfigDlqEnabled({ required: false })
  dlqEnabled?: boolean;

  @ApiConfigDlqMaxAgeSeconds({ required: false })
  dlqMaxAgeSeconds?: number;

  @ApiConfigOrdering({ required: false })
  ordering?: ConfigOrderingValue;

  @ApiConfigDefaultLocale()
  defaultLocale: string;

  @ApiConfigMetadata({ required: false })
  metadata?: Record<string, unknown>;
}
