// @generated by gen v1.0.0 hash:regen
// REMOVE THIS COMMENT TO STOP AUTOMATIC UPDATES TO THIS BLOCK

import { AggregateRootBase } from 'src/shared/domain/aggregates';
import { DomainEvent, EventMetadata } from 'src/shared/domain/events';
import { DomainError, Result, ok, err } from 'src/shared/errors';
import { Clock } from 'src/shared/domain/clock';
import { hasValueChanged } from 'src/shared/utilities';
import { WebhookEntity } from '../entities';
import { WebhookSnapshotProps } from '../props';
import { ValidatedWebhookUpdateFields } from '../types';
import {
  WebhookId,
  WebhookMethodValue,
  createWebhookMethod,
  WebhookStatusValue,
  createWebhookStatus,
  createWebhookCreatedAt,
  createWebhookUpdatedAt,
  createdAtNow,
  updatedAtNow,
  validateMonotonicTime,
  bumpVersion,
  initialVersion,
  createWebhookVersion,
  WebhookVersion,
} from '../value-objects';
import { WebhookCreatedEvent, WebhookUpdatedEvent } from '../events';
import { WebhookErrors } from '../errors';
import { WebhookDomainState } from '../state';

/**
 * Domain Aggregate Root: Webhook
 *
 * Represents the Webhook aggregate root in the notification domain.
 * Encapsulates webhook business logic, state management, and domain invariants.
 *
 * This aggregate follows DDD principles:
 * - Aggregate Root: Central entity that controls access to the aggregate
 * - Consistency Boundary: Ensures all business rules are enforced
 * - Domain Events: Publishes events for state changes
 * - Encapsulation: Private state with controlled access through behavior
 *
 * @domain Notification Context - Webhook Aggregate
 * @layer Domain Aggregates
 */

/**
 * Webhook Aggregate Root
 *
 * Central aggregate root that coordinates webhook business operations.
 * Manages consistency across the aggregate boundary and publishes domain events.
 */
export class WebhookAggregate extends AggregateRootBase {
  private _entity: WebhookEntity;
  private readonly clock: Clock;
  private readonly eventMetadata: EventMetadata;

  private constructor(
    entity: WebhookEntity,
    clock: Clock,
    eventMetadata: EventMetadata,
  ) {
    super();
    this._entity = entity;
    this.clock = clock;
    this.eventMetadata = eventMetadata;
  }

  /**
   * Factory method to create a new Webhook aggregate
   *
   * @param props - Webhook entity properties (should include createdAt, version)
   * @param clock - Clock instance for time operations
   * @param eventMetadata - Event metadata for domain events
   * @returns Result containing WebhookAggregate or DomainError
   */
  public static create(
    props: WebhookDomainState,
    clock: Clock,
    eventMetadata: EventMetadata,
  ): Result<WebhookAggregate, DomainError> {
    // Create timestamp VOs for lifecycle fields using Clock injection
    const createdAtResult = props.createdAt
      ? createWebhookCreatedAt(props.createdAt.value) // Extract Date from existing VO
      : createdAtNow(clock);

    if (!createdAtResult.ok) {
      return err(createdAtResult.error);
    }

    const updatedAtResult = props.updatedAt
      ? createWebhookUpdatedAt(props.updatedAt.value) // Extract Date from existing VO
      : updatedAtNow(clock);

    if (!updatedAtResult.ok) {
      return err(updatedAtResult.error);
    }

    // Validate monotonic time constraint
    const monotonicTimeResult = validateMonotonicTime(
      createdAtResult.value,
      updatedAtResult.value,
    );
    if (!monotonicTimeResult.ok) {
      return err(monotonicTimeResult.error);
    }

    // Create version VO for lifecycle management
    const versionResult =
      props.version !== undefined
        ? WebhookVersion.create(props.version.value) // Extract number from existing VO
        : initialVersion();

    if (!versionResult.ok) {
      return err(versionResult.error);
    }

    // Ensure props have required lifecycle fields with VOs for proper domain state
    const entityProps: WebhookDomainState = {
      ...props,
      createdAt: createdAtResult.value, // Keep as VO
      updatedAt: updatedAtResult.value, // Keep as VO
      version: versionResult.value, // Keep as VO
    };

    // Create the entity first
    const entityResult = WebhookEntity.create(entityProps);
    if (!entityResult.ok) {
      return err(entityResult.error);
    }

    // Create the aggregate
    const aggregate = new WebhookAggregate(
      entityResult.value,
      clock,
      eventMetadata,
    );

    // Create typed WebhookCreatedEvent with only business data
    const createdEvent = WebhookCreatedEvent.create({
      id: entityProps.id.value,
      name: entityProps.name.value,
      description: entityProps.description?.value,
      targetUrl: entityProps.targetUrl.value,
      webhookEventType: entityProps.webhookEventType.value,
      method: entityProps.method.value,
      headers: entityProps.headers?.value,
      signingSecret: entityProps.signingSecret?.value,
      status: entityProps.status.value,
      verifyTls: entityProps.verifyTls?.value,
      requestTimeoutMs: entityProps.requestTimeoutMs?.value,
      connectTimeoutMs: entityProps.connectTimeoutMs?.value,
      rateLimitPerMinute: entityProps.rateLimitPerMinute?.value,
    });

    // Apply as domain event with clean business data
    const domainEvent: DomainEvent = {
      type: createdEvent.eventType,
      version: Number(createdEvent.eventVersion),
      occurredAt: clock.now(),
      aggregateId: entityProps.id.value,
      aggregateType: 'Webhook',
      data: createdEvent.payload,
      metadata: eventMetadata,
    };

    aggregate.apply(domainEvent);

    return ok(aggregate);
  }

  /**
   * Factory method to reconstitute aggregate from persistence
   *
   * @param entity - Reconstituted entity
   * @param clock - Clock instance
   * @param eventMetadata - Event metadata for domain events
   * @returns WebhookAggregate
   */
  public static reconstitute(
    entity: WebhookEntity,
    clock: Clock,
    eventMetadata: EventMetadata,
  ): WebhookAggregate {
    const aggregate = new WebhookAggregate(entity, clock, eventMetadata);
    // Set version based on entity state for proper aggregate versioning
    aggregate._version = entity.version.value;
    return aggregate;
  }
  /**
   * Event handler for domain events
   * Updates aggregate state based on events for proper rehydration
   */
  protected when(event: DomainEvent): void {
    switch (event.type) {
      case 'NotificationWebhookConfigWebhookCreated.v1':
      case 'NotificationWebhookConfigWebhookUpdated.v1': {
        // Both events now have the same domain shape - simple merge
        const d = event.data as {
          id: string;
          name: string;
          description?: string;
          targetUrl: string;
          webhookEventType: string;
          method: WebhookMethodValue;
          headers?: Record<string, unknown>;
          signingSecret?: string;
          status: WebhookStatusValue;
          verifyTls?: boolean;
          requestTimeoutMs?: number;
          connectTimeoutMs?: number;
          rateLimitPerMinute?: number;
        };

        // For event replay, we need to reconstruct the full snapshot
        // Note: credentialsRef is a reference - actual secrets would be retrieved separately
        const currentSnapshot = this._entity?.toSnapshot() || {};

        const entityResult = WebhookEntity.fromSnapshot({
          id: d.id,
          name: d.name,
          description: d.description,
          targetUrl: d.targetUrl,
          webhookEventType: d.webhookEventType,
          method: d.method,
          headers: d.headers,
          signingSecret: d.signingSecret,
          status: d.status,
          verifyTls: d.verifyTls,
          requestTimeoutMs: d.requestTimeoutMs,
          connectTimeoutMs: d.connectTimeoutMs,
          rateLimitPerMinute: d.rateLimitPerMinute,
          createdAt: currentSnapshot.createdAt || event.occurredAt,
          updatedAt: event.occurredAt, // Always update the timestamp
          version: currentSnapshot.version + 1 || 1,
        });

        if (entityResult.ok) {
          this._entity = entityResult.value;
        }
        break;
      }
      case 'WebhookDeleted': {
        // Optional: add a flag to track deletion state
        // this._isDeleted = true;
        break;
      }
      default:
        // Unknown event type - log or handle gracefully
        break;
    }
  }

  /**
   * Apply snapshot to restore aggregate state
   */
  protected applySnapshot(
    snapshot: WebhookSnapshotProps,
  ): Result<void, DomainError> {
    // Use the entity's fromSnapshot method to handle all VO creation and validation
    const entityResult = WebhookEntity.fromSnapshot(snapshot);

    if (!entityResult.ok) {
      return err({
        code: 'WEBHOOK.SNAPSHOT_APPLICATION_FAILED',
        title: 'Snapshot Application Failed',
        detail: 'Failed to apply snapshot due to invalid data',
        category: 'domain',
        retryable: false,
        context: {
          originalError: entityResult.error,
          snapshotCode: snapshot.id,
        },
      });
    }

    // Entity is valid and fully reconstituted
    this._entity = entityResult.value;
    return ok(undefined);
  }

  /**
   * Create snapshot of current aggregate state
   */
  public createSnapshot(): WebhookSnapshotProps {
    return this._entity.toSnapshot();
  }

  /**
   * Get current domain state for application layer
   *
   * This method provides access to the rich domain state without
   * requiring the application layer to depend on infrastructure mappers.
   * Maintains clean architecture by keeping dependencies pointing inward.
   *
   * @returns Current domain state with value objects
   */
  public toDomainState(): WebhookDomainState {
    return this._entity.getDomainState();
  }

  // ======================
  // Entity Access
  // ======================

  /**
   * Get the aggregate ID (required for aggregate identity)
   */
  public get id(): WebhookId {
    return this._entity.id;
  }

  /**
   * Get the underlying entity for data access
   * Use this for all data queries and getter access
   */
  public get entity(): WebhookEntity {
    return this._entity;
  }

  // ======================
  // Private Helpers
  // ======================

  /**
   * Detects if any field values have actually changed
   * @param validatedFields - New field values to check
   * @returns true if any changes detected, false otherwise
   */
  private detectChanges(
    validatedFields: ValidatedWebhookUpdateFields,
  ): boolean {
    // Check each field for actual value changes using value object equality
    if (validatedFields.name !== undefined) {
      if (hasValueChanged(this._entity.name, validatedFields.name)) {
        return true;
      }
    }
    if (validatedFields.description !== undefined) {
      if (
        hasValueChanged(this._entity.description, validatedFields.description)
      ) {
        return true;
      }
    }
    if (validatedFields.targetUrl !== undefined) {
      if (hasValueChanged(this._entity.targetUrl, validatedFields.targetUrl)) {
        return true;
      }
    }
    if (validatedFields.webhookEventType !== undefined) {
      if (
        hasValueChanged(
          this._entity.webhookEventType,
          validatedFields.webhookEventType,
        )
      ) {
        return true;
      }
    }
    if (validatedFields.method !== undefined) {
      if (hasValueChanged(this._entity.method, validatedFields.method)) {
        return true;
      }
    }
    if (validatedFields.headers !== undefined) {
      if (hasValueChanged(this._entity.headers, validatedFields.headers)) {
        return true;
      }
    }
    if (validatedFields.signingSecret !== undefined) {
      if (
        hasValueChanged(
          this._entity.signingSecret,
          validatedFields.signingSecret,
        )
      ) {
        return true;
      }
    }
    if (validatedFields.status !== undefined) {
      if (hasValueChanged(this._entity.status, validatedFields.status)) {
        return true;
      }
    }
    if (validatedFields.verifyTls !== undefined) {
      if (hasValueChanged(this._entity.verifyTls, validatedFields.verifyTls)) {
        return true;
      }
    }
    if (validatedFields.requestTimeoutMs !== undefined) {
      if (
        hasValueChanged(
          this._entity.requestTimeoutMs,
          validatedFields.requestTimeoutMs,
        )
      ) {
        return true;
      }
    }
    if (validatedFields.connectTimeoutMs !== undefined) {
      if (
        hasValueChanged(
          this._entity.connectTimeoutMs,
          validatedFields.connectTimeoutMs,
        )
      ) {
        return true;
      }
    }
    if (validatedFields.rateLimitPerMinute !== undefined) {
      if (
        hasValueChanged(
          this._entity.rateLimitPerMinute,
          validatedFields.rateLimitPerMinute,
        )
      ) {
        return true;
      }
    }
    // No changes detected
    return false;
  }

  // ======================
  // Business Operations (Event Publishing)
  // ======================

  /**
   * Batch update multiple properties atomically
   *
   * This method eliminates the logic overlap between factory and individual update methods:
   * - Single optimistic concurrency check
   * - Single version bump
   * - Single domain event published
   * - Atomic transaction for all field changes
   *
   * @param validatedFields - Pre-validated field values (factory responsibility)
   * @param expectedVersion - Optional version for optimistic concurrency control
   * @returns Result indicating success or failure
   */
  public updateBatch(
    validatedFields: ValidatedWebhookUpdateFields,
    expectedVersion?: number,
  ): Result<void, DomainError> {
    // Single optimistic concurrency check (not per field like individual methods)
    if (
      expectedVersion != null &&
      expectedVersion !== this._entity.version.value
    ) {
      return err({
        ...WebhookErrors.CONCURRENCY_CONFLICT,
        context: {
          expected: expectedVersion,
          actual: this._entity.version.value,
          aggregateId: this._entity.id.value,
        },
      });
    }

    const before = this._entity.toSnapshot();

    // Check if any field actually changed by comparing values
    const hasChanges = this.detectChanges(validatedFields);

    // If no changes detected, return success without creating events
    if (!hasChanges) {
      return ok(undefined);
    }

    // Single version bump for entire batch (not per field)
    const currentVersionResult = createWebhookVersion(before.version);
    if (!currentVersionResult.ok) {
      return err(currentVersionResult.error);
    }

    const nextVersionResult = bumpVersion(currentVersionResult.value);
    if (!nextVersionResult.ok) {
      return err(nextVersionResult.error);
    }

    const nextVersion = nextVersionResult.value.value;

    // Single timestamp for entire batch operation
    const updatedAtResult = updatedAtNow(this.clock);
    if (!updatedAtResult.ok) {
      return err(updatedAtResult.error);
    }

    const updatedAt = updatedAtResult.value.value;

    // Apply all field changes atomically through entity
    let currentEntity = this._entity;

    // Apply each validated field change with type safety
    if (validatedFields.name !== undefined) {
      const entityResult = currentEntity.withName(
        validatedFields.name,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.description !== undefined) {
      const entityResult = currentEntity.withDescription(
        validatedFields.description,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.targetUrl !== undefined) {
      const entityResult = currentEntity.withTargetUrl(
        validatedFields.targetUrl,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.webhookEventType !== undefined) {
      const entityResult = currentEntity.withWebhookEventType(
        validatedFields.webhookEventType,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.method !== undefined) {
      const entityResult = currentEntity.withMethod(
        validatedFields.method,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.headers !== undefined) {
      const entityResult = currentEntity.withHeaders(
        validatedFields.headers,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.signingSecret !== undefined) {
      const entityResult = currentEntity.withSigningSecret(
        validatedFields.signingSecret,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.status !== undefined) {
      const entityResult = currentEntity.withStatus(
        validatedFields.status,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.verifyTls !== undefined) {
      const entityResult = currentEntity.withVerifyTls(
        validatedFields.verifyTls,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.requestTimeoutMs !== undefined) {
      const entityResult = currentEntity.withRequestTimeoutMs(
        validatedFields.requestTimeoutMs,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.connectTimeoutMs !== undefined) {
      const entityResult = currentEntity.withConnectTimeoutMs(
        validatedFields.connectTimeoutMs,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    if (validatedFields.rateLimitPerMinute !== undefined) {
      const entityResult = currentEntity.withRateLimitPerMinute(
        validatedFields.rateLimitPerMinute,
        updatedAt,
        nextVersion,
      );
      if (!entityResult.ok) return err(entityResult.error);
      currentEntity = entityResult.value;
    }

    // Commit the batched changes
    this._entity = currentEntity;

    // Create domain-shaped update event (same structure as created event)
    const updatedEvent = WebhookUpdatedEvent.create({
      id: this._entity.id.value,
      name: this._entity.name.value,
      description: this._entity.description?.value,
      targetUrl: this._entity.targetUrl.value,
      webhookEventType: this._entity.webhookEventType.value,
      method: this._entity.method.value,
      headers: this._entity.headers?.value,
      signingSecret: this._entity.signingSecret?.value,
      status: this._entity.status.value,
      verifyTls: this._entity.verifyTls?.value,
      requestTimeoutMs: this._entity.requestTimeoutMs?.value,
      connectTimeoutMs: this._entity.connectTimeoutMs?.value,
      rateLimitPerMinute: this._entity.rateLimitPerMinute?.value,
    });

    // Apply as domain event with clean business data
    const domainEvent: DomainEvent = {
      type: updatedEvent.eventType,
      version: Number(updatedEvent.eventVersion),
      occurredAt: updatedAt,
      aggregateId: this._entity.id.value,
      aggregateType: 'Webhook',
      data: updatedEvent.payload,
      metadata: this.eventMetadata,
    };

    this.apply(domainEvent);

    return ok(undefined);
  }

  /**
   * Set entity to get
   */
  public get(): Result<void, DomainError> {
    const methodResult = createWebhookMethod('get');
    if (!methodResult.ok) return err(methodResult.error);
    return this.updateBatch({ method: methodResult.value });
  }

  /**
   * Set entity to post
   */
  public post(): Result<void, DomainError> {
    const methodResult = createWebhookMethod('post');
    if (!methodResult.ok) return err(methodResult.error);
    return this.updateBatch({ method: methodResult.value });
  }

  /**
   * Set entity to put
   */
  public put(): Result<void, DomainError> {
    const methodResult = createWebhookMethod('put');
    if (!methodResult.ok) return err(methodResult.error);
    return this.updateBatch({ method: methodResult.value });
  }

  /**
   * Set entity to patch
   */
  public patch(): Result<void, DomainError> {
    const methodResult = createWebhookMethod('patch');
    if (!methodResult.ok) return err(methodResult.error);
    return this.updateBatch({ method: methodResult.value });
  }

  /**
   * Set entity to active
   */
  public activate(): Result<void, DomainError> {
    const statusResult = createWebhookStatus('active');
    if (!statusResult.ok) return err(statusResult.error);
    return this.updateBatch({ status: statusResult.value });
  }

  /**
   * Set entity to paused
   */
  public paused(): Result<void, DomainError> {
    const statusResult = createWebhookStatus('paused');
    if (!statusResult.ok) return err(statusResult.error);
    return this.updateBatch({ status: statusResult.value });
  }

  /**
   * Set entity to disabled
   */
  public disable(): Result<void, DomainError> {
    const statusResult = createWebhookStatus('disabled');
    if (!statusResult.ok) return err(statusResult.error);
    return this.updateBatch({ status: statusResult.value });
  }

  /**
   * Delete the webhook entity (business operation with event publishing)
   *
   * @returns Result indicating success or failure
   */
  public delete(): Result<void, DomainError> {
    // Create timestamp VO for delete operation using injected clock
    const deletedAtResult = updatedAtNow(this.clock);
    if (!deletedAtResult.ok) {
      return err(deletedAtResult.error);
    }

    // Create and apply domain event for deletion
    const domainEvent: DomainEvent = {
      type: 'WebhookDeleted',
      version: 1,
      occurredAt: deletedAtResult.value.value, // Extract Date from VO
      aggregateId: this._entity.id.value,
      aggregateType: 'Webhook',
    };

    this.apply(domainEvent);

    return ok(undefined);
  }

  // ======================
  // Query Methods (Delegate to Entity)
  // ======================

  /**
   * Check if this aggregate represents the same entity as another
   */
  public sameAs(other: WebhookAggregate): boolean {
    return this._entity.sameAs(other._entity);
  }
}
